import {
  boolean,
  char,
  customType,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  time,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';

import { workspaces } from './core';

const citext = customType<{ data: string }>({ dataType() { return 'citext'; } });

export const locationType = pgEnum('location_type', ['shop','mobile','fleet_site','customer_site']);

export const profiles = pgTable('profiles', {
  id: uuid('id').primaryKey(),
  displayName: text('display_name'),
  phone: text('phone'),
  avatarUrl: text('avatar_url'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const locations = pgTable('locations', {
  id: uuid('id').defaultRandom().primaryKey(),
  workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  locationType: locationType('location_type').default('shop').notNull(),
  addressLine1: text('address_line1'),
  addressLine2: text('address_line2'),
  city: text('city'),
  region: text('region'),
  postalCode: text('postal_code'),
  countryCode: char('country_code', { length: 2 }).default('US').notNull(),
  latitude: numeric('latitude'),
  longitude: numeric('longitude'),
  phone: text('phone'),
  isActive: boolean('is_active').default(true).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const workspaceSettings = pgTable('workspace_settings', {
  workspaceId: uuid('workspace_id').primaryKey().references(() => workspaces.id, { onDelete: 'cascade' }),
  ownerName: text('owner_name'),
  phone: text('phone'),
  email: citext('email'),
  addressLine1: text('address_line1'),
  addressLine2: text('address_line2'),
  city: text('city'),
  region: text('region'),
  postalCode: text('postal_code'),
  countryCode: char('country_code', { length: 2 }).default('US').notNull(),
  websiteUrl: text('website_url'),
  logoUrl: text('logo_url'),
  bookingSlug: citext('booking_slug'),
  terminology: jsonb('terminology').default({ quote: 'Quote', service: 'Service', vehicle: 'Vehicle', customer: 'Customer' }).notNull(),
  openingTime: time('opening_time'),
  closingTime: time('closing_time'),
  workingDays: text('working_days').array().default(['Monday','Tuesday','Wednesday','Thursday','Friday']).notNull(),
  dayHours: jsonb('day_hours').default({}).notNull(),
  serviceRadiusMiles: numeric('service_radius_miles'),
  bufferTimeBefore: integer('buffer_time_before').default(0).notNull(),
  bufferTimeAfter: integer('buffer_time_after').default(0).notNull(),
  minLeadTimeHours: integer('min_lead_time_hours').default(2).notNull(),
  maxAdvanceDays: integer('max_advance_days').default(30).notNull(),
  slotDurationMinutes: integer('slot_duration_minutes').default(30).notNull(),
  allowMultiDayBookings: boolean('allow_multi_day_bookings').default(false).notNull(),
  requireApproval: boolean('require_approval').default(false).notNull(),
  cancellationWindowHours: integer('cancellation_window_hours').default(24).notNull(),
  allowCancellation: boolean('allow_cancellation').default(true).notNull(),
  allowRescheduling: boolean('allow_rescheduling').default(true).notNull(),
  rescheduleWindowHours: integer('reschedule_window_hours').default(24).notNull(),
  termsAndConditions: text('terms_and_conditions'),
  requireTermsAcceptance: boolean('require_terms_acceptance').default(false).notNull(),
  taxRate: numeric('tax_rate').default('0').notNull(),
  oilPricePerQuart: numeric('oil_price_per_quart').default('0').notNull(),
  wasteOilFee: numeric('waste_oil_fee').default('0').notNull(),
  wasteOilFeeEnabled: boolean('waste_oil_fee_enabled').default(false).notNull(),
  shopFeeEnabled: boolean('shop_fee_enabled').default(false).notNull(),
  shopFeeType: text('shop_fee_type').default('fixed').notNull(),
  shopFeeValue: numeric('shop_fee_value').default('0').notNull(),
  shopFeeDescription: text('shop_fee_description'),
  surchargeEnabled: boolean('surcharge_enabled').default(false).notNull(),
  surchargeType: text('surcharge_type').default('percentage').notNull(),
  surchargeValue: numeric('surcharge_value').default('0').notNull(),
  surchargeDescription: text('surcharge_description'),
  paymentProvider: text('payment_provider'),
  bookingEnabled: boolean('booking_enabled').default(true).notNull(),
  marketplaceOptIn: boolean('marketplace_opt_in').default(false).notNull(),
  operationalSettings: jsonb('operational_settings').default({}).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});
