export type NewsletterCategory = "education" | "maintenance_tip" | "psa" | "recall" | "seasonal" | "offer" | "fleet" | "trust";

export interface NewsletterIssue {
  week: number;
  category: NewsletterCategory;
  subject: string;
  preheader: string;
  headline: string;
  body: string;
  ctaLabel?: string;
  ctaUrl?: string;
}

const BOOK = "https://momsoilchange.servicewriter.xyz";
const SITE = "https://momsoilchange.com";

export const NEWSLETTER_ISSUES: NewsletterIssue[] = [
  { week: 1, category: "education", subject: "What actually happens during a mobile oil change?", preheader: "Driveway to done, without the waiting room.", headline: "Your oil change, without losing your day", body: "We verify the vehicle, confirm the correct oil and filter, perform the service, inspect key maintenance items, and leave the work area clean. Mobile should mean convenient, not careless.", ctaLabel: "Book Mobile Service", ctaUrl: BOOK },
  { week: 2, category: "maintenance_tip", subject: "5 signs your oil may be overdue", preheader: "Your car often gives clues before the dashboard does.", headline: "Your engine may be asking for attention", body: "Watch for a maintenance reminder, low oil level, increased engine noise, overdue mileage, or a recent stretch of heavy stop-and-go driving. Your real driving pattern matters more than one universal number.", ctaLabel: "Check Your Schedule", ctaUrl: BOOK },
  { week: 3, category: "education", subject: "Synthetic oil without the sales pitch", preheader: "What you are really paying for.", headline: "Better stability under heat, cold, and load", body: "Full synthetic oil is engineered for more consistent performance across temperature extremes and longer service intervals. The correct choice still starts with the specification required by your engine.", ctaLabel: "View Full Synthetic Service", ctaUrl: `${SITE}/services/full-synthetic-oil-change` },
  { week: 4, category: "psa", subject: "Oil reminder or oil-pressure warning? Big difference.", preheader: "One can wait. One may not.", headline: "Know which dashboard light you are seeing", body: "An oil-life reminder generally means routine service is due. A red oil-pressure warning can indicate a lubrication problem that may require shutting the engine off immediately and having the vehicle checked.", ctaLabel: "Read More Tips", ctaUrl: `${SITE}/blog` },
  { week: 5, category: "maintenance_tip", subject: "Why short trips can be hard on engine oil", preheader: "Low mileage does not always mean easy driving.", headline: "Ten-minute trips still count", body: "Engines that rarely reach full operating temperature can accumulate moisture and fuel dilution. If most of your driving is short, local, or stop-and-go, severe-service guidance may be more relevant than annual mileage.", ctaLabel: "Book When Due", ctaUrl: BOOK },
  { week: 6, category: "education", subject: "Do you really need to pre-fill an oil filter?", preheader: "Modern engines make this old rule less universal.", headline: "A common oil-change myth", body: "Many modern filters are mounted sideways, upside down, or use top-mounted cartridges that cannot realistically be pre-filled. The manufacturer service procedure matters more than a one-size-fits-all habit.", ctaLabel: "More Maintenance Education", ctaUrl: `${SITE}/blog` },
  { week: 7, category: "seasonal", subject: "Cold mornings change what your oil has to do", preheader: "Viscosity matters most at startup.", headline: "Cold starts are where the oil earns its keep", body: "The correct winter viscosity helps oil circulate quickly after startup. Going thicker just because an engine has miles on it can work against the lubrication system if it is outside the manufacturer specification.", ctaLabel: "Schedule Service", ctaUrl: BOOK },
  { week: 8, category: "maintenance_tip", subject: "Your cabin air filter affects more than smell", preheader: "Weak airflow may be telling you something.", headline: "One small filter, one noticeable difference", body: "Cabin filters trap dust, pollen, and debris before air reaches the passenger compartment. Weak vent airflow or a musty smell can be signs that the filter is overdue.", ctaLabel: "See Cabin Filter Service", ctaUrl: `${SITE}/services/cabin-air-filter-replacement` },
  { week: 9, category: "maintenance_tip", subject: "Dirty-looking does not always mean replace now", preheader: "Why we inspect before recommending a filter.", headline: "Inspect first. Replace when needed.", body: "A little surface dust is normal. Restriction, heavy loading, damage, or an expired interval are better reasons for replacement. Maintenance should be based on evidence, not fear.", ctaLabel: "See Air Filter Service", ctaUrl: `${SITE}/services/air-filter-replacement` },
  { week: 10, category: "education", subject: "What high-mileage oil actually means", preheader: "Useful formulation, not magic repair.", headline: "High-mileage oil explained simply", body: "High-mileage formulas often include additive packages intended for older seals and engines with more wear. They can be useful, but they do not repair mechanical problems and still must meet the correct viscosity and specification.", ctaLabel: "Explore High Mileage Service", ctaUrl: `${SITE}/services/high-mileage-oil-change` },
  { week: 11, category: "psa", subject: "Low oil and old oil are two different problems", preheader: "Clean-looking oil can still be dangerously low.", headline: "Check the level, not just the color", body: "Oil condition and oil quantity are separate maintenance questions. Engines can consume or leak oil between services, so periodic level checks can catch a problem before it becomes expensive.", ctaLabel: "Schedule Maintenance", ctaUrl: BOOK },
  { week: 12, category: "maintenance_tip", subject: "Wipers should clear the glass in one clean pass", preheader: "Streaking matters when the weather gets worse.", headline: "Visibility is maintenance too", body: "Worn blades can chatter, smear, skip, or leave sections of windshield untouched. Replace them when performance drops instead of waiting for the rubber to tear completely.", ctaLabel: "See Wiper Service", ctaUrl: `${SITE}/services/wiper-blade-replacement` },
  { week: 13, category: "seasonal", subject: "What winter leaves behind", preheader: "A practical spring maintenance check.", headline: "Give the car a post-winter look", body: "Salt, cold starts, potholes, and short trips all add up. Spring is a good time to check fluids, filters, wipers, tires, battery condition, and any warning lights that showed up over winter.", ctaLabel: "Book Spring Service", ctaUrl: BOOK },
  { week: 14, category: "education", subject: "Why the correct oil filter matters", preheader: "A filter is not just a generic can.", headline: "Fitment is part of the oil change", body: "Filter media, bypass behavior, anti-drainback design, size, and sealing dimensions vary by application. The right filter is part of doing the service correctly.", ctaLabel: "Book With MOMS", ctaUrl: BOOK },
  { week: 15, category: "psa", subject: "Oil-pressure warning? Do not treat it like a reminder.", preheader: "This one can become expensive fast.", headline: "One warning light you should not ignore", body: "If the oil-pressure warning stays on while the engine is running, shut the engine off when it is safe and have the cause checked before continuing. Low pressure can damage an engine quickly." },
  { week: 16, category: "maintenance_tip", subject: "How often should you really change your oil?", preheader: "The answer depends on the vehicle and how you drive.", headline: "Stop guessing by one universal mileage number", body: "Modern intervals vary widely. Follow the manufacturer interval or oil-life system, then account for severe use such as short trips, extended idling, towing, extreme temperatures, and heavy traffic.", ctaLabel: "Read the Guide", ctaUrl: `${SITE}/how-often-to-change-oil` },
  { week: 17, category: "education", subject: "Dark oil is not automatically bad oil", preheader: "Color alone cannot tell the whole story.", headline: "Oil can darken while still doing its job", body: "Detergent additives are designed to suspend contaminants. Service decisions should be based on interval, specification, level, condition, and vehicle requirements, not color alone." },
  { week: 18, category: "fleet", subject: "Fleet maintenance is really a downtime problem", preheader: "The service itself is only part of the cost.", headline: "Maintenance where the vehicles already are", body: "For fleets, moving units to a shop can cost more time than the service itself. On-site preventive maintenance can reduce shuttle time and let managers schedule service around operating hours.", ctaLabel: "Fleet Maintenance", ctaUrl: `${SITE}/fleet-maintenance` },
  { week: 19, category: "offer", subject: "Oil change day does not need to take over your day", preheader: "Your driveway can be the waiting room.", headline: "Stay home. Keep working. We come to you.", body: "Routine maintenance should not require rearranging an entire afternoon. MOMS brings the oil change to your home or workplace so you can keep doing what you were already doing.", ctaLabel: "Book Mobile Service", ctaUrl: BOOK },
  { week: 20, category: "maintenance_tip", subject: "Tire pressure changes with temperature", preheader: "A seasonal pressure drop is normal, but it still matters.", headline: "Check pressure when seasons change", body: "Tire pressure falls as outside temperature drops. Check pressures cold and use the specification on the vehicle placard, not the maximum pressure printed on the tire sidewall." },
  { week: 21, category: "recall", subject: "Recall notices are worth opening", preheader: "A two-minute VIN check can reveal an open safety campaign.", headline: "Do not ignore that recall letter", body: "Safety recalls can involve brakes, steering, airbags, electrical systems, cameras, fuel systems, and more. Check your VIN with NHTSA, then contact the manufacturer dealer for recall repair.", ctaLabel: "Check NHTSA Recalls", ctaUrl: "https://www.nhtsa.gov/recalls" },
  { week: 22, category: "education", subject: "What motor-oil viscosity numbers actually mean", preheader: "0W-20 is not a quality grade.", headline: "Those numbers on the bottle matter", body: "The first number relates to cold-temperature flow behavior; the second describes viscosity at operating temperature. Always use a viscosity range and specification approved for your engine.", ctaLabel: "Motor Oil Lookup", ctaUrl: `${SITE}/motor-oil-lookup` },
  { week: 23, category: "maintenance_tip", subject: "A small oil leak can become a big maintenance issue", preheader: "Parking-spot stains are information.", headline: "Do not normalize a growing leak", body: "Leaks can come from filters, drain plugs, valve covers, oil pans, timing covers, and other seals. If you notice new spots or a dropping oil level, identify the source instead of topping it off indefinitely." },
  { week: 24, category: "seasonal", subject: "Summer road trip? Check these before you leave", preheader: "Oil is only one item on the pre-trip list.", headline: "Five-minute checks can prevent a ruined trip", body: "Before a long drive, check oil level, coolant when cold, tire pressure, tread, washer fluid, and warning lights. If service is due soon, doing it before the trip is usually the easier move.", ctaLabel: "Book Before Your Trip", ctaUrl: BOOK },
  { week: 25, category: "education", subject: "Why different engines take different amounts of oil", preheader: "Five quarts is not a universal capacity.", headline: "Oil capacity depends on the engine", body: "Engine design, filter size, oil coolers, and manufacturer specifications all affect capacity. Correct fill quantity should be verified for the exact vehicle and engine." },
  { week: 26, category: "trust", subject: "What we check before we pour anything into your engine", preheader: "Fitment first. Service second.", headline: "Correct oil starts with identifying the vehicle", body: "We verify viscosity, specification, capacity, and filter fitment before service. Different trims and engines inside the same model line can have different requirements.", ctaLabel: "Book With MOMS", ctaUrl: BOOK },
  { week: 27, category: "psa", subject: "Overfilling oil is not extra protection", preheader: "More oil is not better.", headline: "Correct level matters", body: "Too much oil can create its own problems, including aeration in some engines. Fill to the specified capacity, verify the level correctly, and avoid topping beyond the full mark." },
  { week: 28, category: "maintenance_tip", subject: "Severe-service schedules exist for a reason", preheader: "City driving can qualify even when mileage stays low.", headline: "Your driving pattern matters", body: "Short trips, extended idling, towing, dusty roads, frequent cold starts, and heavy traffic can all affect maintenance intervals. Use the schedule that matches how the vehicle is actually driven." },
  { week: 29, category: "education", subject: "Synthetic blend vs. full synthetic", preheader: "Start with the engine specification.", headline: "Choose by requirement first", body: "Both can be valid when they meet the required specification. Full synthetic generally provides stronger performance margins, but the correct choice begins with what the engine requires.", ctaLabel: "Compare Services", ctaUrl: `${SITE}/services` },
  { week: 30, category: "maintenance_tip", subject: "Oil-life monitors do not measure oil level", preheader: "60% oil life does not mean 60% full.", headline: "Oil life and oil level are different", body: "Oil-life systems estimate service interval from operating conditions. They do not replace checking oil quantity, and a vehicle can show plenty of remaining oil life while the actual level is low." },
  { week: 31, category: "seasonal", subject: "Back-to-school driving changes your maintenance pattern", preheader: "Pickup lines and short trips add up.", headline: "School traffic counts as real engine use", body: "Morning drop-offs, sports runs, errands, and idling can create a lot of engine operating time while adding relatively few miles. Keep that in mind when judging service intervals.", ctaLabel: "Schedule Fall Service", ctaUrl: BOOK },
  { week: 32, category: "psa", subject: "A burning-oil smell deserves attention", preheader: "The smell may be your first clue.", headline: "If you smell oil, investigate it", body: "Oil leaking onto hot engine or exhaust components can create smoke and odor. If the smell persists, especially after service, check for leaks or spilled oil instead of assuming it will always burn off." },
  { week: 33, category: "maintenance_tip", subject: "Why battery problems show up when temperatures swing", preheader: "Heat ages batteries. Cold exposes the weakness.", headline: "Battery season starts before winter", body: "Slow cranking, dim lights during startup, age, or repeated jump-starts are all reasons to test the battery before a cold morning leaves you stranded." },
  { week: 34, category: "education", subject: "What an anti-drainback valve in an oil filter does", preheader: "A small valve with an important job.", headline: "Filter design matters between starts", body: "Depending on filter orientation and engine design, an anti-drainback valve helps reduce oil draining backward out of the filter after shutdown. It is another reason correct filter fitment matters." },
  { week: 35, category: "trust", subject: "Why we do not replace every dirty-looking filter", preheader: "Maintenance should be evidence-based.", headline: "Inspect, explain, then replace", body: "A little dirt is normal. Damage, restriction, heavy loading, or an expired interval are what matter. Our approach is to inspect first and recommend replacement when the evidence supports it.", ctaLabel: "See Our Services", ctaUrl: `${SITE}/services` },
  { week: 36, category: "psa", subject: "Never crawl under a vehicle supported only by a jack", preheader: "A jack lifts. A stand supports.", headline: "Basic driveway safety is worth repeating", body: "If you work on your own vehicle, use stable ground, proper lift points, wheel chocks, and properly rated support equipment. A lifting jack by itself is not a safe work support." },
  { week: 37, category: "maintenance_tip", subject: "What to do after an oil change", preheader: "A 60-second check can catch a rare problem early.", headline: "Look, listen, verify", body: "After service, make sure warning lights go out normally, there are no fresh leaks, and the engine sounds normal. Checking the parking area after the first drive is an easy habit." },
  { week: 38, category: "education", subject: "Why some engines consume oil between changes", preheader: "Consumption does not always mean an external leak.", headline: "Where did the oil go?", body: "Some engines burn small amounts of oil as part of normal operation, while others consume more as mileage increases. Track the level between services and pay attention to sudden changes." },
  { week: 39, category: "seasonal", subject: "Winter-ready does not start with snow", preheader: "Prepare before the first freeze.", headline: "Cold-weather problems usually give clues first", body: "Check battery condition, tire pressures, wipers, washer fluid, coolant protection, and upcoming service needs before winter weather arrives.", ctaLabel: "Book Winter Prep", ctaUrl: BOOK },
  { week: 40, category: "offer", subject: "Your next oil change can happen while you work", preheader: "No waiting room. No shuttle. No lost afternoon.", headline: "We bring the maintenance bay to you", body: "Book your appointment, park where the service can be performed safely, and keep working while MOMS handles the maintenance.", ctaLabel: "Book at Work", ctaUrl: BOOK },
  { week: 41, category: "recall", subject: "Check your VIN for open recalls before holiday travel", preheader: "A quick lookup can reveal an unresolved safety campaign.", headline: "Recall check before the road trip", body: "Manufacturers and NHTSA publish safety recalls by VIN. If your vehicle has an open recall, schedule the repair with the appropriate dealership.", ctaLabel: "Check NHTSA Recalls", ctaUrl: "https://www.nhtsa.gov/recalls" },
  { week: 42, category: "maintenance_tip", subject: "Do not forget the spare tire", preheader: "It usually gets checked only when you need it most.", headline: "Your backup tire needs maintenance too", body: "If your vehicle carries a spare, include it in periodic pressure checks. Compact spares often require much higher pressure than road tires, so use the vehicle specification." },
  { week: 43, category: "education", subject: "Why direct-injection engines can be harder on oil", preheader: "Modern engine technology raises the workload.", headline: "Modern engines ask more from motor oil", body: "Turbocharging, direct injection, tighter clearances, and emissions systems can increase thermal and chemical demands on oil. Current manufacturer approvals matter, not just viscosity." },
  { week: 44, category: "trust", subject: "The right recommendation starts with one question", preheader: "What does this vehicle actually need?", headline: "Fit the service to the vehicle", body: "A good maintenance plan considers mileage, age, manufacturer schedule, operating conditions, and real inspection findings. We would rather recommend the right work at the right time than stack unnecessary items onto an oil change.", ctaLabel: "Book Mobile Service", ctaUrl: BOOK },
  { week: 45, category: "maintenance_tip", subject: "Why tire rotations matter", preheader: "Front and rear tires often wear differently.", headline: "Even wear helps you use the whole tire", body: "Rotating at the appropriate interval can reduce uneven wear and help all four tires age more consistently. Follow the correct pattern for the vehicle and tire setup." },
  { week: 46, category: "psa", subject: "Never open a hot cooling system", preheader: "Cooling-system pressure can turn coolant into a burn hazard.", headline: "Hot coolant is not worth the risk", body: "If you need to check coolant, let the engine cool fully and follow the manufacturer procedure. If the vehicle is overheating, shut it down safely and address the cause." },
  { week: 47, category: "seasonal", subject: "Holiday traffic is severe service in disguise", preheader: "Idling and short trips can pile up while mileage barely moves.", headline: "Traffic hours still count", body: "Engines accumulate operating time even when the odometer moves slowly. Heavy traffic, delivery work, and repeated short trips can justify closer attention to fluid levels and maintenance intervals." },
  { week: 48, category: "education", subject: "Why API and OEM oil approvals matter", preheader: "Viscosity is only part of choosing the correct oil.", headline: "The letters on the bottle are engineering requirements", body: "Modern oils are tested against performance standards for wear, deposits, emissions compatibility, fuel economy, and more. Use oil that meets the specification required by the engine.", ctaLabel: "Learn More", ctaUrl: `${SITE}/motor-oil-lookup` },
  { week: 49, category: "maintenance_tip", subject: "Start the year with a maintenance baseline", preheader: "Know where the vehicle stands before problems stack up.", headline: "New year, clean starting point", body: "Record current mileage, oil-service status, tire condition, filters, battery age, and warning lights. A simple baseline makes the rest of the year easier because you are not guessing what was done last.", ctaLabel: "Book a Baseline Service", ctaUrl: BOOK },
  { week: 50, category: "fleet", subject: "Fleet PM works best when every unit has a record", preheader: "Consistency beats memory.", headline: "Maintenance should follow the unit", body: "Track service by VIN or unit number, date, mileage, work performed, and upcoming interval. A clear PM history makes overdue units and replacement decisions easier to manage.", ctaLabel: "Talk Fleet Maintenance", ctaUrl: `${SITE}/fleet-maintenance` },
  { week: 51, category: "trust", subject: "What MOMS means by convenient maintenance", preheader: "Convenience should not require sacrificing service quality.", headline: "Mobile does not mean shortcut", body: "Correct fitment, proper materials, clean work practices, inspection, and documentation still matter whether the service happens in a shop or in your driveway.", ctaLabel: "Book With MOMS", ctaUrl: BOOK },
  { week: 52, category: "offer", subject: "52 weeks later: keep next year simple too", preheader: "Thanks for spending the year with MOMS.", headline: "Good maintenance is mostly consistency", body: "Use the right products, follow the right intervals, and address small problems before they become large ones. Whenever the next service is due, MOMS can bring it to your home or workplace.", ctaLabel: "Book Your Next Service", ctaUrl: BOOK },
];

export function renderNewsletter(issue: NewsletterIssue, unsubscribeUrl: string) {
  const cta = issue.ctaLabel && issue.ctaUrl
    ? `<p style="margin:28px 0"><a href="${issue.ctaUrl}" style="display:inline-block;background:#f97316;color:#fff;text-decoration:none;font-weight:800;padding:14px 22px;border-radius:999px">${issue.ctaLabel}</a></p>`
    : "";

  return `<!doctype html><html><body style="margin:0;background:#f8fafc;font-family:Arial,sans-serif;color:#0f172a"><div style="display:none;max-height:0;overflow:hidden">${issue.preheader}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:24px 12px"><tr><td align="center"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;background:#fff;border-radius:20px;overflow:hidden;border:1px solid #e2e8f0"><tr><td style="background:#0f172a;color:#fff;padding:24px 28px"><div style="font-size:12px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:#93c5fd">MOMS Mobile Oil Change®</div><div style="font-size:12px;margin-top:6px;color:#cbd5e1">Weekly maintenance note · Week ${issue.week}</div></td></tr><tr><td style="padding:34px 28px"><h1 style="margin:0 0 16px;font-size:30px;line-height:1.15">${issue.headline}</h1><p style="font-size:17px;line-height:1.7;color:#334155;margin:0">${issue.body}</p>${cta}<div style="margin-top:34px;padding:18px;border-radius:14px;background:#eff6ff;color:#1e3a8a;font-size:14px;line-height:1.6"><strong>MOMS Mobile Oil Change®</strong><br>Mobile preventive maintenance at your home or workplace in the Philadelphia area.</div></td></tr><tr><td style="padding:20px 28px;background:#f1f5f9;color:#64748b;font-size:12px;line-height:1.6">You are receiving this because you subscribed to MOMS maintenance updates. <a href="${unsubscribeUrl}" style="color:#475569">Unsubscribe</a>.</td></tr></table></td></tr></table></body></html>`;
}
