import { supabase } from "@/integrations/supabase/client";
import { queueAppointmentStatusForSync } from "@/offline/outbox/appointments";
import { isOfflineEligibleForCurrentUser } from "@/offline/rollout";
import type { AppointmentFormState } from "@/shared/types/forms";
import { requestAppointmentProviderSync } from "./provider-sync.command";
import { nextApi } from "@/lib/nextApiClient";
import { fetchBusinessSettings, resolveCurrentWorkspace } from "@/application/queries/settings.query";
import { syncAppointmentPrimaryService } from "@/lib/appointmentItemsApi";

export interface SaveAppointmentOptions { existingAppointmentId?: string; isPrefillNew?: boolean; }
export interface SaveAppointmentResult { appointmentId: string; isUpdate: boolean; }

function uuidOrNull(value: unknown): string | null { if (value == null) return null; const normalized=String(value).trim(); if(!normalized||normalized==="undefined"||normalized==="null")return null; return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(normalized)?normalized:null; }
function zonedParts(timestamp:number,timezone:string){const parts=new Intl.DateTimeFormat("en-US",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).formatToParts(new Date(timestamp));const get=(type:Intl.DateTimeFormatPartTypes)=>Number(parts.find(p=>p.type===type)?.value||0);return{year:get("year"),month:get("month"),day:get("day"),hour:get("hour")%24,minute:get("minute"),second:get("second")};}
function workspaceLocalToIso(date:string,time:string,timezone:string):string{const dm=/^(\d{4})-(\d{2})-(\d{2})$/.exec(date),tm=/^(\d{1,2}):(\d{2})(?::(\d{2}))?$/.exec(time);if(!dm||!tm)throw new Error("Invalid appointment date/time");const target={year:+dm[1],month:+dm[2],day:+dm[3],hour:+tm[1],minute:+tm[2],second:+(tm[3]||0)};let candidate=Date.UTC(target.year,target.month-1,target.day,target.hour,target.minute,target.second);for(let i=0;i<3;i++){const r=zonedParts(candidate,timezone),delta=Date.UTC(target.year,target.month-1,target.day,target.hour,target.minute,target.second)-Date.UTC(r.year,r.month-1,r.day,r.hour,r.minute,r.second);candidate+=delta;if(delta===0)break;}const v=zonedParts(candidate,timezone);if(v.year!==target.year||v.month!==target.month||v.day!==target.day||v.hour!==target.hour||v.minute!==target.minute)throw new Error("That local time is not valid in the workspace timezone. Choose another time.");return new Date(candidate).toISOString();}
async function workspaceTimezone(workspaceId:string):Promise<string>{const{data,error}=await(supabase as any).from("workspaces").select("timezone").eq("id",workspaceId).maybeSingle();if(error)throw error;return data?.timezone||"UTC";}
async function sendStaffAppointmentConfirmation(appointmentId:string,workspaceId:string):Promise<void>{const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("Authentication required to send confirmation email.");const response=await fetch(`/api/v1/appointments/${encodeURIComponent(appointmentId)}/confirmation`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","Authorization":`Bearer ${session.access_token}`},body:JSON.stringify({workspace_id:workspaceId})});const body=await response.json().catch(()=>({})) as{error?:{message?:string}};if(!response.ok)throw new Error(body.error?.message||"Confirmation email could not be queued.");}

export async function saveAppointment(formData:AppointmentFormState,options:SaveAppointmentOptions={}):Promise<SaveAppointmentResult>{
  if(!formData.scheduled_date||!formData.scheduled_time)throw new Error("Please select a date and time");const context=await resolveCurrentWorkspace();if(!context)throw new Error("Select a workspace before saving an appointment.");const customerId=uuidOrNull(formData.customer_id);if(!customerId)throw new Error("Select or create a customer before saving this appointment.");const vehicleId=uuidOrNull(formData.vehicle_id);if(!vehicleId)throw new Error("Select or create a vehicle before saving this appointment.");const serviceCatalogId=uuidOrNull(formData.service_catalog_id);if(!serviceCatalogId)throw new Error("Select a service before saving this appointment.");
  const durationMinutes=Math.max(5,Number(formData.duration_minutes??60)),timezone=await workspaceTimezone(context.workspaceId),startsAt=workspaceLocalToIso(formData.scheduled_date,formData.scheduled_time,timezone),endsAt=new Date(Date.parse(startsAt)+durationMinutes*60000).toISOString();
  let resolvedTaxAmount=formData.tax_amount!=null?Number(formData.tax_amount):null;if(resolvedTaxAmount==null&&formData.estimated_cost!=null){const settings=await fetchBusinessSettings();if(settings){const{data}=await(supabase as any).from("workspace_settings").select("tax_rate").eq("workspace_id",context.workspaceId).maybeSingle();resolvedTaxAmount=Number((Number(formData.estimated_cost)*Number(data?.tax_rate??0)/100).toFixed(2));}}
  let resolvedLocationAddress=formData.location_address?.trim()||null;if(!resolvedLocationAddress){const{data:customer}=await(supabase as any).from("customers").select("address_line1,address_line2,city,region,postal_code").eq("workspace_id",context.workspaceId).eq("id",customerId).maybeSingle();if(customer)resolvedLocationAddress=[customer.address_line1,customer.address_line2,customer.city,customer.region,customer.postal_code].filter(Boolean).join(", ")||null;}
  const overrideAvailability=(formData as AppointmentFormState&{override_availability?:boolean}).override_availability===true;
  const payload={workspace_id:context.workspaceId,customer_id:customerId,vehicle_id:vehicleId,starts_at:startsAt,ends_at:endsAt,source:"staff",status:formData.status||"confirmed",notes:formData.notes?.trim()||null,title:formData.title?.trim()||"Appointment",description:formData.description?.trim()||null,guest_name:formData.guest_name?.trim()||null,guest_email:formData.guest_email?.trim()||null,guest_phone:formData.guest_phone?.trim()||null,service_catalog_id:serviceCatalogId,estimated_cost:formData.estimated_cost!=null?Number(formData.estimated_cost):null,tax_amount:resolvedTaxAmount,location_address:resolvedLocationAddress,customer_city:formData.customer_city?.trim()||null,customer_state:formData.customer_state?.trim()||null,customer_postal_code:formData.customer_postal_code?.trim()||null,override_availability:overrideAvailability};
  const shouldUpdate=Boolean(options.existingAppointmentId&&!options.isPrefillNew);if(shouldUpdate&&options.existingAppointmentId){await nextApi.appointments.update(options.existingAppointmentId,payload);await syncAppointmentPrimaryService({workspaceId:context.workspaceId,appointmentId:options.existingAppointmentId,serviceCatalogId});if(formData.sendEmailNotification)await sendStaffAppointmentConfirmation(options.existingAppointmentId,context.workspaceId);return{appointmentId:options.existingAppointmentId,isUpdate:true};}
  const{data:created}=await nextApi.appointments.create(payload);const record=created as{id?:string};if(!record.id)throw new Error("Failed to create appointment");await syncAppointmentPrimaryService({workspaceId:context.workspaceId,appointmentId:record.id,serviceCatalogId});if(formData.sendEmailNotification)await sendStaffAppointmentConfirmation(record.id,context.workspaceId);requestAppointmentProviderSync({appointmentId:record.id,syncMode:"appointment_created",guestEmail:formData.guest_email?.trim()||null}).catch(e=>console.warn("[saveAppointment] provider sync failed",e));return{appointmentId:record.id,isUpdate:false};
}

export interface AutoDispatchResult{autoDispatchEnabled:boolean;topRecommendationName?:string|null;}
export async function tryAutoDispatchAppointment(_appointmentId:string,_formData:AppointmentFormState):Promise<AutoDispatchResult>{const context=await resolveCurrentWorkspace();if(!context)return{autoDispatchEnabled:false};const{data,error}=await(supabase as any).from("workspace_settings").select("operational_settings").eq("workspace_id",context.workspaceId).maybeSingle();if(error||!data)return{autoDispatchEnabled:false};const operational=data.operational_settings&&typeof data.operational_settings==="object"?data.operational_settings as Record<string,unknown>:{};return{autoDispatchEnabled:operational.auto_dispatch_enabled===true,topRecommendationName:null};}
export async function updateAppointmentSchedule(appointmentId:string,scheduledDate:string,scheduledTime:string):Promise<void>{const context=await resolveCurrentWorkspace();if(!context)throw new Error("Select a workspace before rescheduling an appointment.");const{data:existing,error}=await(supabase as any).from("appointments").select("starts_at,ends_at").eq("workspace_id",context.workspaceId).eq("id",appointmentId).maybeSingle();if(error)throw error;if(!existing)throw new Error("Appointment not found");const timezone=await workspaceTimezone(context.workspaceId),startsAt=workspaceLocalToIso(scheduledDate,scheduledTime,timezone),ps=Date.parse(existing.starts_at),pe=Date.parse(existing.ends_at),duration=Number.isFinite(ps)&&Number.isFinite(pe)&&pe>ps?pe-ps:3600000;await nextApi.appointments.update(appointmentId,{workspace_id:context.workspaceId,starts_at:startsAt,ends_at:new Date(Date.parse(startsAt)+duration).toISOString()});}
export async function updateAppointmentStatus(appointmentId:string,newStatus:string):Promise<void>{if(await isOfflineEligibleForCurrentUser()){await queueAppointmentStatusForSync(appointmentId,newStatus);return;}const context=await resolveCurrentWorkspace();if(!context)throw new Error("Select a workspace before updating an appointment.");if(newStatus==="completed")await nextApi.appointments.complete(appointmentId,context.workspaceId);else if(newStatus==="cancelled")await nextApi.appointments.cancel(context.workspaceId,appointmentId);else await nextApi.appointments.update(appointmentId,{workspace_id:context.workspaceId,status:newStatus});if(newStatus==="cancelled"){try{const{releaseAppointmentReservations}=await import("./booking-inventory.command");await releaseAppointmentReservations(appointmentId);}catch(e){console.warn("[updateAppointmentStatus] inventory release failed",e);}}}
