/** Invoices Command — canonical manual invoice writes. */
import { supabase } from "@/integrations/supabase/client";
import { bankersRound } from "@/lib/financialMath";
import { getCurrentAuthUser } from "@/lib/auth/current-user";
import { nextApi } from "@/lib/nextApiClient";
import { getSelectedWorkspaceId } from "@/application/queries/workspaces.selection";

export interface InvoiceLineItemInput{vehicle_id:string|null;service_catalog_id:string|null;description:string;quantity:number;unit_price:number;display_order:number;vin?:string|null;vehicle_year?:number|null;vehicle_make?:string|null;vehicle_model?:string|null;vehicle_trim?:string|null;vehicle_engine?:string|null;oil_type?:string|null;oil_capacity?:string|null;oil_filter?:string|null;vehicle_mileage?:number|null;license_plate?:string|null;odometer_measure?:string|null;}
export interface CreateInvoiceInput{invoice_number:string;bill_to_type:"retail"|"fleet";customer_id:string|null;fleet_client_id:string|null;contact_name:string|null;contact_email:string|null;contact_phone:string|null;issue_date:string;due_date:string|null;payment_terms:string|null;notes:string|null;terms_text:string|null;discount_type:"fixed"|"percentage";discount_amount:number;tax_enabled:boolean;tax_rate:number;waste_oil_fee_enabled:boolean;waste_oil_fee:number;shop_fee_enabled:boolean;shop_fee:number;surcharge_enabled:boolean;surcharge:number;line_items:InvoiceLineItemInput[];}
export interface InvoiceTotals{subtotal:number;effective_discount:number;tax_amount:number;total:number;}
export function computeInvoiceTotals(input:{line_items:InvoiceLineItemInput[];discount_type:"fixed"|"percentage";discount_amount:number;tax_enabled:boolean;tax_rate:number;waste_oil_fee_enabled:boolean;waste_oil_fee:number;shop_fee_enabled:boolean;shop_fee:number;surcharge_enabled:boolean;surcharge:number;}):InvoiceTotals{const lineTotal=input.line_items.reduce((s,li)=>s+(Number(li.quantity)||0)*(Number(li.unit_price)||0),0);const fees=(input.waste_oil_fee_enabled?Number(input.waste_oil_fee)||0:0)+(input.shop_fee_enabled?Number(input.shop_fee)||0:0)+(input.surcharge_enabled?Number(input.surcharge)||0:0);const subtotal=bankersRound(lineTotal+fees,2);const raw=input.discount_type==="percentage"?subtotal*(Number(input.discount_amount)||0)/100:Number(input.discount_amount)||0;const effective_discount=bankersRound(Math.max(0,Math.min(raw,subtotal)),2);const taxable=Math.max(0,subtotal-effective_discount);const tax_amount=input.tax_enabled?bankersRound(taxable*(Number(input.tax_rate)||0)/100,2):0;return{subtotal,effective_discount,tax_amount,total:bankersRound(taxable+tax_amount,2)};}
function workspace(){const id=getSelectedWorkspaceId();if(!id)throw new Error("Select a workspace before changing an invoice.");return id;}
export async function createInvoice(input:CreateInvoiceInput):Promise<string>{const{data:{user}}=await getCurrentAuthUser();if(!user)throw new Error("Not authenticated");const workspace_id=workspace();const t=computeInvoiceTotals(input);const result=await nextApi.invoices.create({workspace_id,...input,status:"draft",subtotal:t.subtotal,discount_amount:t.effective_discount,tax_rate:input.tax_enabled?input.tax_rate:0,tax_amount:t.tax_amount,waste_oil_fee:input.waste_oil_fee_enabled?bankersRound(input.waste_oil_fee,2):0,shop_fee:input.shop_fee_enabled?bankersRound(input.shop_fee,2):0,surcharge:input.surcharge_enabled?bankersRound(input.surcharge,2):0,total:t.total,line_items:input.line_items.map((li,idx)=>({...li,quantity:bankersRound(Number(li.quantity)||0,2),unit_price:bankersRound(Number(li.unit_price)||0,2),display_order:li.display_order??idx}))});return(result.data as{id:string}).id;}
export async function updateInvoice(invoiceId:string,input:CreateInvoiceInput):Promise<void>{const{data:{user}}=await getCurrentAuthUser();if(!user)throw new Error("Not authenticated");const workspace_id=workspace();const t=computeInvoiceTotals(input);await nextApi.invoices.update(invoiceId,{workspace_id,...input,subtotal:t.subtotal,discount_amount:t.effective_discount,tax_rate:input.tax_enabled?input.tax_rate:0,tax_amount:t.tax_amount,total:t.total,line_items:input.line_items});}
export async function deleteInvoice(invoiceId:string,_reason?:string):Promise<void>{const{data:{user}}=await getCurrentAuthUser();if(!user)throw new Error("Not authenticated");await nextApi.invoices.remove(workspace(),invoiceId);}
export async function markInvoiceStatus(invoiceId:string,status:"draft"|"sent"|"partial"|"paid"|"void"):Promise<void>{const{data:{user}}=await getCurrentAuthUser();if(!user)throw new Error("Not authenticated");const workspace_id=workspace();await nextApi.invoices.update(invoiceId,{workspace_id,status});if(status==="void"){const{error}=await supabase.from("invoice_lifecycle_events").insert({invoice_id:invoiceId,user_id:user.id,event_type:"voided",idempotency_key:`voided:${invoiceId}`,details:{source:"invoice_ui"}});if(error&&error.code!=="23505")throw error;}}
export async function sendManualInvoiceEmail(params:{invoiceId:string;recipientEmail?:string;subject?:string;message?:string;}):Promise<{recipient:string}>{const{data}=await nextApi.payments.action({action:"send_manual_invoice",workspace_id:workspace(),invoice_id:params.invoiceId,recipient_email:params.recipientEmail,subject:params.subject,message:params.message});return{recipient:(data as{recipient?:string}|null)?.recipient??""};}

const FLEET_INVOICE_RETIRED="Fleet invoicing is separated from Service Writer. Use the Fleet application for Fleet work-order billing.";
export async function recordFleetInvoicePayment(_params:{invoiceId:string;amount:number;note?:string;}):Promise<{status:string;amount_paid:number;balance_due:number}>{throw new Error(FLEET_INVOICE_RETIRED);}
export async function createInvoiceFromFleetWorkOrder(_workOrderId:string):Promise<string>{throw new Error(FLEET_INVOICE_RETIRED);}
export interface BulkFleetInvoicePreviewRow{work_order_id:string;order_number:string|null;status:string;fleet_client_id:string|null;invoice_id:string|null;line_count:number;order_total:number;}
export interface BulkFleetInvoicePreview{clientId:string;workOrderCount:number;lineCount:number;subtotal:number;rows:BulkFleetInvoicePreviewRow[];errors:string[];}
export interface BulkFleetInvoiceResult{invoice_id:string;invoice_number:string;work_order_count:number;line_item_count:number;subtotal:number;total:number;}
export interface FleetInvoiceOptions{taxEnabled?:boolean;taxRate?:number;processingFeeEnabled?:boolean;processingFeeType?:"percentage"|"fixed";processingFeeValue?:number;[key:string]:unknown;}
export async function previewFleetConsolidatedInvoice(_workOrderIds:string[]):Promise<BulkFleetInvoicePreview>{return{clientId:"",workOrderCount:0,lineCount:0,subtotal:0,rows:[],errors:[FLEET_INVOICE_RETIRED]};}
export async function createInvoiceFromFleetWorkOrders(_workOrderIds:string[],_options:FleetInvoiceOptions={}):Promise<BulkFleetInvoiceResult>{throw new Error(FLEET_INVOICE_RETIRED);}
