import { supabase } from "@/integrations/supabase/client";
import { nextApi } from "@/lib/nextApiClient";
import { getSelectedWorkspaceId } from "@/application/queries/workspaces.selection";
import { getCurrentAuthUser } from "@/lib/auth/current-user";

export interface ServiceRecordData{customerId?:string|null;vehicleId?:string|null;serviceDate:string;serviceType:string;description:string;partsUsed?:string|null;laborHours?:number|null;laborCost?:number|null;partsCost?:number|null;totalCost:number;status:'pending'|'in_progress'|'completed';notes?:string|null;technician?:string|null;taxRate?:number|null;taxAmount?:number|null;discountType?:string|null;discountAmount?:number|null;shopSupplies?:number|null;paymentStatus?:'unpaid'|'partial'|'paid'|null;paidAmount?:number|null;appointmentId?:string|null;}
export interface FilterPart{name:string;partNumber:string;}
export interface CreateServiceRecordResult{success:boolean;serviceId?:string;serviceNumber?:string;error?:string;}
export interface AppointmentToServiceData{appointmentId:string;technician?:string;additionalNotes?:string;laborHours?:number;shopSupplies?:number;mileage?:number;vin?:string;filterParts?:FilterPart[];oilQuartsUsed?:number;oilType?:string;}

export async function createServiceRecord(data:ServiceRecordData,_ownerUserId?:string):Promise<CreateServiceRecordResult>{const workspace_id=getSelectedWorkspaceId();if(!workspace_id)return{success:false,error:'Select a workspace before creating a service record.'};try{const response=await nextApi.serviceRecords.create({workspace_id,appointment_id:data.appointmentId||null,status:data.status==='pending'?'draft':data.status,work_performed:data.description,internal_notes:data.notes||null,oil_quarts_used:null,metadata:{customer_id:data.customerId||null,vehicle_id:data.vehicleId||null,service_date:data.serviceDate,service_type:data.serviceType,parts_used:data.partsUsed||null,labor_hours:data.laborHours||null,labor_cost:data.laborCost||null,parts_cost:data.partsCost||null,total_cost:data.totalCost,technician:data.technician||null,tax_rate:data.taxRate||null,tax_amount:data.taxAmount||null,discount_type:data.discountType||null,discount_amount:data.discountAmount||null,shop_supplies:data.shopSupplies||null,payment_status:data.paymentStatus||'unpaid',paid_amount:data.paidAmount||null}});const record=response.data as any;return{success:true,serviceId:record.id,serviceNumber:record.service_number};}catch(error){const err=error as Error;return{success:false,error:err.message||'Failed to create service record'};}}
function formatFilterPartsForDisplay(parts:FilterPart[]):string{return parts?.length?parts.map(f=>`${f.name}: ${f.partNumber}`).join(', '):'';}
async function buildVehicleSpecNotes(vehicle:{year:number;make:string;model:string}|null,bookedServiceNames:string[]):Promise<string>{if(!vehicle)return'';const{data:specs}=await supabase.from('vehicle_specifications').select('oil_capacity, oil_filter, air_filter, cabin_filter, fuel_filter, additional_specs').eq('year',vehicle.year).ilike('make',vehicle.make).ilike('model',vehicle.model).limit(1);if(!specs?.length)return'';const spec=specs[0];const add=spec.additional_specs as Record<string,string|null>|null;const names=bookedServiceNames.map(n=>n.toLowerCase());const has=(...k:string[])=>names.some(n=>k.some(x=>n.includes(x)));const lines:string[]=[];if(has('oil','lube','maintenance','full service','pm ')||!names.length){if(spec.oil_capacity)lines.push(`Oil Capacity: ${spec.oil_capacity} qt`);if(spec.oil_filter)lines.push(`Oil Filter: ${spec.oil_filter}`);const torque=add?.oil_plug_torque||add?.drain_plug_torque;if(torque)lines.push(`Drain Plug Torque: ${torque}`);}if(has('air filter','engine filter','air intake')&&spec.air_filter)lines.push(`Air Filter: ${spec.air_filter}`);if(has('cabin','cabin air','cabin filter','hvac')&&spec.cabin_filter)lines.push(`Cabin Air Filter: ${spec.cabin_filter}`);if(has('fuel filter','fuel system')&&spec.fuel_filter)lines.push(`Fuel Filter: ${spec.fuel_filter}`);return lines.length?`--- Vehicle Specs ---\n${lines.join('\n')}`:'';}

export async function createServiceRecordFromAppointment(data:AppointmentToServiceData):Promise<CreateServiceRecordResult>{
 const workspace_id=getSelectedWorkspaceId();if(!workspace_id)return{success:false,error:'Select a workspace before creating a service record.'};const{data:{user}}=await getCurrentAuthUser();if(!user)return{success:false,error:'Not authenticated'};
 try{const db=supabase as any;const[{data:appointment,error:appointmentError},{data:items}]=await Promise.all([
  db.from('appointments').select('id,workspace_id,customer_id,vehicle_id,status,starts_at,ends_at,notes,metadata,vehicle:vehicles(id,year,make,model,vin,mileage,metadata)').eq('id',data.appointmentId).eq('workspace_id',workspace_id).single(),
  db.from('appointment_items').select('service_catalog_id,description,quantity,unit_price,service_catalog(name)').eq('appointment_id',data.appointmentId).eq('workspace_id',workspace_id).order('sort_order'),
 ]);if(appointmentError||!appointment)throw new Error('Appointment not found');
 const itemRows=items??[];const serviceNames=itemRows.map((i:any)=>i.service_catalog?.name||i.description).filter(Boolean);const lineTotal=itemRows.reduce((sum:number,i:any)=>sum+Number(i.unit_price||0)*Number(i.quantity||1),0);const meta=appointment.metadata&&typeof appointment.metadata==='object'&&!Array.isArray(appointment.metadata)?appointment.metadata:{};const vehicleMeta=appointment.vehicle?.metadata&&typeof appointment.vehicle.metadata==='object'&&!Array.isArray(appointment.vehicle.metadata)?appointment.vehicle.metadata:{};
 const specNotes=await buildVehicleSpecNotes(appointment.vehicle?{year:appointment.vehicle.year,make:appointment.vehicle.make,model:appointment.vehicle.model}:null,serviceNames);const partsEntries:string[]=[];if(data.filterParts?.length)partsEntries.push(formatFilterPartsForDisplay(data.filterParts));if(data.oilQuartsUsed)partsEntries.push(`Oil: ${data.oilQuartsUsed} qt ${data.oilType?.trim()||vehicleMeta.oil_type||'Motor Oil'}`);const workPerformed=itemRows.length?itemRows.map((i:any)=>`${i.service_catalog?.name||i.description} (${i.quantity||1}x)`).join(', '):String(meta.title||'Completed service');const combined=[appointment.notes,data.additionalNotes,specNotes].filter(Boolean).join('\n---\n');
 if(appointment.vehicle_id&&(data.mileage||data.vin)){const update:any={};if(data.mileage)update.mileage=data.mileage;if(data.vin)update.vin=data.vin;await db.from('vehicles').update(update).eq('id',appointment.vehicle_id).eq('workspace_id',workspace_id);}
 const taxAmount=Number(meta.tax_amount||0);const subtotal=lineTotal||Number(meta.estimated_cost||0);const{data:record,error}=await db.from('service_records').insert({workspace_id,appointment_id:data.appointmentId,customer_id:appointment.customer_id,vehicle_id:appointment.vehicle_id,completed_by:user.id,status:'completed',work_performed:workPerformed,oil_quarts_used:data.oilQuartsUsed||null,internal_notes:combined||null,started_at:appointment.starts_at,completed_at:new Date().toISOString(),subtotal,tax_amount:taxAmount,discount_amount:0,total_amount:subtotal+taxAmount,currency_code:'USD',metadata:{technician_label:data.technician||null,labor_hours:data.laborHours||null,parts_used:partsEntries.length?partsEntries.join(', '):null,service_names:serviceNames}}).select('id').single();if(error)throw error;return{success:true,serviceId:record.id};
 }catch(error){const err=error as Error;return{success:false,error:err.message||'Failed to create service record'};}
}

export async function completeAppointmentWithServiceRecord(appointmentId:string,options?:{technician?:string;additionalNotes?:string;laborHours?:number;mileage?:number;vin?:string;filterParts?:FilterPart[];oilQuartsUsed?:number;oilType?:string;}):Promise<{success:boolean;serviceId?:string;error?:string}>{const workspace_id=getSelectedWorkspaceId();if(!workspace_id)return{success:false,error:'Select a workspace before completing a service record.'};try{const completion=await nextApi.appointments.complete(appointmentId,workspace_id);const appointment=completion.data as Record<string,unknown>|null;const service=await nextApi.serviceRecords.create({workspace_id,appointment_id:appointmentId,status:'completed',started_at:null,completed_at:new Date().toISOString(),work_performed:options?.additionalNotes??'Completed service',oil_quarts_used:options?.oilQuartsUsed??null,metadata:{technician:options?.technician??null,labor_hours:options?.laborHours??null,mileage:options?.mileage??null,vin:options?.vin??null,oil_type:options?.oilType?.trim()||null,filter_parts:options?.filterParts?.length?formatFilterPartsForDisplay(options.filterParts):null,appointment_completion:appointment}});return{success:true,serviceId:(service.data as any)?.id};}catch(error){const msg=(error as Error).message||'Failed to complete appointment';return{success:false,error:msg};}}
export async function updateServiceRecordStatus(serviceId:string,status:'pending'|'in_progress'|'completed'):Promise<{success:boolean;error?:string}>{const workspace_id=getSelectedWorkspaceId();if(!workspace_id)return{success:false,error:'Select a workspace before updating status.'};try{await nextApi.serviceRecords.update(serviceId,{workspace_id,status:status==='pending'?'draft':status});return{success:true};}catch(error){return{success:false,error:(error as Error).message};}}
export async function updateServicePaymentStatus(serviceId:string,paymentStatus:'unpaid'|'partial'|'paid',paidAmount?:number):Promise<{success:boolean;error?:string}>{const workspace_id=getSelectedWorkspaceId();if(!workspace_id)return{success:false,error:'Select a workspace before updating payment status.'};try{await nextApi.serviceRecords.update(serviceId,{workspace_id,payment_status:paymentStatus,paid_amount:paidAmount||null});return{success:true};}catch(error){return{success:false,error:(error as Error).message};}}
