import { z } from "zod";
import { errorResponse, json, requireWorkspaceMember } from "@/server/api";
import { sendLifecycleEmail } from "@/server/messaging/lifecycle-sender";
const bodySchema = z.object({ workspace_id: z.string().uuid(), recipient_email: z.string().email().optional(), subject: z.string().trim().max(200).optional(), message: z.string().trim().max(10000).optional() });
function object(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function text(value: unknown): string | null { return typeof value === "string" && value.trim() ? value.trim() : null; }
function escapeHtml(value: unknown): string { return String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }
function money(value: unknown, currency = "USD"): string { const amount = Number(value ?? 0); return Number.isFinite(amount) ? amount.toLocaleString("en-US", { style: "currency", currency }) : String(value ?? ""); }
function lineAmount(quantity: unknown, unitPrice: unknown): number { const qty = Number(quantity ?? 0); const rate = Number(unitPrice ?? 0); return Number.isFinite(qty) && Number.isFinite(rate) ? Number((qty * rate).toFixed(2)) : 0; }
export async function POST(request: Request, context: { params: Promise<{ id: string }> }) {
 try {
  const invoiceId = z.string().uuid().parse((await context.params).id); const body = bodySchema.parse(await request.json()); const { supabase } = await requireWorkspaceMember(body.workspace_id, ["owner", "admin", "manager", "service_advisor", "receptionist"], request);
  const [{ data: invoice, error: invoiceError }, { data: workspace, error: workspaceError }] = await Promise.all([supabase.from("invoices").select("id,workspace_id,invoice_number,status,subtotal,tax_total,total,amount_paid,due_at,metadata,invoice_lines(description,quantity,unit_price,sort_order),customers(id,first_name,last_name,email)").eq("workspace_id", body.workspace_id).eq("id", invoiceId).single(), supabase.from("workspaces").select("name,currency_code").eq("id", body.workspace_id).single()]);
  if (invoiceError || !invoice) throw invoiceError ?? new Error("Invoice not found"); if (workspaceError || !workspace) throw workspaceError ?? new Error("Workspace not found"); if (invoice.status === "void") return json({ error: { code: "invoice_void", message: "A void invoice cannot be sent." } }, { status: 409 });
  const metadata = object(invoice.metadata); const customer = Array.isArray(invoice.customers) ? invoice.customers[0] : invoice.customers; const recipient = body.recipient_email ?? text(metadata.contact_email) ?? customer?.email ?? null; if (!recipient) return json({ error: { code: "customer_email_required", message: "Recipient email is required to send this invoice." } }, { status: 422 });
  const customerName = [customer?.first_name, customer?.last_name].filter(Boolean).join(" ") || text(metadata.contact_name) || "Customer"; const currency = workspace.currency_code || "USD"; const total = Math.max(0, Number(invoice.total) || 0); const paid = Math.max(0, Number(invoice.amount_paid) || 0); const balance = Math.max(0, Number((total - paid).toFixed(2))); const isPaid = invoice.status === "paid" || balance < 0.01; const isPartial = !isPaid && paid > 0;
  const subject = body.subject?.trim() || (isPaid ? `Paid invoice ${invoice.invoice_number} from ${workspace.name}` : isPartial ? `Invoice ${invoice.invoice_number} — ${money(balance, currency)} remaining` : `Invoice ${invoice.invoice_number} from ${workspace.name} — ${money(total, currency)}`);
  const intro = body.message?.trim() || (isPaid ? `Hi ${customerName},\n\nThis invoice is paid in full. Here is your final invoice for your records.\n\nThanks,\n${workspace.name}` : isPartial ? `Hi ${customerName},\n\nWe received ${money(paid, currency)} toward invoice ${invoice.invoice_number}. The remaining balance is ${money(balance, currency)}.\n\nThanks,\n${workspace.name}` : `Hi ${customerName},\n\nPlease find invoice ${invoice.invoice_number} below. Let us know if you have any questions.\n\nThanks,\n${workspace.name}`);
  const lines = [...(invoice.invoice_lines ?? [])].sort((a, b) => Number(a.sort_order ?? 0) - Number(b.sort_order ?? 0)); const lineText = lines.length ? lines.map((line) => `${line.description} — ${line.quantity} × ${money(line.unit_price, currency)} = ${money(lineAmount(line.quantity, line.unit_price), currency)}`).join("\n") : "No line items"; const paymentSummary = isPaid ? `Paid: ${money(paid, currency)}\nBalance due: ${money(0, currency)}\nStatus: PAID IN FULL` : isPartial ? `Paid: ${money(paid, currency)}\nBalance due: ${money(balance, currency)}` : `Balance due: ${money(balance, currency)}`; const dueText = !isPaid && invoice.due_at ? `\nDue: ${new Date(invoice.due_at).toLocaleDateString("en-US")}` : ""; const plainText = `${intro}\n\nInvoice ${invoice.invoice_number}\n${lineText}\n\nSubtotal: ${money(invoice.subtotal, currency)}\nTax: ${money(invoice.tax_total, currency)}\nTotal: ${money(total, currency)}\n${paymentSummary}${dueText}`;
  const rowsHtml = lines.length ? lines.map((line) => `<tr><td>${escapeHtml(line.description)}</td><td>${escapeHtml(line.quantity)}</td><td>${escapeHtml(money(line.unit_price, currency))}</td><td>${escapeHtml(money(lineAmount(line.quantity, line.unit_price), currency))}</td></tr>`).join("") : `<tr><td colspan="4">No line items</td></tr>`; const html = `<!doctype html><html><body><h1>Invoice ${escapeHtml(invoice.invoice_number)}</h1><div>${escapeHtml(intro).replaceAll("\n", "<br>")}</div><table><tbody>${rowsHtml}</tbody></table><p>Total: ${escapeHtml(money(total, currency))}<br>Paid: ${escapeHtml(money(paid, currency))}<br>Balance due: ${escapeHtml(money(isPaid ? 0 : balance, currency))}</p></body></html>`;
  const sent = await sendLifecycleEmail({ workspaceId: body.workspace_id, recipientEmail: recipient, customerId: customer?.id ?? null, templateKey: isPaid ? "invoice_and_payment_sequence.payment_received" : "invoice_and_payment_sequence.invoice_created", idempotencyKey: `invoice-send:${invoice.id}:${Date.now()}:${crypto.randomUUID()}`, variables: { "business.name": workspace.name, "invoice.number": invoice.invoice_number, "invoice.total": money(total, currency), "invoice.balance_due": money(balance, currency), "invoice.status": String(invoice.status), "customer.full_name": customerName }, metadata: { invoiceId: invoice.id, source: "invoice_send_dialog", invoiceStatus: String(invoice.status), amountPaid: paid.toFixed(2), balanceDue: balance.toFixed(2) }, renderedOverride: { subject, text: plainText, html, purpose: "transactional", fromName: workspace.name } });
  if (sent.status === "suppressed") return json({ data: { recipient, delivery_status: "suppressed", provider: sent.providerName, provider_message_id: sent.providerMessageId, invoice_status: invoice.status, amount_paid: paid, balance_due: balance } });
  const sentAt = new Date().toISOString(); const nextStatus = invoice.status === "draft" ? "issued" : invoice.status; const nextMetadata = { ...metadata, last_sent_at: sentAt, last_sent_to: recipient.toLowerCase(), last_sent_provider: sent.providerName, last_sent_provider_message_id: sent.providerMessageId }; const invoicePatch: Record<string, unknown> = { status: nextStatus, metadata: nextMetadata, updated_at: sentAt }; if (invoice.status === "draft") invoicePatch.issued_at = sentAt;
  const { error: invoiceUpdateError } = await (supabase.from("invoices") as any).update(invoicePatch).eq("workspace_id", body.workspace_id).eq("id", invoice.id); if (invoiceUpdateError) console.error("[invoice-send] email sent but invoice delivery state update failed", invoiceUpdateError);
  return json({ data: { recipient, delivery_status: sent.status, provider: sent.providerName, provider_message_id: sent.providerMessageId, invoice_status: nextStatus, amount_paid: paid, balance_due: balance } });
 } catch (error) { return errorResponse(error); }
}
