import { supabase } from '@/integrations/supabase/client';
import { resolveCurrentWorkspace } from '@/application/queries/settings.query';
import { startOfDay,endOfDay,startOfWeek,startOfMonth,startOfYear,addDays,format } from 'date-fns';

export interface CockpitAppointment{id:string;title:string;scheduled_date:string;scheduled_time:string|null;status:string;guest_name:string|null;estimated_cost:number|null;}
export interface CockpitJobInProgress{id:string;service_type:string;customer_name:string;vehicle:string|null;started_at:string|null;}
export interface CockpitServiceTypeRev{type:string;revenue:number;count:number;}
export type FleetPanelStatus='ready'|'empty'|'error';
export interface FleetPanelState{status:FleetPanelStatus;message?:string;}
export interface FleetOperationsKpis{fleetCustomers:number;techniciansWorking:number;vehiclesScheduledToday:number;overduePms:number;fleetHealthScore:number;scheduledRevenueToday:number;completedRevenueToday:number;pendingApprovalRevenue:number;}
export interface FleetScheduleItem{id:string;time:string|null;customerName:string;vehicleCount:number;assignedTechnician:string|null;route:string|null;etaMinutes:number|null;status:string;}
export interface FleetAttentionGroup{customerId:string;customerName:string;overduePm:number;dueThisWeek:number;upcomingPm:number;waitingApproval:number;}
export interface FleetPipelineStage{stage:'New'|'Assigned'|'Traveling'|'On Site'|'Waiting Approval'|'Completed'|'Invoiced';count:number;}
export interface FleetTechnicianStatus{id:string;name:string;status:'Driving'|'On Site'|'Lunch'|'Available'|'Offline';currentWorkOrder:string|null;etaMinutes:number|null;currentLocation:{lat:number;lng:number}|null;}
export interface FleetCustomerHealth{customerId:string;customerName:string;pmCompliance:number;outstandingAr:number;lastVisit:string|null;lifetimeRevenue:number;monthlyAverageRevenue:number;}
export interface FleetVehiclePmCompliance{vehicleId:string;customerId:string;customerName:string;vehicleLabel:string;pmCompliance:number;dueStatus:'overdue'|'due_this_week'|'upcoming'|'current'|'unknown';lastServiceDate:string|null;nextServiceDate:string|null;mileage:number|null;}
export interface FleetPmQueueItem{vehicleId:string;customerId:string;customerName:string;vehicleLabel:string;nextServiceDate:string|null;daysUntilDue:number|null;complianceScore:number;recommendation:string;approvalUrl:string;estimateUrl:string;}
export interface FleetPmQueues{overdue:FleetPmQueueItem[];dueThisWeek:FleetPmQueueItem[];upcoming:FleetPmQueueItem[];thirtyDays:FleetPmQueueItem[];}
export interface FleetArAgingBucket{label:'Current'|'1-30'|'31-60'|'61-90'|'90+';amount:number;count:number;}
export interface FleetInvoiceQueueItem{workOrderId:string;customerId:string;customerName:string;invoiceStatus:string;amount:number;daysOutstanding:number;invoiceUrl:string;workOrderUrl:string;}
export interface FleetRevenueCommand{forecast30Days:number;approvalDollars:number;outstandingAr:number;arAging:FleetArAgingBucket[];invoiceQueue:FleetInvoiceQueueItem[];}
export interface FleetInventorySummary{lowInventory:number;oilGrades:number;filters:number;drainPlugs:number;shopSupplies:number;}
export interface FleetInventoryRequirement{category:'Oil Grades'|'Filters'|'Drain Plugs'|'Shop Supplies';required:number;available:number;shortage:number;}
export interface FleetRouteReadiness{route:string;workOrderId:string;customerName:string;vehicleCount:number;ready:boolean;requirements:FleetInventoryRequirement[];receiveInventoryUrl:string;replenishUrl:string;}
export interface FleetLowStockReplenishment{category:string;shortage:number;receiveInventoryUrl:string;replenishUrl:string;}
export interface FleetInventoryReadiness{routes:FleetRouteReadiness[];lowStockReplenishment:FleetLowStockReplenishment[];}
export interface FleetMapPoint{id:string;label:string;type:'technician'|'customer'|'stop';status:string|null;route:string|null;etaMinutes:number|null;location:{lat:number;lng:number}|null;}
export interface FleetLiveRouteAction{workOrderId:string;route:string;customerName:string;assignedTechnician:string|null;etaMinutes:number|null;reassignUrl:string;availabilityUrl:string;}
export interface FleetOperationsDashboard{kpis:FleetOperationsKpis;schedule:FleetScheduleItem[];attention:FleetAttentionGroup[];pipeline:FleetPipelineStage[];technicians:FleetTechnicianStatus[];pmForecast:{today:number;thisWeek:number;nextWeek:number;thirtyDays:number};pmQueues:FleetPmQueues;vehicleCompliance:FleetVehiclePmCompliance[];revenueCommand:FleetRevenueCommand;customerHealth:FleetCustomerHealth[];inventory:FleetInventorySummary;inventoryReadiness:FleetInventoryReadiness;mapPoints:FleetMapPoint[];liveRouteActions:FleetLiveRouteAction[];panels:Record<'schedule'|'attention'|'pipeline'|'technicians'|'revenue'|'pmForecast'|'customerHealth'|'inventory'|'map',FleetPanelState>;}
export interface CockpitData{revenueToday:number;revenueWeek:number;revenueMonth:number;revenueYTD:number;revenueTodayPrev:number;revenueMonthPrev:number;outstandingAR:number;jobsInProgress:number;jobsCompletedToday:number;appointmentsToday:number;unpaidInvoices:number;todaysAppointments:CockpitAppointment[];upcomingNext7:CockpitAppointment[];jobsInProgressList:CockpitJobInProgress[];serviceTypeRevenueMTD:CockpitServiceTypeRev[];fleetOperations:FleetOperationsDashboard;}
function obj(value:unknown):Record<string,unknown>{return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};}
function customerName(c:any){return c?.company_name||[c?.first_name,c?.last_name].filter(Boolean).join(' ')||'Unknown Customer';}
function toCockpitAppointment(row:any):CockpitAppointment{const starts=row.starts_at?new Date(row.starts_at):null;const meta=obj(row.metadata);return{id:row.id,title:String(meta.title||row.notes||'Appointment'),scheduled_date:starts?starts.toISOString().slice(0,10):'',scheduled_time:starts?starts.toISOString().slice(11,16):null,status:String(row.status||'pending'),guest_name:typeof meta.guest_name==='string'?meta.guest_name:null,estimated_cost:Number(meta.estimated_cost)||null};}
function emptyFleetOperations():FleetOperationsDashboard{const separated:FleetPanelState={status:'empty',message:'Fleet operations are managed in the Fleet application.'};return{kpis:{fleetCustomers:0,techniciansWorking:0,vehiclesScheduledToday:0,overduePms:0,fleetHealthScore:100,scheduledRevenueToday:0,completedRevenueToday:0,pendingApprovalRevenue:0},schedule:[],attention:[],pipeline:[{stage:'New',count:0},{stage:'Assigned',count:0},{stage:'Traveling',count:0},{stage:'On Site',count:0},{stage:'Waiting Approval',count:0},{stage:'Completed',count:0},{stage:'Invoiced',count:0}],technicians:[],pmForecast:{today:0,thisWeek:0,nextWeek:0,thirtyDays:0},pmQueues:{overdue:[],dueThisWeek:[],upcoming:[],thirtyDays:[]},vehicleCompliance:[],revenueCommand:{forecast30Days:0,approvalDollars:0,outstandingAr:0,arAging:[{label:'Current',amount:0,count:0},{label:'1-30',amount:0,count:0},{label:'31-60',amount:0,count:0},{label:'61-90',amount:0,count:0},{label:'90+',amount:0,count:0}],invoiceQueue:[]},customerHealth:[],inventory:{lowInventory:0,oilGrades:0,filters:0,drainPlugs:0,shopSupplies:0},inventoryReadiness:{routes:[],lowStockReplenishment:[]},mapPoints:[],liveRouteActions:[],panels:{schedule:separated,attention:separated,pipeline:separated,technicians:separated,revenue:separated,pmForecast:separated,customerHealth:separated,inventory:separated,map:separated}};}
function paidStatus(status:unknown){return ['paid','succeeded','completed','captured'].includes(String(status||'').toLowerCase());}
export async function fetchDashboardCockpit():Promise<CockpitData|null>{
 const context=await resolveCurrentWorkspace();if(!context)return null;const db=supabase as any;const now=new Date();
 const ranges={today:[startOfDay(now),endOfDay(now)],yesterday:[startOfDay(addDays(now,-1)),endOfDay(addDays(now,-1))],week:[startOfWeek(now,{weekStartsOn:1}),endOfDay(now)],month:[startOfMonth(now),endOfDay(now)],year:[startOfYear(now),endOfDay(now)]} as const;
 const prevMonthStart=new Date(now.getFullYear(),now.getMonth()-1,1);const prevMonthEnd=new Date(now.getFullYear(),now.getMonth()-1,Math.min(now.getDate(),new Date(now.getFullYear(),now.getMonth(),0).getDate()),23,59,59,999);const next7=addDays(now,7);
 const [paymentsRes,invoicesRes,todayRes,upcomingRes,recordsRes,itemsRes]=await Promise.all([
  db.from('payments').select('amount,status,paid_at,created_at').eq('workspace_id',context.workspaceId),db.from('invoices').select('id,status,total,amount_paid,due_at,created_at').eq('workspace_id',context.workspaceId),db.from('appointments').select('id,status,starts_at,notes,metadata').eq('workspace_id',context.workspaceId).gte('starts_at',ranges.today[0].toISOString()).lte('starts_at',ranges.today[1].toISOString()).order('starts_at'),db.from('appointments').select('id,status,starts_at,notes,metadata').eq('workspace_id',context.workspaceId).gt('starts_at',ranges.today[1].toISOString()).lte('starts_at',next7.toISOString()).order('starts_at').limit(10),db.from('service_records').select('id,appointment_id,customer_id,vehicle_id,status,work_performed,started_at,completed_at,total_amount,metadata,customers(first_name,last_name,company_name),vehicles(year,make,model)').eq('workspace_id',context.workspaceId),db.from('appointment_items').select('appointment_id,description,quantity,unit_price,service_catalog(name)').eq('workspace_id',context.workspaceId),]);
 const firstError=[paymentsRes,invoicesRes,todayRes,upcomingRes,recordsRes,itemsRes].find(r=>r.error)?.error;if(firstError)throw firstError;
 const payments=(paymentsRes.data??[]).filter((p:any)=>paidStatus(p.status));const sumRange=(start:Date,end:Date)=>payments.reduce((sum:number,p:any)=>{const at=new Date(p.paid_at||p.created_at);return at>=start&&at<=end?sum+Number(p.amount||0):sum;},0);
 const invoices=invoicesRes.data??[];const outstandingAR=invoices.reduce((sum:number,i:any)=>sum+Math.max(0,Number(i.total||0)-Number(i.amount_paid||0)),0);const unpaidInvoices=invoices.filter((i:any)=>Math.max(0,Number(i.total||0)-Number(i.amount_paid||0))>0&&!['void','paid'].includes(String(i.status))).length;
 const records=recordsRes.data??[];const todayKey=format(now,'yyyy-MM-dd');const monthKey=format(startOfMonth(now),'yyyy-MM-dd');const jobsInProgressRows=records.filter((r:any)=>String(r.status)==='in_progress');const completedToday=records.filter((r:any)=>String(r.status)==='completed'&&String(r.completed_at||'').slice(0,10)===todayKey);const completedMonth=records.filter((r:any)=>String(r.status)==='completed'&&String(r.completed_at||'').slice(0,10)>=monthKey);
 const itemByAppt=new Map<string,string>();for(const item of itemsRes.data??[]){if(!itemByAppt.has(item.appointment_id))itemByAppt.set(item.appointment_id,item.service_catalog?.name||item.description||'Service');}
 const serviceRevenue=new Map<string,{revenue:number;count:number}>();for(const r of completedMonth){const meta=obj(r.metadata);const type=itemByAppt.get(r.appointment_id)||String(meta.service_name||r.work_performed||'Service');const bucket=serviceRevenue.get(type)||{revenue:0,count:0};bucket.revenue+=Number(r.total_amount||0);bucket.count+=1;serviceRevenue.set(type,bucket);}
 return{revenueToday:sumRange(...ranges.today),revenueWeek:sumRange(...ranges.week),revenueMonth:sumRange(...ranges.month),revenueYTD:sumRange(...ranges.year),revenueTodayPrev:sumRange(...ranges.yesterday),revenueMonthPrev:sumRange(prevMonthStart,prevMonthEnd),outstandingAR,jobsInProgress:jobsInProgressRows.length,jobsCompletedToday:completedToday.length,appointmentsToday:(todayRes.data??[]).length,unpaidInvoices,todaysAppointments:(todayRes.data??[]).map(toCockpitAppointment),upcomingNext7:(upcomingRes.data??[]).map(toCockpitAppointment),jobsInProgressList:jobsInProgressRows.map((r:any)=>({id:r.id,service_type:itemByAppt.get(r.appointment_id)||r.work_performed||'Service',customer_name:customerName(r.customers),vehicle:r.vehicles?`${r.vehicles.year??''} ${r.vehicles.make??''} ${r.vehicles.model??''}`.trim():null,started_at:r.started_at||null})),serviceTypeRevenueMTD:Array.from(serviceRevenue.entries()).map(([type,v])=>({type,...v})).sort((a,b)=>b.revenue-a.revenue),fleetOperations:emptyFleetOperations()};
}
