import { supabase } from "@/integrations/supabase/client";
import { type DynamicReportConfig } from "@/types/reporting";
import { resolveCurrentWorkspace } from "@/application/queries/settings.query";

export interface UnifiedReportingRecord { appointment_id:string|null;customer_id:string|null;city:string;postal_code:string;state:string;make:string;model:string;year:number;fuel_type:string;oil_type:string;oil_capacity:number;scheduled_time_slot:string;scheduled_date:string;client_type:string;status:string;service_type:string;origin_source:string;technician_name:string;van_name:string;total_billed:number;net_collected:number;balance_due:number;quarts_used:number;job_count:number;duration_minutes:number;actual_minutes:number;travel_minutes:number;latitude?:number;longitude?:number; }
export interface ReportingRecordsFilter { from?:Date;to?:Date;includeLegacy?:boolean; }
export function timeSlotForClock(clock:string|null|undefined):string{if(!clock)return"Unknown";const hour=Number.parseInt(String(clock).split(":")[0],10);if(!Number.isFinite(hour))return"Unknown";if(hour<12)return"Morning";if(hour<17)return"Afternoon";if(hour<21)return"Evening";return"Night";}
export function zipFromAddress(address:string|null|undefined):string|null{const match=(address||"").match(/\b(\d{5})(?:-\d{4})?\b/);return match?match[1]:null;}
export function cityFromAddress(address:string|null|undefined):string|null{const parts=(address||"").split(",").map(p=>p.trim()).filter(Boolean);if(parts.length<2)return null;const candidate=parts[parts.length-2];if(/^[A-Z]{2}\s*\d{5}/.test(candidate))return parts.length>=3?parts[parts.length-3]:null;return candidate.replace(/\s*\d{5}(-\d{4})?$/,"").trim()||null;}
export function stateFromAddress(address:string|null|undefined):string|null{const match=(address||"").match(/\b([A-Z]{2})\s+\d{5}(?:-\d{4})?\b/);return match?match[1]:null;}

function recordName(customer:any){return customer?.company_name||[customer?.first_name,customer?.last_name].filter(Boolean).join(" ")||"Unknown";}
function metadataObject(value:unknown):Record<string,unknown>{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}

export async function fetchRawReportingRecords(filter:ReportingRecordsFilter={}):Promise<UnifiedReportingRecord[]>{
 const context=await resolveCurrentWorkspace();if(!context)return[];const db=supabase as any;
 let apptQuery=db.from("appointments").select("id,customer_id,vehicle_id,assigned_user_id,status,starts_at,ends_at,source,notes,metadata,customers(first_name,last_name,company_name,address_line1,city,region,postal_code,metadata),vehicles(make,model,year,metadata)").eq("workspace_id",context.workspaceId).limit(5000);
 let workQuery=db.from("work_orders").select("id,customer_id,vehicle_id,status,opened_at,completed_at,complaint,diagnosis,metadata,customers(first_name,last_name,company_name,address_line1,city,region,postal_code,metadata),vehicles(make,model,year,metadata)").eq("workspace_id",context.workspaceId).limit(5000);
 if(filter.from){const iso=filter.from.toISOString();apptQuery=apptQuery.gte("starts_at",iso);workQuery=workQuery.gte("opened_at",iso);}if(filter.to){const iso=filter.to.toISOString();apptQuery=apptQuery.lte("starts_at",iso);workQuery=workQuery.lte("opened_at",iso);}
 const [apptRes,workRes,serviceRes,invoiceRes,paymentRes,memberRes]=await Promise.all([
  apptQuery,workQuery,
  db.from("service_records").select("id,appointment_id,work_order_id,total_amount,oil_quarts_used,completed_at,started_at,work_performed,metadata").eq("workspace_id",context.workspaceId),
  db.from("invoices").select("id,work_order_id,total,amount_paid,status,metadata").eq("workspace_id",context.workspaceId),
  db.from("payments").select("invoice_id,amount,status,paid_at,metadata").eq("workspace_id",context.workspaceId),
  db.from("workspace_members").select("user_id,profiles!workspace_members_user_id_fkey(display_name)").eq("workspace_id",context.workspaceId).eq("is_active",true),
 ]);
 const firstError=[apptRes,workRes,serviceRes,invoiceRes,paymentRes,memberRes].find(r=>r.error)?.error;if(firstError)throw firstError;
 const serviceByAppt=new Map<string,any>();const serviceByWork=new Map<string,any>();for(const r of serviceRes.data??[]){if(r.appointment_id)serviceByAppt.set(r.appointment_id,r);if(r.work_order_id)serviceByWork.set(r.work_order_id,r);}
 const invoicesByWork=new Map<string,any>();for(const i of invoiceRes.data??[])if(i.work_order_id)invoicesByWork.set(i.work_order_id,i);
 const paidByInvoice=new Map<string,number>();for(const p of paymentRes.data??[]){if(!p.invoice_id)continue;if(["failed","cancelled","refunded"].includes(String(p.status)))continue;paidByInvoice.set(p.invoice_id,(paidByInvoice.get(p.invoice_id)||0)+Number(p.amount||0));}
 const names=new Map<string,string>((memberRes.data??[]).map((m:any)=>[m.user_id,m.profiles?.display_name||"Staff"]));const records:UnifiedReportingRecord[]=[];
 for(const appt of apptRes.data??[]){const meta=metadataObject(appt.metadata);if(!filter.includeLegacy&&meta.data_origin==="legacy_import")continue;const vm=metadataObject(appt.vehicles?.metadata);const service=serviceByAppt.get(appt.id);const sm=metadataObject(service?.metadata);const starts=appt.starts_at?new Date(appt.starts_at):null;const ends=appt.ends_at?new Date(appt.ends_at):null;const address=String(meta.location_address||appt.customers?.address_line1||"");const billed=Number(service?.total_amount??meta.estimated_cost??0);const collected=Number(sm.amount_paid??0);const duration=starts&&ends?Math.max(0,Math.round((ends.getTime()-starts.getTime())/60000)):Number(meta.duration_minutes||0);records.push({appointment_id:appt.id,customer_id:appt.customer_id??null,city:appt.customers?.city||cityFromAddress(address)||"Unknown",postal_code:appt.customers?.postal_code||zipFromAddress(address)||"Unknown",state:appt.customers?.region||stateFromAddress(address)||"Unknown",make:appt.vehicles?.make||"Unknown",model:appt.vehicles?.model||"Unknown",year:Number(appt.vehicles?.year)||0,fuel_type:String(vm.fuel_type||"Unknown"),oil_type:String(vm.oil_type||sm.oil_type||"Unknown"),oil_capacity:Number(vm.oil_capacity||0),scheduled_time_slot:starts?timeSlotForClock(starts.toISOString().slice(11,16)):"Unknown",scheduled_date:starts?starts.toISOString().slice(0,10):"",client_type:"Retail",status:String(appt.status||"Unknown"),service_type:String(sm.service_name||meta.title||service?.work_performed||"Unspecified"),origin_source:String(appt.source||"direct"),technician_name:appt.assigned_user_id?names.get(appt.assigned_user_id)||"Assigned":"Unassigned",van_name:"Unassigned",total_billed:billed,net_collected:collected,balance_due:Math.max(0,billed-collected),quarts_used:Number(service?.oil_quarts_used||0),job_count:1,duration_minutes:duration,actual_minutes:service?.started_at&&service?.completed_at?Math.max(0,Math.round((new Date(service.completed_at).getTime()-new Date(service.started_at).getTime())/60000)):0,travel_minutes:Number(meta.travel_minutes||0)});}
 for(const wo of workRes.data??[]){const meta=metadataObject(wo.metadata);const vm=metadataObject(wo.vehicles?.metadata);const service=serviceByWork.get(wo.id);const invoice=invoicesByWork.get(wo.id);const paid=invoice?Math.max(Number(invoice.amount_paid||0),paidByInvoice.get(invoice.id)||0):0;const total=Number(invoice?.total??service?.total_amount??0);const opened=wo.opened_at?new Date(wo.opened_at):null;const closed=wo.completed_at?new Date(wo.completed_at):null;records.push({appointment_id:null,customer_id:wo.customer_id??null,city:wo.customers?.city||"Unknown",postal_code:wo.customers?.postal_code||"Unknown",state:wo.customers?.region||"Unknown",make:wo.vehicles?.make||"Unknown",model:wo.vehicles?.model||"Unknown",year:Number(wo.vehicles?.year)||0,fuel_type:String(vm.fuel_type||"Unknown"),oil_type:String(vm.oil_type||"Unknown"),oil_capacity:Number(vm.oil_capacity||0),scheduled_time_slot:opened?timeSlotForClock(opened.toISOString().slice(11,16)):"Unknown",scheduled_date:opened?opened.toISOString().slice(0,10):"",client_type:"Fleet",status:String(wo.status||"Unknown"),service_type:String(meta.requested_service||service?.work_performed||wo.complaint||"Work order"),origin_source:"fleet",technician_name:"Unassigned",van_name:"Unassigned",total_billed:total,net_collected:paid,balance_due:Math.max(0,total-paid),quarts_used:Number(service?.oil_quarts_used||0),job_count:1,duration_minutes:opened&&closed?Math.max(0,Math.round((closed.getTime()-opened.getTime())/60000)):0,actual_minutes:service?.started_at&&service?.completed_at?Math.max(0,Math.round((new Date(service.completed_at).getTime()-new Date(service.started_at).getTime())/60000)):0,travel_minutes:0});}
 return records;
}

export function pivotDataset(records:UnifiedReportingRecord[],config:DynamicReportConfig){const filtered=records.filter(record=>config.filters.every(filter=>{const val=record[filter.field as keyof UnifiedReportingRecord];if(val===undefined)return true;switch(filter.operator){case'eq':return String(val).toLowerCase()===String(filter.value).toLowerCase();case'neq':return String(val).toLowerCase()!==String(filter.value).toLowerCase();case'gt':return Number(val)>Number(filter.value);case'lt':return Number(val)<Number(filter.value);case'contains':return String(val).toLowerCase().includes(String(filter.value).toLowerCase());case'between':return Array.isArray(filter.value)?Number(val)>=Number(filter.value[0])&&Number(val)<=Number(filter.value[1]):true;default:return true;}}));const pivotData:Record<string,Record<string,Record<string,number>>>={};const rowSet=new Set<string>();const colSet=new Set<string>();const totals:Record<string,number>={};filtered.forEach(record=>{const rowKey=config.rows.length?config.rows.map(r=>String(record[r as keyof UnifiedReportingRecord]??"Unknown")).join(" / "):"Grand Total";const colKey=config.columns.length?config.columns.map(c=>String(record[c as keyof UnifiedReportingRecord]??"Unknown")).join(" / "):"Metric Value";rowSet.add(rowKey);colSet.add(colKey);pivotData[rowKey]??={};pivotData[rowKey][colKey]??={};config.values.forEach(v=>{const m=v.field;const value=Number(record[m as keyof UnifiedReportingRecord])||0;pivotData[rowKey][colKey][m]=(pivotData[rowKey][colKey][m]||0)+value;totals[m]=(totals[m]||0)+value;});});rowSet.forEach(r=>colSet.forEach(c=>{if(pivotData[r]?.[c])config.values.forEach(v=>{if(v.aggregation==='avg')pivotData[r][c][v.field]/=pivotData[r][c].job_count||1;});}));return{pivotData,allRows:Array.from(rowSet).sort(),allCols:Array.from(colSet).sort(),totals};}
