/** Fleet OS dashboard compatibility surface. Fleet OS is a separate product. */
export interface FleetOpsKpis{todayJobs:number;todayRevenue:number;vehiclesScheduledToday:number;fleetCustomers:number;techniciansWorking:number;overduePms:number;outstandingInvoices:number;fleetHealth:number;}
export interface FleetOpsScheduleItem{id:string;time:string|null;clientName:string;vehicleCount:number;technicianName:string|null;status:string;total:number;locationName:string|null;eta:string|null;}
export interface FleetOpsAttentionClient{fleetClientId:string;clientName:string;overdue:number;dueThisWeek:number;upcoming:number;awaitingApproval:number;}
export interface FleetOpsPipeline{new:number;assigned:number;traveling:number;onSite:number;waitingApproval:number;completed:number;invoiced:number;}
export interface FleetOpsTechnicianRow{id:string;name:string;status:string;currentLocation:{lat:number;lng:number}|null;currentJob:{id:string;clientName:string|null;scheduledTime:string|null}|null;clockedIn:boolean;}
export interface FleetOpsRevenue{scheduledToday:number;completedToday:number;pendingApproval:number;outstanding:number;}
export interface FleetOpsForecast{today:number;thisWeek:number;nextWeek:number;thirtyDays:number;}
export interface FleetOpsHealthCard{fleetClientId:string;clientName:string;vehicleCount:number;pmCompliance:number;outstandingAr:number;lastVisit:string|null;lifetimeRevenue:number;monthlyAverage:number;}
export interface FleetOpsInventoryRow{id:string;name:string;category:string|null;quantity:number;threshold:number;unit:string;}
export interface FleetOpsInventory{oil:FleetOpsInventoryRow[];filters:FleetOpsInventoryRow[];drainPlugs:FleetOpsInventoryRow[];supplies:FleetOpsInventoryRow[];totalLow:number;}
export interface FleetOpsDashboard{kpis:FleetOpsKpis;todaySchedule:FleetOpsScheduleItem[];attention:FleetOpsAttentionClient[];pipeline:FleetOpsPipeline;technicians:FleetOpsTechnicianRow[];revenue:FleetOpsRevenue;forecast:FleetOpsForecast;health:FleetOpsHealthCard[];inventory:FleetOpsInventory;}
export async function fetchFleetOpsDashboard(_userId:string):Promise<FleetOpsDashboard>{return{kpis:{todayJobs:0,todayRevenue:0,vehiclesScheduledToday:0,fleetCustomers:0,techniciansWorking:0,overduePms:0,outstandingInvoices:0,fleetHealth:100},todaySchedule:[],attention:[],pipeline:{new:0,assigned:0,traveling:0,onSite:0,waitingApproval:0,completed:0,invoiced:0},technicians:[],revenue:{scheduledToday:0,completedToday:0,pendingApproval:0,outstanding:0},forecast:{today:0,thisWeek:0,nextWeek:0,thirtyDays:0},health:[],inventory:{oil:[],filters:[],drainPlugs:[],supplies:[],totalLow:0}};}
