/** Fleet Check-In Query - canonical work order reads. */
import { supabase } from "@/integrations/supabase/client";
import { resolveCurrentWorkspace } from "@/application/queries/settings.query";
export interface FleetCheckInWorkOrder{id:string;order_number:string;service_type:string;description:string|null;priority:string;status:string;scheduled_date:string;scheduled_time:string|null;sla_deadline:string|null;fleet_clients:{company_name:string}|null;fleet_vehicles:{year:number;make:string;model:string;unit_number:string|null;license_plate:string|null}|null;fleet_locations:{name:string;address:string|null;city:string|null;state:string|null}|null;}
export interface FleetCheckInRecord{id:string;fleet_work_order_id:string;checkin_type:string;lat:number|null;lng:number|null;accuracy_meters:number|null;notes:string|null;created_at:string;}
function mapOrder(row:any):FleetCheckInWorkOrder{const meta=row.metadata&&typeof row.metadata==="object"&&!Array.isArray(row.metadata)?row.metadata:{};const opened=row.opened_at?new Date(row.opened_at):null;return{id:row.id,order_number:String(row.number??row.id.slice(0,8)),service_type:String(meta.requested_service||row.complaint||"Work order"),description:row.complaint||null,priority:String(row.priority||"normal"),status:String(row.status||"open"),scheduled_date:opened?opened.toISOString().slice(0,10):"",scheduled_time:opened?opened.toISOString().slice(11,16):null,sla_deadline:typeof meta.sla_deadline==="string"?meta.sla_deadline:null,fleet_clients:null,fleet_vehicles:row.vehicles?{year:Number(row.vehicles.year)||0,make:row.vehicles.make||"",model:row.vehicles.model||"",unit_number:typeof row.vehicles.metadata?.unit_number==="string"?row.vehicles.metadata.unit_number:null,license_plate:row.vehicles.license_plate??null}:null,fleet_locations:null};}
async function orders(){const context=await resolveCurrentWorkspace();if(!context)return[];const{data,error}=await(supabase as any).from("work_orders").select("id,number,complaint,priority,status,opened_at,metadata,vehicles(year,make,model,license_plate,metadata)").eq("workspace_id",context.workspaceId).in("status",["open","scheduled","in_progress","awaiting_parts","awaiting_approval"]).order("opened_at",{ascending:true});if(error)throw error;return(data??[]).map(mapOrder);}
export async function fetchTodayWorkOrders(_userId:string):Promise<{workOrders:FleetCheckInWorkOrder[];checkins:Record<string,FleetCheckInRecord[]>}>{const workOrders=await orders();const grouped:Record<string,FleetCheckInRecord[]>={};if(workOrders.length){const ids=workOrders.map(o=>o.id);const{data}=await(supabase as any).from("fleet_checkins").select("*").in("fleet_work_order_id",ids).order("created_at",{ascending:false});for(const ci of data??[]){(grouped[ci.fleet_work_order_id]??=[]).push(ci as FleetCheckInRecord);}}return{workOrders,checkins:grouped};}
export async function refreshWorkOrders(_userId:string):Promise<FleetCheckInWorkOrder[]>{return orders();}
export async function refreshCheckins(workOrderId:string,_userId:string):Promise<FleetCheckInRecord[]>{const{data}=await(supabase as any).from("fleet_checkins").select("*").eq("fleet_work_order_id",workOrderId).order("created_at",{ascending:false});return(data??[]) as FleetCheckInRecord[];}
