import { supabase } from "@/integrations/supabase/client";
import type { JobRuntime } from "@/domain/jobs/job-runtime";
import { computeFinancialSummary,deriveInvoiceStatus,deriveSettlementStatus } from "@/domain/financials/canonical-financials";
import { normalizeJobStatus } from "@/domain/jobs/job-lifecycle";
import { buildTrustContext,type TrustContext } from "@/domain/auth/build-trust-context";
import { canViewFinancials,canViewJob } from "@/domain/auth/job-authorization";
export type { TrustContext } from "@/domain/auth/build-trust-context";
type ChecklistRow={status:string|null;is_required:boolean|null;step_name:string|null};
function checklistStatus(rows:ChecklistRow[]):JobRuntime["execution"]["checklistStatus"]{if(!rows.length)return"complete";const normalized=rows.map(r=>(r.status??"pending").toLowerCase());if(normalized.some(s=>s==="blocked"||s==="failed"))return"blocked";const pending=rows.filter(r=>r.is_required!==false&&(r.status??"pending").toLowerCase()!=="completed");if(!pending.length)return"complete";return normalized.some(s=>s==="completed"||s==="in_progress")?"in_progress":"not_started";}
function blockers(rows:ChecklistRow[]){return rows.filter(r=>["blocked","failed"].includes((r.status??"").toLowerCase())).map(r=>`Blocked step: ${r.step_name??"unnamed step"}`);}
function obj(v:unknown):Record<string,unknown>{return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};}
function customerName(c:any){return c?.company_name||[c?.first_name,c?.last_name].filter(Boolean).join(" ")||"Unknown Customer";}

export async function getJobRuntime(jobId:string,trustContext?:TrustContext):Promise<JobRuntime>{
 const trust=trustContext??await buildTrustContext();const db=supabase as any;
 const {data:appointment,error}=await db.from("appointments").select("id,workspace_id,customer_id,vehicle_id,assigned_user_id,status,starts_at,ends_at,created_at,updated_at,metadata,customer:customers(id,first_name,last_name,company_name,phone,email),vehicle:vehicles(id,vin,year,make,model)").eq("id",jobId).single();if(error||!appointment)throw error||new Error("Job not found");
 const [{data:items},{data:checklistRows},{data:records},{data:invoices}]=await Promise.all([
  db.from("appointment_items").select("service_catalog_id,description,quantity,unit_price,service_catalog(name)").eq("workspace_id",appointment.workspace_id).eq("appointment_id",jobId).order("sort_order"),
  db.from("job_execution_checklists").select("status,is_required,step_name").eq("job_id",jobId).eq("job_source","appointment"),
  db.from("service_records").select("started_at,completed_at,status,total_amount,tax_amount,subtotal,metadata").eq("workspace_id",appointment.workspace_id).eq("appointment_id",jobId).order("created_at",{ascending:false}).limit(1),
  db.from("invoices").select("id,status,subtotal,tax_total,total,amount_paid").eq("workspace_id",appointment.workspace_id).contains("metadata",{appointment_id:jobId}).order("created_at",{ascending:false}).limit(1),
 ]);
 const invoice=invoices?.[0]??null;let payments:any[]=[];if(invoice?.id){const p=await db.from("payments").select("amount,status,metadata").eq("workspace_id",appointment.workspace_id).eq("invoice_id",invoice.id);payments=p.data??[];}
 const checklist=(checklistRows??[]) as ChecklistRow[];const lifecycleStatus=normalizeJobStatus(appointment.status);const meta=obj(appointment.metadata);const record=records?.[0]??null;
 const itemSubtotal=(items??[]).reduce((s:number,i:any)=>s+Number(i.unit_price||0)*Number(i.quantity||1),0);const subtotalCents=Math.round(Number(invoice?.subtotal??record?.subtotal??itemSubtotal)*100);const taxCents=Math.round(Number(invoice?.tax_total??record?.tax_amount??0)*100);const totalCents=Math.round(Number(invoice?.total??record?.total_amount??((subtotalCents+taxCents)/100))*100);
 const summary=computeFinancialSummary({services:[{totalDueCents:totalCents as any,balanceDueCents:totalCents as any,jobStatus:lifecycleStatus==="completed"?"completed":"scheduled"}],payments:payments.map((p:any)=>({amountCents:Math.round(Number(p.amount||0)*100),refundAmountCents:Math.round(Number(obj(p.metadata).refund_amount||0)*100),status:p.status||"pending"}))});
 const visibleToUser=appointment.workspace_id===trust.orgId;const editableByUser=visibleToUser&&trust.role!=="customer";const firstItem=items?.[0];const serviceName=firstItem?.service_catalog?.name||firstItem?.description||String(meta.title||"")||undefined;
 const baseForAuth:any={id:appointment.id,orgId:appointment.workspace_id,customer:{id:appointment.customer?.id||appointment.customer_id||"",name:customerName(appointment.customer)},vehicle:{id:appointment.vehicle?.id||appointment.vehicle_id||""},service:{},lifecycle:{status:lifecycleStatus,updatedAt:appointment.updated_at||appointment.created_at||new Date().toISOString()},execution:{checklistStatus:"not_started"},dispatch:{},financials:{subtotalCents,taxCents,totalCents,paidCents:0,refundedCents:0,balanceCents:totalCents,invoiceStatus:"none",paymentStatus:"unpaid"},parts:{status:"not_required",required:[]},trust:{visibleToUser,editableByUser},timestamps:{createdAt:appointment.created_at||"",updatedAt:appointment.updated_at||appointment.created_at||""}};
 if(!canViewJob(baseForAuth,trust))throw new Error("Not authorized to view this job.");
 const runtime:JobRuntime={id:appointment.id,orgId:appointment.workspace_id,customer:{id:appointment.customer?.id||appointment.customer_id||"",name:customerName(appointment.customer),phone:appointment.customer?.phone||undefined,email:appointment.customer?.email||undefined},vehicle:{id:appointment.vehicle?.id||appointment.vehicle_id||"",vin:appointment.vehicle?.vin||undefined,year:appointment.vehicle?.year||undefined,make:appointment.vehicle?.make||undefined,model:appointment.vehicle?.model||undefined},service:{appointmentId:appointment.id,serviceTypeId:firstItem?.service_catalog_id||undefined,serviceName},lifecycle:{status:lifecycleStatus,updatedAt:appointment.updated_at||appointment.created_at||new Date().toISOString()},execution:{checklistStatus:checklistStatus(checklist),startedAt:record?.started_at||undefined,completedAt:record?.completed_at||undefined,blockingIssues:blockers(checklist)},dispatch:{technicianId:appointment.assigned_user_id||undefined,assignedAt:typeof meta.assigned_at==="string"?meta.assigned_at:undefined,enRouteAt:typeof meta.en_route_at==="string"?meta.en_route_at:undefined,arrivedAt:typeof meta.arrived_at==="string"?meta.arrived_at:undefined},financials:{subtotalCents,taxCents,totalCents,paidCents:summary.collectedCents,refundedCents:summary.refundedCents,balanceCents:Math.max(totalCents-summary.collectedCents,0),invoiceStatus:deriveInvoiceStatus(summary),paymentStatus:deriveSettlementStatus(summary)},parts:{status:"not_required",required:[]},trust:{visibleToUser,editableByUser,organizationRole:trust.role,subscriptionTier:trust.subscriptionTier},timestamps:{createdAt:appointment.created_at||new Date().toISOString(),updatedAt:appointment.updated_at||appointment.created_at||new Date().toISOString()}};
 if(!canViewFinancials(runtime,trust))runtime.financials={...runtime.financials,subtotalCents:0,taxCents:0,totalCents:0,paidCents:0,refundedCents:0,balanceCents:0,invoiceStatus:"none",paymentStatus:"unpaid"};return runtime;
}
