import { addDays,format } from "date-fns";
import { supabase } from "@/integrations/supabase/client";
import { matchesTechLifecycleFilter } from "@/lib/tech-job-state";
import { buildCommandCenterBuckets } from "@/lib/command-center-filters";
import { fetchOperationalJobsByDateRange,type OperationalJobRow } from "@/application/queries/operational-jobs.query";
import { normalizeTechNotificationPreferences } from "@/lib/technician-notification-preferences";
import { getCurrentAuthUser } from "@/lib/auth/current-user";
import { resolveCurrentWorkspace } from "@/application/queries/settings.query";
export interface TechIdentityLike{isAdmin:boolean;userId:string;techId:string;businessUserId?:string;}
export interface TechnicianAppContext{user_id:string;workspace_user_id:string;technician_id:string|null;technician_name:string;role:string;is_admin_preview:boolean;access_state:"linked"|"locked"|"deactivated"|"unlinked"|"admin_preview"|"unauthenticated"|"invited"|"roster_only";presence_state:string;field_status:string|null;shift_id:string|null;shift_status:string|null;clock_in:string|null;van_id:string|null;van_name:string|null;push_notifications_enabled:boolean;data_fresh_at:string;}
export interface TechSessionJob{id:string;job_source:"appointment"|"fleet_work_order";is_fleet:boolean;title:string;scheduled_date:string;scheduled_time:string;estimated_duration_minutes:number;status:string;dispatch_status:string;stage:string;job_priority:string;customer_name:string|null;customer_phone:string|null;location_address:string|null;location_lat:number|null;location_lng:number|null;notes:string|null;vehicle_year:number|null;vehicle_make:string|null;vehicle_model:string|null;service_name:string|null;updated_at:string|null;fleet_job_id?:string|null;fleet_job_number?:string|null;fleet_vehicle_count?:number|null;}
export interface TechSession{access_state:string;workspace_user_id:string|null;technician_id:string|null;shift:{shift_id:string;clock_in:string;break_start:string|null;break_end:string|null;status:string}|null;is_on_shift:boolean;is_on_break:boolean;jobs:TechSessionJob[];current_job:TechSessionJob|null;next_job:TechSessionJob|null;data_fresh_at:string;}
export interface JobExecutionStep{id:string;step_key:string;step_name:string;step_order:number;is_required:boolean;requires_photo:boolean;status:"pending"|"in_progress"|"completed"|"blocked";evidence_url:string|null;notes:string|null;completed_at:string|null;}
export interface TechJobWorkspace{job:Record<string,unknown>&{id:string;job_source:"appointment"|"fleet_work_order";is_fleet:boolean;title:string;status:string;dispatch_status:string;stage:string;customer:{id:string|null;name:string|null;phone:string|null;email:string|null};vehicle:{id:string|null;year:number|null;make:string|null;model:string|null;vin:string|null;license_plate:string|null};site:{address:string|null;lat:number|null;lng:number|null};};source:"appointment"|"fleet_work_order";checklist:JobExecutionStep[];parts:Array<{id:string;description:string|null;quantity:number|null;part_number:string|null}>;thread_id:string|null;data_fresh_at:string;}
export type TechJobsFilter="today"|"upcoming"|"in_progress"|"completed"|"issues";
interface TechOperationalJob{id:string;source:"appointment"|"fleet_work_order";title:string;scheduled_date:string;scheduled_time:string;estimated_duration_minutes:number|null;dispatch_status:string;status:string;job_priority:string;location_address:string|null;location_lat?:number|null;location_lng?:number|null;notes?:string|null;payment_status?:string|null;customers:{name:string;phone:string|null}|null;vehicles:{year:number;make:string;model:string;color?:string|null}|null;service_catalog:{name:string}|null;is_fleet?:boolean;fleet_job_id?:string|null;fleet_job_number?:string|null;fleet_vehicle_count?:number|null;}
export interface TechFleetAssignment{id:string;order_number:string|null;scheduled_date:string|null;scheduled_time:string|null;status:string;priority:string|null;service_type:string|null;description:string|null;total:number|null;fleet_job_id:string|null;fleet_job_number:string|null;client_name:string|null;location_name:string|null;location_address:string|null;vehicle_year:number|null;vehicle_make:string|null;vehicle_model:string|null;unit_number:string|null;license_plate:string|null;}
export async function getCurrentAuthUserId():Promise<string|null>{const{data:{user}}=await getCurrentAuthUser();return user?.id??null;}
export async function fetchTechnicianIdByAuthUserId(authUserId:string):Promise<string|null>{const context=await resolveCurrentWorkspace();if(!context)return null;const{data}=await supabase.from("workspace_members").select("user_id,role,is_active").eq("workspace_id",context.workspaceId).eq("user_id",authUserId).eq("is_active",true).maybeSingle();return data?.role==="technician"?data.user_id:null;}
async function canonicalContext():Promise<TechnicianAppContext>{const{data:{user}}=await getCurrentAuthUser();const now=new Date().toISOString();if(!user)return{user_id:"",workspace_user_id:"",technician_id:null,technician_name:"Technician",role:"technician",is_admin_preview:false,access_state:"unauthenticated",presence_state:"off_shift",field_status:null,shift_id:null,shift_status:null,clock_in:null,van_id:null,van_name:null,push_notifications_enabled:true,data_fresh_at:now};const context=await resolveCurrentWorkspace();if(!context)return{user_id:user.id,workspace_user_id:user.id,technician_id:null,technician_name:"Workspace Preview",role:"admin",is_admin_preview:true,access_state:"admin_preview",presence_state:"off_shift",field_status:null,shift_id:null,shift_status:null,clock_in:null,van_id:null,van_name:null,push_notifications_enabled:true,data_fresh_at:now};const[membershipRes,profileRes,shiftRes,prefRes]=await Promise.all([supabase.from("workspace_members").select("user_id,role,is_active").eq("workspace_id",context.workspaceId).eq("user_id",user.id).maybeSingle(),supabase.from("profiles").select("display_name").eq("id",user.id).maybeSingle(),supabase.from("time_clock_entries").select("id,clock_in,status").eq("user_id",user.id).in("status",["active","on_break"]).order("clock_in",{ascending:false}).limit(1).maybeSingle(),supabase.from("technician_notification_preferences").select("push_notifications_enabled").eq("user_id",user.id).maybeSingle()]);const member=membershipRes.data,shift=shiftRes.data;const isTech=member?.role==="technician";return{user_id:user.id,workspace_user_id:user.id,technician_id:isTech?user.id:null,technician_name:profileRes.data?.display_name||"Technician",role:member?.role||"viewer",is_admin_preview:!isTech,access_state:member?.is_active===false?"deactivated":isTech?"linked":"admin_preview",presence_state:member?.is_active===false?"deactivated":!shift?"off_shift":shift.status==="on_break"?"on_break":"available",field_status:null,shift_id:shift?.id??null,shift_status:shift?.status??null,clock_in:shift?.clock_in??null,van_id:null,van_name:null,push_notifications_enabled:prefRes.data?.push_notifications_enabled??true,data_fresh_at:now};}
export async function fetchTechnicianAppContext():Promise<TechnicianAppContext>{const{data,error}=await supabase.rpc("get_technician_app_context_v1" as never);if(!error&&data)return data as unknown as TechnicianAppContext;return canonicalContext();}
export async function fetchTechnicianJobWorkspace(jobId:string):Promise<Record<string,unknown>>{const{data,error}=await supabase.rpc("get_technician_job_workspace_v1" as never,{p_job_id:jobId} as never);if(error)throw error;return data as unknown as Record<string,unknown>;}
export async function fetchTechnicianSession():Promise<TechSession>{const{data,error}=await supabase.rpc("get_technician_session_v2" as never);if(!error&&data){const session=data as unknown as TechSession;return{...session,jobs:session.jobs??[]};}const context=await canonicalContext();return{access_state:context.access_state,workspace_user_id:context.workspace_user_id,technician_id:context.technician_id,shift:context.shift_id&&context.clock_in?{shift_id:context.shift_id,clock_in:context.clock_in,break_start:null,break_end:null,status:context.shift_status||"active"}:null,is_on_shift:Boolean(context.shift_id),is_on_break:context.shift_status==="on_break",jobs:[],current_job:null,next_job:null,data_fresh_at:new Date().toISOString()};}
export async function fetchTechnicianJobWorkspaceV2(jobId:string):Promise<TechJobWorkspace>{const{data,error}=await supabase.rpc("get_technician_job_workspace_v2" as never,{p_job_id:jobId} as never);if(error)throw error;const workspace=data as unknown as TechJobWorkspace;return{...workspace,checklist:workspace?.checklist??[],parts:workspace?.parts??[]};}
export function mapOperationalRowToTechJob(job:OperationalJobRow):TechOperationalJob{const isFleet=job.source==="work_order";return{id:job.job_id,source:isFleet?"fleet_work_order":"appointment",title:job.title||(isFleet?"Fleet Service":"Service Appointment"),scheduled_date:job.scheduled_date,scheduled_time:job.scheduled_time,estimated_duration_minutes:job.estimated_duration_minutes??job.duration_minutes,dispatch_status:job.dispatch_status??"unassigned",status:job.status??"scheduled",job_priority:job.job_priority??"normal",location_address:job.location_address,location_lat:job.location_lat,location_lng:job.location_lng,notes:job.dispatch_notes??null,customers:(job.customer_name||job.guest_name)?{name:job.customer_name??job.guest_name??"Customer",phone:job.customer_phone??job.guest_phone??null}:null,vehicles:(job.vehicle_year||job.vehicle_make||job.vehicle_model)?{year:job.vehicle_year??0,make:job.vehicle_make??"",model:job.vehicle_model??""}:null,service_catalog:job.service_catalog_name?{name:job.service_catalog_name}:null,is_fleet:isFleet,fleet_job_id:job.fleet_job_id??null,fleet_job_number:job.fleet_job_number??null,fleet_vehicle_count:job.fleet_job_vehicle_count??null};}
async function scopedJobs(identity:TechIdentityLike,from:string,to:string){const{data,error}=await fetchOperationalJobsByDateRange(identity.businessUserId||identity.userId,from,to);if(error)throw error;return((data??[]) as OperationalJobRow[]).filter(job=>identity.isAdmin||job.assigned_technician_id===identity.techId).map(mapOperationalRowToTechJob);}
export async function fetchTechJobsByFilter(identity:TechIdentityLike,filter:TechJobsFilter){const today=format(new Date(),"yyyy-MM-dd"),nextWeek=format(addDays(new Date(),7),"yyyy-MM-dd");return(await scopedJobs(identity,today,nextWeek)).filter(job=>matchesTechLifecycleFilter(job,filter,today,nextWeek)).sort((a,b)=>`${a.scheduled_date} ${a.scheduled_time}`.localeCompare(`${b.scheduled_date} ${b.scheduled_time}`)) as unknown as Array<Record<string,unknown>>;}
export async function fetchTechTodayData(identity:TechIdentityLike){const today=format(new Date(),"yyyy-MM-dd"),nextWeek=format(addDays(new Date(),7),"yyyy-MM-dd");const[jobs,clock]=await Promise.all([scopedJobs(identity,today,nextWeek),supabase.from("time_clock_entries").select("clock_in,clock_out").eq("user_id",identity.userId).gte("clock_in",`${today}T00:00:00`)]);return{jobs:jobs as unknown as Array<Record<string,unknown>>,clockEntries:(clock.data??[]) as Array<Record<string,unknown>>};}
export async function fetchTechDispatchParityByDate(identity:TechIdentityLike,dateStr:string){const scoped=await scopedJobs(identity,dateStr,dateStr);const buckets=buildCommandCenterBuckets(scoped.map(job=>({id:job.id,status:job.status,dispatch_status:job.dispatch_status})));const techCounts={today:scoped.filter(j=>matchesTechLifecycleFilter(j,"today",dateStr,dateStr)).length,active:scoped.filter(j=>matchesTechLifecycleFilter(j,"in_progress",dateStr,dateStr)).length,completed:scoped.filter(j=>matchesTechLifecycleFilter(j,"completed",dateStr,dateStr)).length,issues:scoped.filter(j=>matchesTechLifecycleFilter(j,"issues",dateStr,dateStr)).length};return{date:dateStr,techCounts,commandCenterCounts:{queue:buckets.queue.length,active:buckets.active.length,completed:buckets.completed.length},deltas:{activeMinusActive:techCounts.active-buckets.active.length,completedMinusCompleted:techCounts.completed-buckets.completed.length}};}
export async function fetchTechMoreDataForCurrentUser(){const id=await getCurrentAuthUserId();if(!id)return{tech:null,clockEntry:null};const[profile,clock]=await Promise.all([supabase.from("profiles").select("id,display_name,phone,avatar_url").eq("id",id).maybeSingle(),supabase.from("time_clock_entries").select("id,clock_in,status").eq("user_id",id).in("status",["active","on_break"]).order("clock_in",{ascending:false}).limit(1)]);return{tech:profile.data?{id:profile.data.id,name:profile.data.display_name,phone:profile.data.phone,avatar_url:profile.data.avatar_url,status:"available"}:null,clockEntry:(clock.data?.[0] as Record<string,unknown>|undefined)??null};}
export async function fetchTechInventoryDataForCurrentUser(){const id=await getCurrentAuthUserId();if(!id)return{vanId:null,vanName:"",items:[] as Array<Record<string,unknown>>};const{data:van}=await supabase.from("vans").select("id,name").eq("assigned_technician_id",id).eq("is_active",true).limit(1).maybeSingle();if(!van)return{vanId:null,vanName:"",items:[] as Array<Record<string,unknown>>};const{data}=await supabase.from("van_inventory").select("id,quantity,min_quantity,inventory_items(id,name,sku,category,unit_cost)").eq("van_id",van.id);return{vanId:van.id,vanName:van.name,items:(data??[]) as Array<Record<string,unknown>>};}
export async function fetchTechProfileDataForCurrentUser(){const id=await getCurrentAuthUserId();if(!id)return{tech:null,skills:[] as Array<Record<string,unknown>>};const{data:profile}=await supabase.from("profiles").select("id,display_name,phone,avatar_url").eq("id",id).maybeSingle();return{tech:profile?{id:profile.id,name:profile.display_name,phone:profile.phone,avatar_url:profile.avatar_url,status:"available",total_jobs_completed:null}:null,skills:[] as Array<Record<string,unknown>>};}
export async function fetchTechNotificationSettingsForCurrentUser(){const id=await getCurrentAuthUserId();if(!id)return normalizeTechNotificationPreferences(null);const{data,error}=await supabase.from("technician_notification_preferences").select("push_notifications_enabled,dispatch_push_enabled,customer_sms_enabled,customer_email_enabled,offline_cache_enabled").eq("user_id",id).maybeSingle();if(error)throw error;return normalizeTechNotificationPreferences({pushNotificationsEnabled:data?.push_notifications_enabled,dispatchPushEnabled:data?.dispatch_push_enabled,customerSmsEnabled:data?.customer_sms_enabled,customerEmailEnabled:data?.customer_email_enabled,offlineCacheEnabled:data?.offline_cache_enabled});}
export async function fetchTechRouteStopsForCurrentUserToday(identity:TechIdentityLike){const today=format(new Date(),"yyyy-MM-dd");return(await scopedJobs(identity,today,today)).filter(job=>job.status!=="cancelled"&&job.dispatch_status!=="cancelled") as unknown as Array<Record<string,unknown>>;}
export async function fetchTechMessagesDataForCurrentUser(){const id=await getCurrentAuthUserId();if(!id)return{techId:null,humanMessages:[],statusNotes:[],activeJobs:[],activeJobsError:null,eventsError:null,notesError:null};const context=await resolveCurrentWorkspace();if(!context)return{techId:id,humanMessages:[],statusNotes:[],activeJobs:[],activeJobsError:null,eventsError:null,notesError:null};const today=format(new Date(),"yyyy-MM-dd"),nextWeek=format(addDays(new Date(),7),"yyyy-MM-dd");const[jobs,events]=await Promise.all([fetchOperationalJobsByDateRange(context.workspaceId,today,nextWeek),supabase.from("dispatch_events").select("id,appointment_id,event_type,notes,created_at,performed_by").eq("technician_id",id).order("created_at",{ascending:false}).limit(50)]);return{techId:id,humanMessages:events.data??[],statusNotes:events.data??[],activeJobs:(jobs.data??[]).filter((job:OperationalJobRow)=>job.assigned_technician_id===id),activeJobsError:jobs.error,eventsError:events.error,notesError:null};}
export async function fetchTechJobDetailBundle(jobId:string){const workspace=await fetchTechnicianJobWorkspaceV2(jobId);const photos=await supabase.from("job_photos").select("id,photo_type,storage_path,file_name,created_at").eq("job_id",jobId).order("created_at");return{job:workspace.job,source:workspace.source,services:workspace.parts??[],photos:photos.data??[],checklist:workspace.checklist??[],events:[] as Array<Record<string,unknown>>,notes:[] as Array<Record<string,unknown>>,servicesError:null,photosError:photos.error?.message??null,eventsError:null,notesError:null};}
export async function fetchTechFleetAssignments(identity:TechIdentityLike&{isAdmin?:boolean}):Promise<TechFleetAssignment[]>{const today=format(new Date(),"yyyy-MM-dd"),nextWeek=format(addDays(new Date(),14),"yyyy-MM-dd");const jobs=await scopedJobs(identity,today,nextWeek);return jobs.filter(j=>j.source==="fleet_work_order").map(j=>({id:j.id,order_number:j.fleet_job_number??j.id.slice(0,8),scheduled_date:j.scheduled_date||null,scheduled_time:j.scheduled_time||null,status:j.status,priority:j.job_priority,service_type:j.service_catalog?.name??j.title,description:j.notes??null,total:null,fleet_job_id:j.fleet_job_id??null,fleet_job_number:j.fleet_job_number??null,client_name:j.customers?.name??null,location_name:null,location_address:j.location_address,vehicle_year:j.vehicles?.year??null,vehicle_make:j.vehicles?.make??null,vehicle_model:j.vehicles?.model??null,unit_number:null,license_plate:null}));}
