import { useState } from "react";
import { cancelCustomerPortalAppointment } from "@/application/commands/customer-portal.command";
import { toast } from "@/components/ui/sonner";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Loader2, AlertTriangle } from "lucide-react";
interface Props { appointment:{id:string;title:string;can_manage:boolean;service_catalog?:{name:string}|null};open:boolean;onClose:()=>void;onSuccess:()=>void; }
export function CancelDialog({appointment,open,onClose,onSuccess}:Props){const[reason,setReason]=useState("");const[submitting,setSubmitting]=useState(false);const handleCancel=async()=>{if(!appointment.can_manage)return;setSubmitting(true);let result;try{result=await cancelCustomerPortalAppointment(appointment.id,reason||undefined);}catch(error){setSubmitting(false);toast.error(error instanceof Error?error.message:"Failed to cancel appointment");return;}setSubmitting(false);if(!result.success){toast.error(result.message||"Unable to cancel. The cancellation window may have passed.");return;}toast.success("Appointment cancelled successfully");onSuccess();};return <Dialog open={open} onOpenChange={(v)=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle className="flex items-center gap-2 text-destructive"><AlertTriangle className="h-5 w-5"/>Cancel Appointment</DialogTitle><DialogDescription>Are you sure you want to cancel &ldquo;{appointment.service_catalog?.name||appointment.title}&rdquo;? This action may not be reversible.</DialogDescription></DialogHeader><div className="py-4"><label className="text-sm font-medium mb-2 block">Reason (optional)</label><Textarea placeholder="Let us know why you're cancelling..." value={reason} onChange={(e)=>setReason(e.target.value)} rows={3}/></div><DialogFooter><Button variant="outline" onClick={onClose} disabled={submitting}>Keep Appointment</Button><Button variant="destructive" onClick={handleCancel} disabled={submitting}>{submitting&&<Loader2 className="h-4 w-4 mr-2 animate-spin"/>}Yes, Cancel Appointment</Button></DialogFooter></DialogContent></Dialog>}
