import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const OFFLINE_SCHEMA_VERSION = 4;

export const offlineSchema = appSchema({
  version: OFFLINE_SCHEMA_VERSION,
  tables: [
    tableSchema({
      name: 'offline_appointments',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string', isOptional: true },
        { name: 'status', type: 'string', isOptional: true },
        { name: 'scheduled_date', type: 'string', isOptional: true },
        { name: 'scheduled_time', type: 'string', isOptional: true },
        { name: 'customer_server_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'vehicle_server_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'updated_at_server', type: 'number', isOptional: true },
        { name: 'updated_at_local', type: 'number' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'offline_customers',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string', isOptional: true },
        { name: 'email', type: 'string', isOptional: true, isIndexed: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'updated_at_server', type: 'number', isOptional: true },
        { name: 'updated_at_local', type: 'number' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'offline_vehicles',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'customer_server_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'make', type: 'string', isOptional: true },
        { name: 'model', type: 'string', isOptional: true },
        { name: 'year', type: 'number', isOptional: true },
        { name: 'vin', type: 'string', isOptional: true, isIndexed: true },
        { name: 'updated_at_server', type: 'number', isOptional: true },
        { name: 'updated_at_local', type: 'number' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'offline_outbox',
      columns: [
        { name: 'mutation_id', type: 'string', isIndexed: true },
        { name: 'entity', type: 'string', isIndexed: true },
        { name: 'operation', type: 'string', isIndexed: true },
        { name: 'payload', type: 'string' },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'updated_at', type: 'number' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'attempt_count', type: 'number' },
        { name: 'next_retry_at', type: 'number', isOptional: true, isIndexed: true },
        { name: 'last_error', type: 'string', isOptional: true },
        { name: 'idempotency_key', type: 'string', isIndexed: true },
        { name: 'acked_at', type: 'number', isOptional: true, isIndexed: true },
        { name: 'dead_letter_reason', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'offline_sync_state',
      columns: [
        { name: 'entity', type: 'string', isIndexed: true },
        { name: 'cursor', type: 'string', isOptional: true },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'offline_fleet_work_orders',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'order_number', type: 'string', isOptional: true },
        { name: 'status', type: 'string', isOptional: true, isIndexed: true },
        { name: 'priority', type: 'string', isOptional: true },
        { name: 'scheduled_date', type: 'string', isOptional: true },
        { name: 'service_type', type: 'string', isOptional: true },
        { name: 'po_number', type: 'string', isOptional: true },
        { name: 'total', type: 'number', isOptional: true },
        { name: 'vehicle_server_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'client_server_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'updated_at_server', type: 'number', isOptional: true },
        { name: 'updated_at_local', type: 'number' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'offline_service_catalog',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'default_price', type: 'number', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'sort_order', type: 'number', isOptional: true },
        { name: 'updated_at_server', type: 'number', isOptional: true },
        { name: 'updated_at_local', type: 'number' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'offline_technician_messages',
      columns: [
        { name: 'server_id', type: 'string', isIndexed: true },
        { name: 'appointment_server_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'message_type', type: 'string', isOptional: true, isIndexed: true },
        { name: 'title', type: 'string', isOptional: true },
        { name: 'body', type: 'string', isOptional: true },
        { name: 'created_at_server', type: 'number', isOptional: true, isIndexed: true },
        { name: 'updated_at_server', type: 'number', isOptional: true },
        { name: 'updated_at_local', type: 'number' },
        { name: 'sync_status', type: 'string', isIndexed: true },
        { name: 'is_deleted', type: 'boolean' },
      ],
    }),
  ],
});
