import { Q,type Model } from '@nozbe/watermelondb';
import { supabase } from '@/integrations/supabase/client';
import { getOfflineDatabase } from './index';
import { isOfflineEligibleForUser } from '../rollout';
import { emitOfflineObservability } from '../observability';
import { getCurrentAuthUser } from '@/lib/auth/current-user';
import { resolveCurrentWorkspace } from '@/application/queries/settings.query';
const SYNCED='synced';const ENTITIES={appointments:'appointments',customers:'customers',vehicles:'vehicles',workOrders:'fleet_work_orders',catalog:'service_catalog',messages:'technician_messages'} as const;type PullEntity=typeof ENTITIES[keyof typeof ENTITIES];interface SyncRow{id:string;updated_at?:string|null;}
const readRaw=(model:Model,key:string):unknown=>Reflect.get(model._raw,key);function writeRaw(model:Model,fields:Record<string,unknown>){for(const[k,v]of Object.entries(fields))Reflect.set(model._raw,k,v);}function toEpoch(value?:string|null){if(!value)return undefined;const p=Date.parse(value);return Number.isNaN(p)?undefined:p;}async function currentUserId(){const{data,error}=await getCurrentAuthUser();if(error)return null;return data.user?.id??null;}
async function cursor(entity:PullEntity):Promise<string|null>{const db=getOfflineDatabase();if(!db)return null;const rows=await db.get('offline_sync_state').query(Q.where('entity',entity)).fetch();const value=rows.length?readRaw(rows[0],'cursor'):null;return typeof value==='string'?value:null;}async function setCursor(entity:PullEntity,value:string){const db=getOfflineDatabase();if(!db)return;const rows=await db.get('offline_sync_state').query(Q.where('entity',entity)).fetch();const now=Date.now();await db.write(async()=>{if(rows.length)await rows[0].update(r=>writeRaw(r,{cursor:value,updated_at:now}));else await db.get('offline_sync_state').create(r=>writeRaw(r,{entity,cursor:value,updated_at:now}));});}
async function markMissing(table:string,ids:Set<string>){const db=getOfflineDatabase();if(!db)return;const local=await db.get(table).query().fetch();await db.write(async()=>{for(const row of local){const id=readRaw(row,'server_id');if(typeof id!=='string'||ids.has(id))continue;await row.update(r=>writeRaw(r,{is_deleted:true,sync_status:SYNCED,updated_at_local:Date.now()}));}});}function accept(local:Model,server?:number){const status=readRaw(local,'sync_status'),localTime=Number(readRaw(local,'updated_at_local')??0);return status==='pending'||status==='failed'?Number(server??0)>=localTime:true;}
async function upsert<T extends SyncRow>(table:string,rows:T[],project:(record:Model,row:T)=>void){const db=getOfflineDatabase();if(!db)return;const now=Date.now();await db.write(async()=>{const collection=db.get(table);for(const row of rows){const found=await collection.query(Q.where('server_id',row.id)).fetch();const stamp=toEpoch(row.updated_at);if(found.length){if(!accept(found[0],stamp))continue;await found[0].update(r=>{project(r,row);writeRaw(r,{updated_at_server:stamp,updated_at_local:now,sync_status:SYNCED,is_deleted:false});});}else await collection.create(r=>{writeRaw(r,{server_id:row.id});project(r,row);writeRaw(r,{updated_at_server:stamp,updated_at_local:now,sync_status:SYNCED,is_deleted:false});});}});}function latest(rows:SyncRow[],current:string|null){return rows.map(r=>r.updated_at).filter((v):v is string=>Boolean(v)).sort().at(-1)??current;}function metadata(v:unknown):Record<string,unknown>{return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};}
async function pullAppointments(workspaceId:string){const cur=await cursor(ENTITIES.appointments);let q=supabase.from('appointments').select('id,status,starts_at,ends_at,customer_id,vehicle_id,notes,metadata,updated_at').eq('workspace_id',workspaceId).order('updated_at');if(cur)q=q.gt('updated_at',cur);const res=await q;if(res.error)throw new Error(`[offline] appointments pull failed: ${res.error.message}`);const rows=res.data??[];await upsert('offline_appointments',rows,(r,row)=>{const start=row.starts_at?new Date(row.starts_at):null;const meta=metadata(row.metadata);writeRaw(r,{title:String(meta.title||row.notes||'Appointment'),status:row.status,scheduled_date:start?start.toISOString().slice(0,10):'',scheduled_time:start?start.toISOString().slice(11,16):'',customer_server_id:row.customer_id,vehicle_server_id:row.vehicle_id});});const next=latest(rows,cur);if(next)await setCursor(ENTITIES.appointments,next);await markMissing('offline_appointments',new Set(rows.map(r=>r.id)));}
async function pullCustomers(workspaceId:string){const cur=await cursor(ENTITIES.customers);let q=supabase.from('customers').select('id,first_name,last_name,company_name,email,phone,updated_at').eq('workspace_id',workspaceId).order('updated_at');if(cur)q=q.gt('updated_at',cur);const res=await q;if(res.error)throw new Error(`[offline] customers pull failed: ${res.error.message}`);const rows=res.data??[];await upsert('offline_customers',rows,(r,row)=>writeRaw(r,{name:row.company_name||[row.first_name,row.last_name].filter(Boolean).join(' ')||'Customer',email:row.email,phone:row.phone}));const next=latest(rows,cur);if(next)await setCursor(ENTITIES.customers,next);await markMissing('offline_customers',new Set(rows.map(r=>r.id)));}
async function pullVehicles(workspaceId:string){const cur=await cursor(ENTITIES.vehicles);let q=supabase.from('vehicles').select('id,customer_id,make,model,year,vin,updated_at').eq('workspace_id',workspaceId).order('updated_at');if(cur)q=q.gt('updated_at',cur);const res=await q;if(res.error)throw new Error(`[offline] vehicles pull failed: ${res.error.message}`);const rows=res.data??[];await upsert('offline_vehicles',rows,(r,row)=>writeRaw(r,{customer_server_id:row.customer_id,make:row.make,model:row.model,year:row.year,vin:row.vin}));const next=latest(rows,cur);if(next)await setCursor(ENTITIES.vehicles,next);await markMissing('offline_vehicles',new Set(rows.map(r=>r.id)));}
async function pullWorkOrders(workspaceId:string){const cur=await cursor(ENTITIES.workOrders);let q=supabase.from('work_orders').select('id,number,status,priority,opened_at,customer_id,vehicle_id,complaint,metadata,updated_at').eq('workspace_id',workspaceId).order('updated_at');if(cur)q=q.gt('updated_at',cur);const res=await q;if(res.error)throw new Error(`[offline] work orders pull failed: ${res.error.message}`);const rows=res.data??[];await upsert('offline_fleet_work_orders',rows,(r,row)=>{const meta=metadata(row.metadata);writeRaw(r,{order_number:row.number||row.id.slice(0,8),status:row.status,priority:row.priority,scheduled_date:row.opened_at?String(row.opened_at).slice(0,10):null,service_type:String(meta.requested_service||row.complaint||'Work order'),po_number:typeof meta.po_number==='string'?meta.po_number:null,total:Number(meta.total||0),vehicle_server_id:row.vehicle_id,client_server_id:row.customer_id});});const next=latest(rows,cur);if(next)await setCursor(ENTITIES.workOrders,next);await markMissing('offline_fleet_work_orders',new Set(rows.map(r=>r.id)));}
async function pullCatalog(workspaceId:string){const cur=await cursor(ENTITIES.catalog);let q=supabase.from('service_catalog').select('id,name,category,labor_price,is_active,metadata,updated_at').eq('workspace_id',workspaceId).order('updated_at');if(cur)q=q.gt('updated_at',cur);const res=await q;if(res.error)throw new Error(`[offline] catalog pull failed: ${res.error.message}`);const rows=res.data??[];await upsert('offline_service_catalog',rows,(r,row)=>writeRaw(r,{name:row.name,category:row.category,default_price:row.labor_price,is_active:row.is_active,sort_order:Number(metadata(row.metadata).sort_order||0)}));const next=latest(rows,cur);if(next)await setCursor(ENTITIES.catalog,next);await markMissing('offline_service_catalog',new Set(rows.map(r=>r.id)));}
async function pullMessages(workspaceId:string,userId:string){const cur=await cursor(ENTITIES.messages);let q=supabase.from('appointments').select('id,metadata,updated_at').eq('workspace_id',workspaceId).eq('assigned_user_id',userId).order('updated_at');if(cur)q=q.gt('updated_at',cur);const res=await q;if(res.error)throw new Error(`[offline] technician message pull failed: ${res.error.message}`);const rows=(res.data??[]).map(row=>{const note=metadata(row.metadata).dispatch_notes;return{id:row.id,appointment_id:row.id,dispatch_notes:typeof note==='string'?note:'',updated_at:row.updated_at};}).filter(row=>row.dispatch_notes);await upsert('offline_technician_messages',rows,(r,row)=>writeRaw(r,{appointment_server_id:row.appointment_id,message_type:row.dispatch_notes.toLowerCase().includes('urgent')?'urgent':'dispatch',title:'Dispatch Note',body:row.dispatch_notes,created_at_server:toEpoch(row.updated_at)}));const next=latest(rows,cur);if(next)await setCursor(ENTITIES.messages,next);await markMissing('offline_technician_messages',new Set(rows.map(r=>r.id)));}
export async function runOfflinePullSync():Promise<void>{const db=getOfflineDatabase();if(!db)return;const userId=await currentUserId();if(!userId||!isOfflineEligibleForUser(userId))return;const context=await resolveCurrentWorkspace();if(!context)return;await pullAppointments(context.workspaceId);await pullCustomers(context.workspaceId);await pullVehicles(context.workspaceId);await pullWorkOrders(context.workspaceId);await pullCatalog(context.workspaceId);await pullMessages(context.workspaceId,userId);await emitOfflineObservability('pull_sync');}
