import type { HTMLAttributes, ReactNode } from "react";
import { cn } from "@/lib/utils";

export function PageContainer({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn("mx-auto w-full max-w-[1600px]", className)} {...props} />; }
export function PageHeader({ title, description, actions, className }: { title: string; description?: string; actions?: ReactNode; className?: string }) { return <header className={cn("flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between", className)}><div className="min-w-0"><h1 className="text-2xl font-semibold tracking-tight">{title}</h1>{description && <p className="mt-0.5 max-w-3xl text-sm text-muted-foreground">{description}</p>}</div>{actions && <div className="flex shrink-0 flex-wrap items-center gap-2">{actions}</div>}</header>; }
export function PageToolbar({ title, meta, controls, actions, className }: { title: string; meta?: ReactNode; controls?: ReactNode; actions?: ReactNode; className?: string }) { return <div className={cn("flex flex-col gap-2 border-b bg-card px-3 py-2.5 sm:flex-row sm:items-center", className)}><div className="min-w-0"><h2 className="text-sm font-semibold">{title}</h2>{meta && <div className="text-xs text-muted-foreground">{meta}</div>}</div>{controls && <div className="flex min-w-0 flex-1 flex-wrap items-center gap-2 sm:ml-4">{controls}</div>}{actions && <div className="flex shrink-0 items-center gap-2 sm:ml-auto">{actions}</div>}</div>; }
export function Section({ className, ...props }: HTMLAttributes<HTMLElement>) { return <section className={cn("space-y-3", className)} {...props} />; }
export function Panel({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn("rounded-lg border bg-card p-4 text-card-foreground shadow-sm", className)} {...props} />; }
export function ResponsiveGrid({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn("grid gap-3 sm:grid-cols-2 xl:grid-cols-4", className)} {...props} />; }
export function EmptyState({ icon, title, description, action, variant = "standard", className }: { icon?: ReactNode; title: string; description?: string; action?: ReactNode; variant?: "inline" | "standard" | "onboarding"; className?: string }) { const height = { inline: "min-h-[88px] p-3", standard: "min-h-[180px] p-5", onboarding: "min-h-[300px] p-8" }; return <div className={cn("flex flex-col items-center justify-center rounded-lg border border-dashed bg-muted/20 text-center", height[variant], className)}>{icon && <div className={cn("text-muted-foreground", variant === "inline" ? "mb-1" : "mb-3")}>{icon}</div>}<h3 className={cn("font-semibold", variant === "inline" ? "text-sm" : "text-base")}>{title}</h3>{description && <p className="mt-1 max-w-md text-sm text-muted-foreground">{description}</p>}{action && <div className={variant === "inline" ? "mt-2" : "mt-4"}>{action}</div>}</div>; }
export function StickyActionBar({ className, children, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn("sticky-action-bar", className)} {...props}><div className="mx-auto flex min-h-16 w-full max-w-4xl items-center justify-between gap-3 px-4 py-2">{children}</div></div>; }
