import { json, errorResponse, paginationSchema, requireWorkspaceMember } from "@/server/api";
import { z } from "zod";

const appointmentSchema=z.object({workspace_id:z.string().uuid(),customer_id:z.string().uuid(),vehicle_id:z.string().uuid().nullable().optional(),location_id:z.string().uuid().nullable().optional(),assigned_user_id:z.string().uuid().nullable().optional(),starts_at:z.string().datetime(),ends_at:z.string().datetime(),source:z.string().trim().max(40).default("staff"),status:z.string().trim().max(40).default("confirmed"),notes:z.string().max(5000).nullable().optional(),title:z.string().trim().max(200).optional(),description:z.string().max(5000).nullable().optional(),guest_name:z.string().max(200).nullable().optional(),guest_email:z.string().email().max(320).nullable().optional(),guest_phone:z.string().max(40).nullable().optional(),service_catalog_id:z.string().uuid().nullable().optional(),estimated_cost:z.number().nonnegative().nullable().optional(),tax_amount:z.number().nonnegative().nullable().optional(),location_address:z.string().max(500).nullable().optional(),customer_city:z.string().max(120).nullable().optional(),customer_state:z.string().max(120).nullable().optional(),customer_postal_code:z.string().max(24).nullable().optional(),override_availability:z.boolean().optional().default(false)}).superRefine((v,ctx)=>{if(new Date(v.ends_at)<=new Date(v.starts_at))ctx.addIssue({code:"custom",path:["ends_at"],message:"ends_at must be after starts_at"});});
function compatibilityMetadata(body:z.infer<typeof appointmentSchema>){return{title:body.title??null,description:body.description??null,guest_name:body.guest_name??null,guest_email:body.guest_email??null,guest_phone:body.guest_phone??null,service_catalog_id:body.service_catalog_id??null,estimated_cost:body.estimated_cost??null,tax_amount:body.tax_amount??null,location_address:body.location_address??null,customer_city:body.customer_city??null,customer_state:body.customer_state??null,customer_postal_code:body.customer_postal_code??null,override_availability:body.override_availability};}
function localParts(iso:string,timeZone:string){const parts=new Intl.DateTimeFormat("en-US",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",weekday:"long",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(iso));const text=(t:Intl.DateTimeFormatPartTypes)=>parts.find(p=>p.type===t)?.value||"";return{date:`${text("year")}-${text("month")}-${text("day")}`,weekday:text("weekday").toLowerCase(),minutes:Number(text("hour"))*60+Number(text("minute"))};}
function configuredHours(settings:any,weekday:string){const raw=settings?.day_hours&&typeof settings.day_hours==="object"?settings.day_hours[weekday]:null;const explicit=typeof raw?.is_open==="boolean"?raw.is_open:typeof raw?.isOpen==="boolean"?raw.isOpen:undefined;const isOpen=explicit??(Array.isArray(settings?.working_days)&&settings.working_days.some((d:string)=>d.toLowerCase()===weekday));const parse=(v:string|undefined,fallback:string)=>{const m=/^(\d{1,2}):(\d{2})/.exec(v||fallback);return m?Number(m[1])*60+Number(m[2]):0;};return{isOpen,open:parse(raw?.open,settings?.opening_time||"09:00"),close:parse(raw?.close,settings?.closing_time||"17:00")};}

export async function GET(request:Request){try{const url=new URL(request.url),workspaceId=url.searchParams.get("workspace_id");if(!workspaceId)throw new Error("workspace_id is required");const{supabase}=await requireWorkspaceMember(workspaceId,undefined,request);const{limit,offset}=paginationSchema.parse(Object.fromEntries(url.searchParams));const{data,error}=await supabase.from("appointments").select("*,customers(id,first_name,last_name,email,phone),vehicles(id,customer_id,year,make,model,vin,license_plate,plate_region,color,mileage,notes),locations(id,name)").eq("workspace_id",workspaceId).order("starts_at").range(offset,offset+limit-1);if(error)throw error;return json({data:data??[],pagination:{limit,offset}});}catch(error){return errorResponse(error);}}

export async function POST(request:Request){try{const body=appointmentSchema.parse(await request.json());const{supabase,user}=await requireWorkspaceMember(body.workspace_id,["owner","admin","manager","service_advisor","receptionist","dispatcher"],request);
if(body.assigned_user_id){const{data,error}=await supabase.from("workspace_members").select("user_id").eq("workspace_id",body.workspace_id).eq("user_id",body.assigned_user_id).eq("is_active",true).maybeSingle();if(error)throw error;if(!data)return json({error:{code:"invalid_assignment",message:"The assigned user is not an active member of this workspace."}},{status:400});}
const[{data:workspace,error:we},{data:settings,error:se}]=await Promise.all([supabase.from("workspaces").select("timezone").eq("id",body.workspace_id).single(),supabase.from("workspace_settings").select("day_hours,opening_time,closing_time,working_days,buffer_time_before,buffer_time_after,min_lead_time_hours").eq("workspace_id",body.workspace_id).single()]);if(we)throw we;if(se)throw se;
if(!body.override_availability){const tz=workspace?.timezone||"UTC",start=localParts(body.starts_at,tz),end=localParts(body.ends_at,tz),hours=configuredHours(settings,start.weekday);if(start.date!==end.date||!hours.isOpen||start.minutes<hours.open||end.minutes>hours.close)return json({error:{code:"outside_business_hours",message:"The requested time is outside configured availability."}},{status:409});const lead=Math.max(0,Number(settings?.min_lead_time_hours||0));if(Date.parse(body.starts_at)<Date.now()+lead*3600000)return json({error:{code:"lead_time",message:"The requested time is inside the minimum lead-time window."}},{status:409});const db=supabase as any;const{data:blackout,error:be}=await db.from("workspace_blackout_dates").select("id").eq("workspace_id",body.workspace_id).eq("blocked_date",start.date).limit(1);if(be)throw be;if(blackout?.length)return json({error:{code:"blackout_date",message:"The requested date is unavailable."}},{status:409});const before=Math.max(0,Number(settings?.buffer_time_before||0)),after=Math.max(0,Number(settings?.buffer_time_after||0)),queryEnd=new Date(Date.parse(body.ends_at)+before*60000).toISOString(),queryStart=new Date(Date.parse(body.starts_at)-after*60000).toISOString();const{data:conflicts,error:ce}=await supabase.from("appointments").select("id").eq("workspace_id",body.workspace_id).not("status","in",'("cancelled","no_show")').lt("starts_at",queryEnd).gt("ends_at",queryStart).limit(1);if(ce)throw ce;if(conflicts?.length)return json({error:{code:"schedule_conflict",message:"The requested time overlaps an existing appointment or buffer."}},{status:409});}
const{data,error}=await supabase.from("appointments").insert({workspace_id:body.workspace_id,customer_id:body.customer_id,vehicle_id:body.vehicle_id??null,location_id:body.location_id??null,assigned_user_id:body.assigned_user_id??null,starts_at:body.starts_at,ends_at:body.ends_at,source:body.source,status:body.status as any,notes:body.notes??null,created_by:user.id,metadata:compatibilityMetadata(body)}).select().single();if(error)throw error;return json({data},{status:201});}catch(error){return errorResponse(error);}}
