import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const STRIPE_SECRET_KEY = Deno.env.get("STRIPE_SECRET_KEY") ?? "";
const STRIPE_CONNECT_CLIENT_ID = Deno.env.get("STRIPE_CONNECT_CLIENT_ID") ?? "";
const STRIPE_CONNECT_REDIRECT_URI = Deno.env.get("STRIPE_CONNECT_REDIRECT_URI") ?? "https://servicewriter.xyz/settings?stripe_callback=true";
const SQUARE_APPLICATION_ID = Deno.env.get("SQUARE_APPLICATION_ID") ?? "";
const SQUARE_APPLICATION_SECRET = Deno.env.get("SQUARE_APPLICATION_SECRET") ?? "";
const SQUARE_REDIRECT_URI = Deno.env.get("SQUARE_REDIRECT_URI") ?? "https://servicewriter.xyz/settings?square_callback=true";
const SQUARE_ENVIRONMENT = (Deno.env.get("SQUARE_ENVIRONMENT") ?? "production").toLowerCase();
const PROVIDER_TOKEN_ENCRYPTION_KEY = Deno.env.get("PROVIDER_TOKEN_ENCRYPTION_KEY") ?? "";

const admin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, { auth: { autoRefreshToken: false, persistSession: false } });
const cors = { "access-control-allow-origin": "*", "access-control-allow-headers": "authorization, x-client-info, apikey, content-type", "access-control-allow-methods": "POST, OPTIONS" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json", ...cors } });

function b64url(bytes: Uint8Array): string { let s = ""; for (const b of bytes) s += String.fromCharCode(b); return btoa(s).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); }
function fromB64url(value: string): Uint8Array { const n = value.replaceAll("-", "+").replaceAll("_", "/") + "===".slice((value.length + 3) % 4); return Uint8Array.from(atob(n), c => c.charCodeAt(0)); }
async function digestBytes(value: string): Promise<Uint8Array> { return new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value))); }
async function stateKey() { if (!SUPABASE_SERVICE_ROLE_KEY) throw new Error("Server state signing key is unavailable"); return crypto.subtle.importKey("raw", await digestBytes(`servicewriter-provider-state:${SUPABASE_SERVICE_ROLE_KEY}`), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); }
async function sign(value: string) { return b64url(new Uint8Array(await crypto.subtle.sign("HMAC", await stateKey(), new TextEncoder().encode(value)))); }
async function makeState(userId: string, workspaceId: string, provider: string) { const payload = b64url(new TextEncoder().encode(JSON.stringify({ sub: userId, workspace_id: workspaceId, provider, exp: Date.now() + 10 * 60_000, nonce: crypto.randomUUID() }))); return `${payload}.${await sign(payload)}`; }
async function verifyState(state: string, userId: string, workspaceId: string, provider: string) { const [payload, signature] = state.split("."); if (!payload || !signature || await sign(payload) !== signature) return false; const decoded = JSON.parse(new TextDecoder().decode(fromB64url(payload))) as Record<string, unknown>; return decoded.sub === userId && decoded.workspace_id === workspaceId && decoded.provider === provider && typeof decoded.exp === "number" && decoded.exp > Date.now(); }

async function encryptionKey() { const source = PROVIDER_TOKEN_ENCRYPTION_KEY || `servicewriter-provider-token:${SUPABASE_SERVICE_ROLE_KEY}`; if (!source) throw new Error("Provider token encryption is not configured"); const raw = PROVIDER_TOKEN_ENCRYPTION_KEY ? fromB64url(source) : await digestBytes(source); if (raw.byteLength !== 32) throw new Error("PROVIDER_TOKEN_ENCRYPTION_KEY must be a base64url-encoded 32-byte key"); return crypto.subtle.importKey("raw", raw, "AES-GCM", false, ["encrypt"]); }
async function encrypt(value: string | null | undefined) { if (!value) return null; const iv = crypto.getRandomValues(new Uint8Array(12)); const cipher = new Uint8Array(await crypto.subtle.encrypt({ name: "AES-GCM", iv }, await encryptionKey(), new TextEncoder().encode(value))); const combined = new Uint8Array(iv.length + cipher.length); combined.set(iv); combined.set(cipher, iv.length); return b64url(combined); }

async function userFromRequest(request: Request) { const token = (request.headers.get("authorization") ?? "").replace(/^Bearer\s+/i, "").trim(); if (!token) throw new Error("Not authenticated"); const { data, error } = await admin.auth.getUser(token); if (error || !data.user) throw new Error("Not authenticated"); return data.user; }
async function authorizeWorkspace(userId: string, workspaceId: string) { if (!workspaceId) throw new Error("workspace_id is required"); const { data, error } = await admin.from("workspace_members").select("role,is_active").eq("workspace_id", workspaceId).eq("user_id", userId).eq("is_active", true).maybeSingle(); if (error) throw error; if (!data) throw new Error("You do not have access to this workspace"); if (!["owner", "admin"].includes(String(data.role))) throw new Error("Owner or admin permission is required to connect a payment provider"); return data; }
async function settingsFor(workspaceId: string) { const { data, error } = await admin.from("workspace_settings").select("operational_settings,payment_provider").eq("workspace_id", workspaceId).maybeSingle(); if (error) throw error; if (!data) throw new Error("Workspace settings not found"); return data; }
async function updateOperational(workspaceId: string, patch: Record<string, unknown>, paymentProvider?: "stripe" | "square") { const settings = await settingsFor(workspaceId); const current = settings.operational_settings && typeof settings.operational_settings === "object" && !Array.isArray(settings.operational_settings) ? settings.operational_settings as Record<string, unknown> : {}; const update: Record<string, unknown> = { operational_settings: { ...current, ...patch }, updated_at: new Date().toISOString() }; if (paymentProvider) update.payment_provider = paymentProvider; const { error } = await admin.from("workspace_settings").update(update).eq("workspace_id", workspaceId); if (error) throw error; }
async function saveConnection(workspaceId: string, userId: string, provider: "stripe" | "square", externalAccountId: string, metadata: Record<string, unknown>, scopes: string[] = []) { const now = new Date().toISOString(); const { error } = await admin.from("provider_connections").upsert({ workspace_id: workspaceId, provider, external_account_id: externalAccountId, status: "connected", scopes, metadata, created_by: userId, last_synced_at: now, updated_at: now }, { onConflict: "workspace_id,provider" }); if (error) throw error; }

async function stripeRequest(path: string, init: RequestInit = {}) { if (!STRIPE_SECRET_KEY) throw new Error("Stripe server credential is not configured"); const headers = new Headers(init.headers); headers.set("authorization", `Bearer ${STRIPE_SECRET_KEY}`); if (init.body) headers.set("content-type", "application/x-www-form-urlencoded"); const response = await fetch(`https://api.stripe.com/v1/${path}`, { ...init, headers }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data?.error?.message || `Stripe API request failed (${response.status})`); return data as Record<string, any>; }
async function persistStripe(workspaceId: string, userId: string, account: Record<string, any>) { const accountId = String(account.id || ""); if (!accountId) throw new Error("Stripe did not return an account id"); const charges = account.charges_enabled === true; const payouts = account.payouts_enabled === true; const details = account.details_submitted === true; await saveConnection(workspaceId, userId, "stripe", accountId, { charges_enabled: charges, payouts_enabled: payouts, details_submitted: details, business_profile: account.business_profile?.name ?? null }); await updateOperational(workspaceId, { stripe_payment_mode: "connect", stripe_account_id: accountId, stripe_account_status: charges && payouts ? "active" : "restricted", stripe_charges_enabled: charges, stripe_payouts_enabled: payouts, stripe_details_submitted: details }, "stripe"); return { connected: true, account_id: accountId, charges_enabled: charges, payouts_enabled: payouts, details_submitted: details };
async function stripeInitiate(userId: string, workspaceId: string) {
  const state = await makeState(userId, workspaceId, "stripe");
  if (STRIPE_CONNECT_CLIENT_ID) {
    const params = new URLSearchParams({ response_type: "code", client_id: STRIPE_CONNECT_CLIENT_ID, scope: "read_write", state, redirect_uri: STRIPE_CONNECT_REDIRECT_URI });
    return { url: `https://connect.stripe.com/oauth/authorize?${params}`, mode: "oauth" };
  }
  const settings = await settingsFor(workspaceId); const op = settings.operational_settings && typeof settings.operational_settings === "object" && !Array.isArray(settings.operational_settings) ? settings.operational_settings as Record<string, unknown> : {}; let accountId = typeof op.stripe_account_id === "string" ? op.stripe_account_id : "";
  if (accountId) {
    try { await stripeRequest(`accounts/${encodeURIComponent(accountId)}`); } catch { throw new Error("The Stripe account stored for this workspace is not accessible to the configured Stripe platform. Reconnect Stripe with the correct platform/OAuth credentials."); }
  } else {
    const account = await stripeRequest("accounts", { method: "POST", body: new URLSearchParams({ type: "standard", "metadata[workspace_id]": workspaceId }) }); accountId = String(account.id || "");
  }
  const link = await stripeRequest("account_links", { method: "POST", body: new URLSearchParams({ account: accountId, type: "account_onboarding", refresh_url: "https://servicewriter.xyz/settings?stripe_refresh=true", return_url: "https://servicewriter.xyz/settings?stripe_success=true" }) });
  return { url: link.url, mode: "account_link", account_id: accountId };
}
async function stripeCallback(userId: string, workspaceId: string, code: string, state: string) { if (!STRIPE_CONNECT_CLIENT_ID) throw new Error("Stripe OAuth client id is not configured"); if (!(await verifyState(state, userId, workspaceId, "stripe"))) throw new Error("Invalid or expired Stripe OAuth state"); if (!code) throw new Error("Stripe authorization code is missing"); if (!STRIPE_SECRET_KEY) throw new Error("Stripe server credential is not configured"); const response = await fetch("https://connect.stripe.com/oauth/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_secret: STRIPE_SECRET_KEY, code, grant_type: "authorization_code" }) }); const token = await response.json().catch(() => ({})); if (!response.ok) throw new Error(token?.error_description || token?.error || "Stripe OAuth exchange failed"); const accountId = String(token.stripe_user_id || ""); const account = await stripeRequest(`accounts/${encodeURIComponent(accountId)}`); return persistStripe(workspaceId, userId, account); }
async function stripeRefresh(userId: string, workspaceId: string) { const settings = await settingsFor(workspaceId); const op = settings.operational_settings && typeof settings.operational_settings === "object" && !Array.isArray(settings.operational_settings) ? settings.operational_settings as Record<string, unknown> : {}; const accountId = typeof op.stripe_account_id === "string" ? op.stripe_account_id : ""; if (!accountId) return { connected: false }; const account = await stripeRequest(`accounts/${encodeURIComponent(accountId)}`); return persistStripe(workspaceId, userId, account); }

const squareBase = SQUARE_ENVIRONMENT === "sandbox" ? "https://connect.squareupsandbox.com" : "https://connect.squareup.com";
const squareApi = SQUARE_ENVIRONMENT === "sandbox" ? "https://connect.squareupsandbox.com" : "https://connect.squareup.com";
async function squareInitiate(userId: string, workspaceId: string) { if (!SQUARE_APPLICATION_ID || !SQUARE_APPLICATION_SECRET) throw new Error("Square OAuth is not configured on the Service Writer server"); const state = await makeState(userId, workspaceId, "square"); const params = new URLSearchParams({ client_id: SQUARE_APPLICATION_ID, scope: "MERCHANT_PROFILE_READ PAYMENTS_READ PAYMENTS_WRITE ORDERS_READ ORDERS_WRITE", session: "false", state }); return { url: `${squareBase}/oauth2/authorize?${params}`, state }; }
async function squareCallback(userId: string, workspaceId: string, code: string, state: string) { if (!SQUARE_APPLICATION_ID || !SQUARE_APPLICATION_SECRET) throw new Error("Square OAuth is not configured on the Service Writer server"); if (!(await verifyState(state, userId, workspaceId, "square"))) throw new Error("Invalid or expired Square OAuth state"); if (!code) throw new Error("Square authorization code is missing"); const response = await fetch(`${squareApi}/oauth2/token`, { method: "POST", headers: { "content-type": "application/json", "Square-Version": "2026-01-22" }, body: JSON.stringify({ client_id: SQUARE_APPLICATION_ID, client_secret: SQUARE_APPLICATION_SECRET, code, grant_type: "authorization_code", redirect_uri: SQUARE_REDIRECT_URI }) }); const token = await response.json().catch(() => ({})); if (!response.ok) throw new Error(token?.message || token?.errors?.[0]?.detail || "Square OAuth exchange failed"); const accessToken = String(token.access_token || ""); const merchantId = String(token.merchant_id || ""); if (!accessToken || !merchantId) throw new Error("Square did not return merchant authorization"); const locationsResponse = await fetch(`${squareApi}/v2/locations`, { headers: { authorization: `Bearer ${accessToken}`, "Square-Version": "2026-01-22" } }); const locationsData = await locationsResponse.json().catch(() => ({})); if (!locationsResponse.ok) throw new Error(locationsData?.errors?.[0]?.detail || "Unable to read Square locations"); const location = (locationsData.locations ?? []).find((item: Record<string, unknown>) => item.status === "ACTIVE") ?? (locationsData.locations ?? [])[0]; const locationId = location?.id ? String(location.id) : null; const now = new Date().toISOString(); const { error: secretError } = await admin.from("provider_connection_secrets").upsert({ workspace_id: workspaceId, provider: "square", access_token_encrypted: await encrypt(accessToken), refresh_token_encrypted: await encrypt(token.refresh_token ? String(token.refresh_token) : null), expires_at: token.expires_at ? String(token.expires_at) : null, updated_at: now }, { onConflict: "workspace_id,provider" }); if (secretError) throw secretError; await saveConnection(workspaceId, userId, "square", merchantId, { location_id: locationId, location_name: location?.name ?? null }, ["MERCHANT_PROFILE_READ", "PAYMENTS_READ", "PAYMENTS_WRITE", "ORDERS_READ", "ORDERS_WRITE"]); await updateOperational(workspaceId, { square_merchant_id: merchantId, square_location_id: locationId, square_charges_enabled: Boolean(locationId), square_onboarding_complete: Boolean(locationId), square_account_status: locationId ? "active" : "restricted" }, "square"); return { connected: true, merchant_id: merchantId, location_id: locationId, charges_enabled: Boolean(locationId) }; }

async function handle(request: Request) {
  if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
  if (request.method !== "POST") return json({ error: "Method Not Allowed" }, 405);
  const user = await userFromRequest(request); const body = await request.json().catch(() => ({})) as Record<string, unknown>; const workspaceId = String(body.workspace_id ?? ""); const provider = String(body.provider ?? ""); const mode = String(body.mode ?? "initiate"); await authorizeWorkspace(user.id, workspaceId);
  if (provider === "stripe") {
    if (mode === "initiate") return json(await stripeInitiate(user.id, workspaceId));
    if (mode === "callback") return json(await stripeCallback(user.id, workspaceId, String(body.code ?? ""), String(body.state ?? "")));
    if (mode === "status") return json(await stripeRefresh(user.id, workspaceId));
  }
  if (provider === "square") {
    if (mode === "initiate") return json(await squareInitiate(user.id, workspaceId));
    if (mode === "callback") return json(await squareCallback(user.id, workspaceId, String(body.code ?? ""), String(body.state ?? "")));
  }
  return json({ error: "Unsupported payment provider operation" }, 400);
}

Deno.serve(async request => { try { return await handle(request); } catch (error) { const message = error instanceof Error ? error.message : "Payment provider connection failed"; return json({ error: message }, /not authenticated/i.test(message) ? 401 : /permission|access/i.test(message) ? 403 : 400); } });
