create index if not exists idx_account_import_records_workspace_id on public.account_import_records(workspace_id);
create index if not exists idx_customers_created_by on public.customers(created_by);
create index if not exists idx_appointments_assigned_user_id on public.appointments(assigned_user_id);
create index if not exists idx_appointments_created_by on public.appointments(created_by);
create index if not exists idx_appointments_workspace_location on public.appointments(workspace_id, location_id);
create index if not exists idx_service_records_completed_by on public.service_records(completed_by);
create index if not exists idx_service_records_work_order_id on public.service_records(work_order_id);
create index if not exists idx_service_records_workspace_quote on public.service_records(workspace_id, quote_id);
create index if not exists idx_message_logs_created_by on public.message_logs(created_by);
create index if not exists idx_message_logs_provider_connection on public.message_logs(provider_connection_id);
create index if not exists idx_dispatch_events_appointment_id on public.dispatch_events(appointment_id);
create index if not exists idx_dispatch_events_work_order_id on public.dispatch_events(work_order_id);
create index if not exists idx_dispatch_events_performed_by on public.dispatch_events(performed_by);
create index if not exists idx_message_delivery_events_workspace on public.message_delivery_events(workspace_id);
create index if not exists idx_message_delivery_events_workspace_log on public.message_delivery_events(workspace_id, message_log_id);
create index if not exists idx_webhook_events_workspace on public.webhook_events(workspace_id);
create index if not exists idx_work_order_assignments_user_id on public.work_order_assignments(user_id);
create index if not exists idx_work_order_assignments_assigned_by on public.work_order_assignments(assigned_by);
create index if not exists idx_work_order_events_actor on public.work_order_events(actor_user_id);
create index if not exists idx_work_order_events_workspace_order on public.work_order_events(workspace_id, work_order_id);
create index if not exists idx_work_order_items_workspace_order on public.work_order_items(workspace_id, work_order_id);
create index if not exists idx_work_order_items_workspace_service on public.work_order_items(workspace_id, service_catalog_id);
create index if not exists idx_work_orders_created_by on public.work_orders(created_by);
create index if not exists idx_work_orders_workspace_appointment on public.work_orders(workspace_id, appointment_id);
create index if not exists idx_work_orders_workspace_customer on public.work_orders(workspace_id, customer_id);
create index if not exists idx_work_orders_workspace_location on public.work_orders(workspace_id, location_id);
create index if not exists idx_work_orders_workspace_vehicle on public.work_orders(workspace_id, vehicle_id);
