// This file is automatically generated. Do not edit it directly.
import { createClient, processLock, type SupabaseClient } from '@supabase/supabase-js';
import type { Database as LegacyDatabase } from './types';
import type { Database as ProductionDatabase } from './types.production';
import { generateCorrelationId, reportClientError } from '@/lib/client-observability';

// ─────────────────────────────────────────────────────────────────────────────
// Single canonical backend
// ─────────────────────────────────────────────────────────────────────────────
// Auth, operational data, functions, storage and realtime MUST resolve to the
// same Supabase project. Production may receive NEXT_PUBLIC_* values from the
// deployment environment, but it must never fall back to a disconnected local
// Supabase instance when those variables are absent from a build.
const CANONICAL_SUPABASE_PROJECT_ID = 'rjfbrfognxqkyhdrpibx';
const CANONICAL_SUPABASE_URL = `https://${CANONICAL_SUPABASE_PROJECT_ID}.supabase.co`;
const CANONICAL_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_-TAyW6MChnKyB_0yICU79g_miXrX3xy';

const NEXT_PUBLIC_SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || '';
const NEXT_PUBLIC_SUPABASE_PROJECT_ID = process.env.NEXT_PUBLIC_SUPABASE_PROJECT_ID || '';

function projectRefFromAnonKey(key: string | undefined): string | null {
  if (!key || key.startsWith('sb_publishable_')) return null;
  try {
    const body = key.split('.')[1];
    if (!body) return null;
    const decode = typeof globalThis.atob === 'function' ? globalThis.atob : null;
    if (!decode) return null;
    const payload = JSON.parse(decode(body.replace(/-/g, '+').replace(/_/g, '/')));
    return typeof payload?.ref === 'string' ? payload.ref : null;
  } catch {
    return null;
  }
}

const SUPABASE_URL = (NEXT_PUBLIC_SUPABASE_URL.trim() || CANONICAL_SUPABASE_URL).replace(/\/$/, '');
const SUPABASE_PUBLISHABLE_KEY = NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY.trim() || CANONICAL_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_PROJECT_ID = NEXT_PUBLIC_SUPABASE_PROJECT_ID.trim() || CANONICAL_SUPABASE_PROJECT_ID;
const CLIENT_SUPABASE_URL = SUPABASE_URL;
const CLIENT_SUPABASE_KEY = SUPABASE_PUBLISHABLE_KEY;

// Guard: the resolved URL must be the canonical production project. Publishable
// keys are opaque and do not encode their project ref, so the URL/project-id
// invariant is the reliable browser-side project guard for modern keys.
{
  const urlRef = CLIENT_SUPABASE_URL.replace(/^https?:\/\//, '').split('.')[0];
  const legacyKeyRef = projectRefFromAnonKey(SUPABASE_PUBLISHABLE_KEY);
  if (urlRef !== CANONICAL_SUPABASE_PROJECT_ID || SUPABASE_PROJECT_ID !== CANONICAL_SUPABASE_PROJECT_ID) {
    throw new Error(
      `[supabase] Backend misconfiguration: expected canonical project "${CANONICAL_SUPABASE_PROJECT_ID}" but resolved URL/project "${urlRef}/${SUPABASE_PROJECT_ID}".`,
    );
  }
  if (legacyKeyRef && legacyKeyRef !== urlRef) {
    throw new Error(
      `[supabase] Backend misconfiguration: URL points at project "${urlRef}" but the legacy publishable key belongs to project "${legacyKeyRef}".`,
    );
  }
}

const isBrowser = typeof window !== "undefined" && typeof window.localStorage !== "undefined";
const INTERACTIVE_AUTH_REQUEST_TIMEOUT_MS = 45_000;

function isInteractiveAuthRequest(url: string): boolean {
  if (!url.includes('/auth/v1/')) return false;
  if (/grant_type=refresh_token/.test(url)) return false;
  if (/\/auth\/v1\/(user|session|logout)/.test(url)) return false;
  return (
    /grant_type=password/.test(url) ||
    /\/auth\/v1\/(signup|otp|recover|magiclink|verify|resend)/.test(url)
  );
}

const tracedFetch: typeof fetch = async (input: RequestInfo | URL, init: RequestInit = {}) => {
  const requestUrl = typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;
  const isAuthRequest = isInteractiveAuthRequest(requestUrl);
  const isEdgeFunctionRequest = requestUrl.includes('/functions/v1/');
  const isRestRequest = requestUrl.includes('/rest/v1/');

  let correlationId: string | null = null;
  let accessToken: string | null = null;
  let userId: string | null = null;

  const inputHeaders = typeof input === 'object' && 'headers' in input ? input.headers : undefined;
  const headers = new Headers(init.headers ?? inputHeaders);

  const authHeader = headers.get('Authorization');
  if (authHeader?.toLowerCase().startsWith('bearer ')) {
    accessToken = authHeader.slice('bearer '.length).trim();
  }

  if (accessToken) {
    try {
      const tokenBody = accessToken.split('.')[1];
      if (tokenBody) {
        const decode = typeof globalThis.atob === 'function' ? globalThis.atob : null;
        if (decode) {
          const payload = JSON.parse(decode(tokenBody.replace(/-/g, '+').replace(/_/g, '/')));
          if (payload?.sub && typeof payload.sub === 'string') userId = payload.sub;
        }
      }
    } catch {
      // best-effort observability only
    }
  }

  if (isEdgeFunctionRequest) {
    correlationId = generateCorrelationId('edge');
    headers.set('x-correlation-id', correlationId);
  }

  let authTimeoutId: ReturnType<typeof setTimeout> | undefined;
  let authAbortController: AbortController | undefined;

  try {
    const requestInit: RequestInit = { ...init, headers };

    if (isAuthRequest && !init.signal && typeof AbortController !== "undefined") {
      authAbortController = new AbortController();
      authTimeoutId = setTimeout(() => authAbortController?.abort(), INTERACTIVE_AUTH_REQUEST_TIMEOUT_MS);
      requestInit.signal = authAbortController.signal;
    }

    const response = await fetch(input, requestInit);
    const isTelemetryRequest = requestUrl.includes('/rest/v1/client_error_events');
    if ((isEdgeFunctionRequest || isRestRequest) && !isTelemetryRequest && !response.ok) {
      const endpoint = (() => {
        const edgeMarker = '/functions/v1/';
        const restMarker = '/rest/v1/';
        const edgeIdx = requestUrl.indexOf(edgeMarker);
        const restIdx = requestUrl.indexOf(restMarker);
        if (edgeIdx >= 0) return requestUrl.slice(edgeIdx + edgeMarker.length).split('?')[0];
        if (restIdx >= 0) return requestUrl.slice(restIdx + restMarker.length).split('?')[0];
        return requestUrl;
      })();

      void reportClientError({
        supabaseUrl: SUPABASE_URL,
        publishableKey: SUPABASE_PUBLISHABLE_KEY,
        accessToken,
        userId,
        correlationId,
        endpoint,
        statusCode: response.status,
        severity: response.status >= 500 ? 'critical' : 'warning',
        errorMessage: `${isEdgeFunctionRequest ? 'Edge function' : 'REST'} call failed with HTTP ${response.status}`,
        context: { method: init.method || 'GET', statusText: response.statusText },
      });
    }

    return response;
  } catch (error) {
    const isTelemetryRequest = requestUrl.includes('/rest/v1/client_error_events');
    if ((isEdgeFunctionRequest || isRestRequest) && !isTelemetryRequest) {
      const endpoint = (() => {
        const edgeMarker = '/functions/v1/';
        const restMarker = '/rest/v1/';
        const edgeIdx = requestUrl.indexOf(edgeMarker);
        const restIdx = requestUrl.indexOf(restMarker);
        if (edgeIdx >= 0) return requestUrl.slice(edgeIdx + edgeMarker.length).split('?')[0];
        if (restIdx >= 0) return requestUrl.slice(restIdx + restMarker.length).split('?')[0];
        return requestUrl;
      })();

      void reportClientError({
        supabaseUrl: SUPABASE_URL,
        publishableKey: SUPABASE_PUBLISHABLE_KEY,
        accessToken,
        userId,
        correlationId,
        endpoint,
        severity: 'error',
        errorMessage: error instanceof Error ? error.message : 'Network failure',
        context: { method: init.method || 'GET' },
      });
    }
    throw error;
  } finally {
    if (authTimeoutId !== undefined) clearTimeout(authTimeoutId);
  }
};

export const productionSupabase = createClient<ProductionDatabase>(CLIENT_SUPABASE_URL, CLIENT_SUPABASE_KEY, {
  auth: {
    storage: isBrowser ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    lock: processLock,
  },
  global: { fetch: tracedFetch },
});

export const supabase = productionSupabase as unknown as SupabaseClient<LegacyDatabase>;
export const authSupabase = supabase;
export const SUPABASE_URL_RESOLVED: string = SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY_RESOLVED: string = SUPABASE_PUBLISHABLE_KEY;
export const SUPABASE_PROJECT_ID_RESOLVED: string = SUPABASE_PROJECT_ID;
export const AUTH_SUPABASE_URL_RESOLVED: string = SUPABASE_URL;
export const AUTH_SUPABASE_PUBLISHABLE_KEY_RESOLVED: string = SUPABASE_PUBLISHABLE_KEY;
export const AUTH_SUPABASE_PROJECT_ID_RESOLVED: string = SUPABASE_PROJECT_ID;
