// This file is automatically generated. Do not edit it directly.
import { createClient, processLock, type SupabaseClient } from '@supabase/supabase-js';
import type { Database as LegacyDatabase } from './types';
import type { Database as ProductionDatabase } from './types.production';
import { generateCorrelationId, reportClientError } from '@/lib/client-observability';

// ─────────────────────────────────────────────────────────────────────────────
// Single canonical backend
// ─────────────────────────────────────────────────────────────────────────────
// Auth, operational data, functions, storage and realtime MUST resolve to the
// same Supabase project. Previously auth was pinned to one project while REST
// pointed at another, so every data call carried a token the data project could
// not verify -> `401 PGRST301 "No suitable key was found to decode the JWT"`.
//
// The project is resolved exclusively from the build environment (Next.js injects
// NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY / NEXT_PUBLIC_SUPABASE_PROJECT_ID).
// No publishable key is ever embedded in this file: a stale hard-coded key is
// how production once shipped an invalid anon JWT, and rewriting this source at
// build time is how it once shipped a malformed client bundle.
// These direct references are intentional: Next.js statically inlines
// `NEXT_PUBLIC_*` variables into the browser bundle. Reading `process.env`
// through a dynamically typed object leaves the client with undefined values
// in production and silently routes auth to disconnected development mode.
const NEXT_PUBLIC_SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || '';
const NEXT_PUBLIC_SUPABASE_PROJECT_ID = process.env.NEXT_PUBLIC_SUPABASE_PROJECT_ID || '';
const FALLBACK_PROJECT_ID = NEXT_PUBLIC_SUPABASE_PROJECT_ID;

function projectRefFromAnonKey(key: string | undefined): string | null {
  if (!key) return null;
  try {
    const body = key.split('.')[1];
    if (!body) return null;
    const decode = typeof globalThis.atob === 'function' ? globalThis.atob : null;
    if (!decode) return null;
    const payload = JSON.parse(decode(body.replace(/-/g, '+').replace(/_/g, '/')));
    return typeof payload?.ref === 'string' ? payload.ref : null;
  } catch {
    return null;
  }
}

const RAW_SUPABASE_URL = NEXT_PUBLIC_SUPABASE_URL.trim();
const SUPABASE_URL = (
  RAW_SUPABASE_URL || (FALLBACK_PROJECT_ID ? `https://${FALLBACK_PROJECT_ID}.supabase.co` : '')
).replace(/\/$/, '');
const SUPABASE_PUBLISHABLE_KEY = NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY.trim();
const SUPABASE_CONFIGURED = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
const CLIENT_SUPABASE_URL = SUPABASE_URL || 'http://127.0.0.1:54321';
const CLIENT_SUPABASE_KEY = SUPABASE_PUBLISHABLE_KEY || 'local-development-key';

if (!SUPABASE_CONFIGURED) {
  console.warn('[supabase] Backend is not configured. UI is running in disconnected development mode; configure NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY before using authenticated data flows.');
}

const SUPABASE_PROJECT_ID =
  projectRefFromAnonKey(SUPABASE_PUBLISHABLE_KEY) ||
  NEXT_PUBLIC_SUPABASE_PROJECT_ID ||
  FALLBACK_PROJECT_ID;

// Guard: the URL host and the publishable key must belong to the same project.
// This is the exact class of misconfiguration that caused the auth/data split.
{
  const urlRef = CLIENT_SUPABASE_URL.replace(/^https?:\/\//, '').split('.')[0];
  const keyRef = projectRefFromAnonKey(SUPABASE_PUBLISHABLE_KEY);
  if (keyRef && urlRef && keyRef !== urlRef) {
    throw new Error(
      `[supabase] Backend misconfiguration: URL points at project "${urlRef}" but the publishable key ` +
        `belongs to project "${keyRef}". Auth and data must use the same project.`,
    );
  }
}


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof window !== "undefined" && typeof window.localStorage !== "undefined";
// The command layer (`signInWithPassword` → `withOperationTimeout`) owns the
// user-facing sign-in deadline. This transport abort is only a last-resort
// backstop, so it must sit ABOVE that budget — otherwise it fires first and the
// clearer "request timed out" path never runs.
const INTERACTIVE_AUTH_REQUEST_TIMEOUT_MS = 45_000;

/**
 * Only *interactive* credential submissions may be hard-aborted. Aborting the
 * background token refresh (`grant_type=refresh_token`) or the boot-time
 * session/user check makes the SDK treat the session as unrecoverable: it drops
 * the stored session, the auth gate never resolves, and every RLS-scoped query
 * returns nothing. That regression is what this predicate prevents.
 */
function isInteractiveAuthRequest(url: string): boolean {
  if (!url.includes('/auth/v1/')) return false;
  if (/grant_type=refresh_token/.test(url)) return false;
  if (/\/auth\/v1\/(user|session|logout)/.test(url)) return false;
  return (
    /grant_type=password/.test(url) ||
    /\/auth\/v1\/(signup|otp|recover|magiclink|verify|resend)/.test(url)
  );
}

const tracedFetch: typeof fetch = async (input: RequestInfo | URL, init: RequestInit = {}) => {
  const requestUrl = typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;
  const isAuthRequest = isInteractiveAuthRequest(requestUrl);
  const isEdgeFunctionRequest = requestUrl.includes('/functions/v1/');
  const isRestRequest = requestUrl.includes('/rest/v1/');

  let correlationId: string | null = null;
  let accessToken: string | null = null;
  let userId: string | null = null;

  const inputHeaders = typeof input === 'object' && 'headers' in input ? input.headers : undefined;
  const headers = new Headers(init.headers ?? inputHeaders);

  // Single-project client: supabase-js already attaches the session token.
  // We only read it here for observability/error reporting.
  const authHeader = headers.get('Authorization');
  if (authHeader?.toLowerCase().startsWith('bearer ')) {
    accessToken = authHeader.slice('bearer '.length).trim();
  }


  if (accessToken) {
    try {
      const tokenBody = accessToken.split('.')[1];
      if (tokenBody) {
        const decode = typeof globalThis.atob === 'function' ? globalThis.atob : null;
        if (decode) {
          const payload = JSON.parse(decode(tokenBody.replace(/-/g, '+').replace(/_/g, '/')));
          if (payload?.sub && typeof payload.sub === 'string') {
            userId = payload.sub;
          }
        }
      }
    } catch {
      // best-effort only
    }
  }

  if (isEdgeFunctionRequest) {
    correlationId = generateCorrelationId('edge');
    headers.set('x-correlation-id', correlationId);
  }

  let authTimeoutId: ReturnType<typeof setTimeout> | undefined;
  let authAbortController: AbortController | undefined;

  try {
    const requestInit: RequestInit = {
      ...init,
      headers,
    };

    // Interactive credential submissions are user-blocking: abort a hung Auth
    // transport so the form can be re-enabled. Background refresh and session
    // bootstrap are deliberately NOT bounded here.
    if (isAuthRequest && !init.signal && typeof AbortController !== "undefined") {
      authAbortController = new AbortController();
      authTimeoutId = setTimeout(
        () => authAbortController?.abort(),
        INTERACTIVE_AUTH_REQUEST_TIMEOUT_MS,
      );
      requestInit.signal = authAbortController.signal;
    }

    const response = await fetch(input, requestInit);

    const isTelemetryRequest = requestUrl.includes('/rest/v1/client_error_events');
    if ((isEdgeFunctionRequest || isRestRequest) && !isTelemetryRequest && !response.ok) {
      const endpoint = (() => {
        const edgeMarker = '/functions/v1/';
        const restMarker = '/rest/v1/';
        const edgeIdx = requestUrl.indexOf(edgeMarker);
        const restIdx = requestUrl.indexOf(restMarker);
        if (edgeIdx >= 0) return requestUrl.slice(edgeIdx + edgeMarker.length).split('?')[0];
        if (restIdx >= 0) return requestUrl.slice(restIdx + restMarker.length).split('?')[0];
        return requestUrl;
      })();

      void reportClientError({
        supabaseUrl: SUPABASE_URL,
        publishableKey: SUPABASE_PUBLISHABLE_KEY,
        accessToken,
        userId,
        correlationId,
        endpoint,
        statusCode: response.status,
        severity: response.status >= 500 ? 'critical' : 'warning',
        errorMessage: `${isEdgeFunctionRequest ? 'Edge function' : 'REST'} call failed with HTTP ${response.status}`,
        context: {
          method: init.method || 'GET',
          statusText: response.statusText,
        },
      });
    }

    return response;
  } catch (error) {
    const isTelemetryRequest = requestUrl.includes('/rest/v1/client_error_events');
    if ((isEdgeFunctionRequest || isRestRequest) && !isTelemetryRequest) {
      const endpoint = (() => {
        const edgeMarker = '/functions/v1/';
        const restMarker = '/rest/v1/';
        const edgeIdx = requestUrl.indexOf(edgeMarker);
        const restIdx = requestUrl.indexOf(restMarker);
        if (edgeIdx >= 0) return requestUrl.slice(edgeIdx + edgeMarker.length).split('?')[0];
        if (restIdx >= 0) return requestUrl.slice(restIdx + restMarker.length).split('?')[0];
        return requestUrl;
      })();

      void reportClientError({
        supabaseUrl: SUPABASE_URL,
        publishableKey: SUPABASE_PUBLISHABLE_KEY,
        accessToken,
        userId,
        correlationId,
        endpoint,
        severity: 'error',
        errorMessage: error instanceof Error ? error.message : 'Network failure',
        context: {
          method: init.method || 'GET',
        },
      });
    }
    throw error;
  } finally {
    if (authTimeoutId !== undefined) clearTimeout(authTimeoutId);
  }
};

// One runtime client, with two explicit compile-time schema views. New canonical
// workspace code uses the schema generated from production; legacy modules keep
// their checked-in compatibility schema while they are migrated or retired.
export const productionSupabase = createClient<ProductionDatabase>(CLIENT_SUPABASE_URL, CLIENT_SUPABASE_KEY, {
  auth: {
    storage: isBrowser ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    // Serializes token refreshes across tabs. Without it two tabs refresh at
    // once, the second presents an already-rotated refresh token, and the SDK
    // discards the session — the app then looks signed out with empty lists.
    lock: processLock,
  },
  global: {
    fetch: tracedFetch,
  },
});

export const supabase = productionSupabase as unknown as SupabaseClient<LegacyDatabase>;

/**
 * Back-compat alias. Auth used to live on a separate project/client; it is now
 * the exact same client as `supabase`. Kept so existing `authSupabase.auth.*`
 * call sites keep working.
 */
export const authSupabase = supabase;

/**
 * Canonical Supabase URL for the active build, resolved from the environment.
 * Consumers that construct edge-function URLs must import this instead of
 * reading `process.env.NEXT_PUBLIC_SUPABASE_URL` directly.
 */
export const SUPABASE_URL_RESOLVED: string = SUPABASE_URL;

/** Canonical publishable key for the active backend client. */
export const SUPABASE_PUBLISHABLE_KEY_RESOLVED: string = SUPABASE_PUBLISHABLE_KEY;

/** Project ref for the resolved Supabase URL. */
export const SUPABASE_PROJECT_ID_RESOLVED: string = SUPABASE_PROJECT_ID;

/** Auth now shares the single backend; these aliases exist for back-compat. */
export const AUTH_SUPABASE_URL_RESOLVED: string = SUPABASE_URL;
export const AUTH_SUPABASE_PUBLISHABLE_KEY_RESOLVED: string = SUPABASE_PUBLISHABLE_KEY;
export const AUTH_SUPABASE_PROJECT_ID_RESOLVED: string = SUPABASE_PROJECT_ID;
