import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";

const ROOT_SOURCES=[["AGENTS.md","buildos"],["CLAUDE.md","claude"],["GEMINI.md","gemini"],[".cursorrules","cursor"],[".windsurfrules","windsurf"],[".github/copilot-instructions.md","github-copilot"]];
const readJson=path=>JSON.parse(readFileSync(path,"utf8"));
const sha256=text=>createHash("sha256").update(text).digest("hex");
const posix=p=>p.split(sep).join("/");
const extractRules=content=>content.split(/\r?\n/).map(x=>x.trim()).filter(x=>x&&(/^(?:[-*]|\d+\.)\s+/.test(x)||/\b(must|never|always|do not|don't|required|before|after|bypass|deploy|test|ship|publish|release|verification|quality gate|blocker|credential|api key|token|password|secret|environment variable)\b/i.test(x))).slice(0,200);
const denied=text=>/\b(never|do not|don't|must not|should not|skip)\b/i.test(text);
const RELEASE="(?:deploy(?:ment|ing)?|ship(?:ping)?|publish(?:ing)?|release|go live|live)";
const VERIFY="(?:test(?:s|ing)?|test suite|verification(?: suite)?|quality check(?:s)?|quality gate(?:s)?)";

function walkFiles(root,dir,accept,out=[]){if(!existsSync(dir))return out;for(const entry of readdirSync(dir,{withFileTypes:true})){const full=join(dir,entry.name);if(entry.isDirectory())walkFiles(root,full,accept,out);else if(entry.isFile()&&accept(entry.name,full))out.push(posix(relative(root,full)))}return out}
function frontmatterScope(content){const block=content.match(/^---\s*\r?\n([\s\S]*?)\r?\n---/);if(!block)return null;const line=block[1].split(/\r?\n/).find(x=>/^\s*(applyTo|globs?)\s*:/.test(x));if(!line)return null;const raw=line.replace(/^\s*(applyTo|globs?)\s*:\s*/,"").trim().replace(/^['"]|['"]$/g,"");return raw||null}
function inferScope(path,content){const explicit=frontmatterScope(content);if(explicit)return explicit;if(path!=="AGENTS.md"&&path.endsWith("/AGENTS.md")){const dir=path.slice(0,-"/AGENTS.md".length);return`${dir}/**`}return"repository"}
function sourceAgent(path){if(path==="AGENTS.md")return"buildos";if(path.endsWith("/AGENTS.md"))return"agents";if(path.startsWith(".github/instructions/"))return"github-copilot";if(path.startsWith(".cursor/rules/"))return"cursor";if(path.startsWith(".windsurf/rules/"))return"windsurf";return ROOT_SOURCES.find(([p])=>p===path)?.[1]||"unknown"}
function discoverSourcePaths(cwd){const paths=new Set(ROOT_SOURCES.filter(([path])=>existsSync(join(cwd,path))).map(([path])=>path));for(const p of walkFiles(cwd,join(cwd,".github","instructions"),name=>name.endsWith(".instructions.md")))paths.add(p);for(const p of walkFiles(cwd,join(cwd,".cursor","rules"),name=>/\.(md|mdc)$/i.test(name)))paths.add(p);for(const p of walkFiles(cwd,join(cwd,".windsurf","rules"),name=>/\.(md|mdc)$/i.test(name)))paths.add(p);for(const p of walkFiles(cwd,cwd,(name,full)=>name==="AGENTS.md"&&!posix(relative(cwd,full)).startsWith("node_modules/")&&!posix(relative(cwd,full)).startsWith(".git/")))paths.add(p);return[...paths].sort()}
function globRegex(glob){let s=glob.trim().replace(/^['"]|['"]$/g,"").replace(/[.+^${}()|[\]\\]/g,"\\$&");s=s.replace(/\*\*/g,"\u0000").replace(/\*/g,"[^/]*").replace(/\?/g,"[^/]").replace(/\u0000/g,".*");return new RegExp(`^${s}$`)}
export function scopeApplies(scope,changedFiles,changedFilesKnown=true){if(scope==="repository")return true;if(!changedFilesKnown)return true;const globs=String(scope).split(",").map(x=>x.trim()).filter(Boolean);return changedFiles.some(file=>globs.some(glob=>globRegex(glob).test(posix(file))))}
function detectChangedFiles(cwd){try{const out=execFileSync("git",["diff-tree","--no-commit-id","--name-only","-r","HEAD"],{cwd,encoding:"utf8",stdio:["ignore","pipe","ignore"]}).trim();return{known:true,files:out?out.split(/\r?\n/).map(posix).filter(Boolean):[]}}catch{return{known:false,files:[]}}}

export function classifyPolicyRules(instruction){
  const text=instruction.toLowerCase(),results=[];
  const add=(topic,polarity)=>{if(!results.some(x=>x.topic===topic&&x.polarity===polarity))results.push({topic,polarity})};
  const negatedVerifyBeforeRelease=new RegExp(`\\b(?:never|do not|don't|must not|should not)\\b[^.]{0,100}${VERIFY}[^.]{0,120}\\bbefore\\b[^.]{0,120}${RELEASE}`),releaseFirst=new RegExp(`${RELEASE}[^.]{0,120}\\b(?:first|before)\\b[^.]{0,120}${VERIFY}|${VERIFY}[^.]{0,120}\\b(?:only )?after\\b[^.]{0,120}${RELEASE}`),verifyFirst=new RegExp(`${VERIFY}[^.]{0,120}\\b(?:before|prior to)\\b[^.]{0,120}${RELEASE}|\\b(?:do not|don't|never|must not)\\b[^.]{0,80}${RELEASE}[^.]{0,120}\\buntil\\b[^.]{0,120}${VERIFY}`);
  if(negatedVerifyBeforeRelease.test(text)||releaseFirst.test(text))add("tests-before-deploy","deny");else if(verifyFirst.test(text))add("tests-before-deploy","require");else if(/\b(test|tests|test suite)\b/.test(text)&&/\bbefore\b/.test(text)&&/\bdeploy(?:ment|ing)?\b/.test(text))add("tests-before-deploy",denied(text)?"deny":"require");
  if(/\b(failed|failing)\b[^.]{0,60}\b(quality )?gate\b[^.]{0,100}\b(stop|block|prevent)\b[^.]{0,80}(?:deploy|ship|publish|release|live)/.test(text)||/\bnever\b[^.]{0,80}\b(publish|ship|release|deploy)\b[^.]{0,80}\b(around|past)\b[^.]{0,80}\b(blocker|gate|failure)\b/.test(text))add("bypass-gate","deny");else if(/\b(ignore|disregard|override|work around|publish around|ship around)\b[^.]{0,100}\b(blocker|gate|failure|check)\b|\b(blocker|gate|failure|check)\b[^.]{0,100}\b(ignore|disregard|override|publish anyway|ship anyway)\b/.test(text))add("bypass-gate","allow");else if(/\bbypass\b/.test(text)&&/\bgate\b/.test(text))add("bypass-gate",denied(text)?"deny":"allow");
  if(/\buse\b/.test(text)&&/\bnpm\b/.test(text))add("use-npm",denied(text)?"deny":"require");
  const credential=/\b(api key(?:s)?|token(?:s)?|password(?:s)?|service credential(?:s)?|credential(?:s)?|secret(?:s)?)\b/.test(text),source=/\b(source|source file(?:s)?|code|repository|repo|committed|commit|hardcode|hard-coded|embed)\b/.test(text),safeStore=/\b(environment variable(?:s)?|secret store|secret manager|vault)\b/.test(text);
  if(credential&&source){if(/\b(put|place|store|keep|commit|hardcode|hard-code|embed|include)\b/.test(text)&&!denied(text))add("secrets-in-source","allow");if(denied(text)||safeStore)add("secrets-in-source","deny")}else if(credential&&safeStore)add("secrets-in-source","deny");
  return results
}
export function classifyPolicyRule(instruction){return classifyPolicyRules(instruction)[0]||null}

function canonicalStances(cwd,sources){
  const stances=new Map([["secrets-in-source","deny"]]);
  try{const cfg=readJson(join(cwd,"buildos.config.json")),verify=cfg.verify||[];if(verify.includes("test")&&(!verify.includes("build")||verify.indexOf("test")<verify.indexOf("build")))stances.set("tests-before-deploy","require")}catch{}
  if(existsSync(join(cwd,"package-lock.json")))stances.set("use-npm","require");else if(existsSync(join(cwd,"pnpm-lock.yaml"))||existsSync(join(cwd,"yarn.lock"))||existsSync(join(cwd,"bun.lock"))||existsSync(join(cwd,"bun.lockb")))stances.set("use-npm","deny");
  const buildos=sources.find(s=>s.path==="AGENTS.md"&&s.agent==="buildos");for(const instruction of buildos?.rules||[])for(const semantic of classifyPolicyRules(instruction)){if(semantic.topic!=="secrets-in-source")stances.set(semantic.topic,semantic.polarity)}
  return stances
}

export function analyzeAgentPolicy(cwd,options={}){const changed=Array.isArray(options.changedFiles)?{known:options.changedFilesKnown!==false,files:options.changedFiles.map(posix)}:detectChangedFiles(cwd);const sources=discoverSourcePaths(cwd).map(path=>{const content=readFileSync(join(cwd,path),"utf8"),agent=sourceAgent(path),scope=inferScope(path,content);return{agent,path,format:path.endsWith(".md")||path.endsWith(".mdc")?"markdown":"text",scope,active:scopeApplies(scope,changed.files,changed.known),contentHash:sha256(content),rules:extractRules(content)}}),canonical=canonicalStances(cwd,sources),rules=sources.flatMap(source=>source.rules.flatMap((instruction,index)=>{const semantics=classifyPolicyRules(instruction),assertions=semantics.length?semantics:[null];return assertions.map((semantic,n)=>({id:`${source.agent}:${source.path}:${index+1}:${n+1}`,sourceAgent:source.agent,sourcePath:source.path,instruction,scope:source.scope,active:source.active,enforcementLevel:source.path==="AGENTS.md"?"canonical":"imported",topic:semantic?.topic||null,polarity:semantic?.polarity||null,conflicts:[],resolution:null,provenance:{sourcePath:source.path,scope:source.scope,contentHash:source.contentHash}}))})),conflicts=[];for(let i=0;i<rules.length;i++)for(let j=i+1;j<rules.length;j++){const a=rules[i],b=rules[j];if(!a.topic||a.topic!==b.topic||!a.polarity||a.polarity===b.polarity)continue;const active=a.active&&b.active,cp=canonical.get(a.topic)||null,resolved=Boolean(cp),winner=resolved?(a.polarity===cp?a:b):null,loser=resolved?(winner===a?b:a):null,c={id:`conflict-${conflicts.length+1}`,topic:a.topic,active,scopes:[a.scope,b.scope],ruleIds:[a.id,b.id],canonicalPolarity:cp,resolved,resolution:resolved?"buildos-canonical-policy":null,winnerRuleId:winner?.id||null,overriddenRuleId:loser?.id||null};conflicts.push(c);a.conflicts.push(c.id);b.conflicts.push(c.id);if(resolved){winner.resolution="canonical";loser.resolution="overridden-by-buildos"}}for(const rule of rules){if(rule.enforcementLevel!=="imported"||!rule.topic||!rule.polarity)continue;const cp=canonical.get(rule.topic);if(cp&&cp!==rule.polarity&&!rule.conflicts.length){const c={id:`conflict-${conflicts.length+1}`,topic:rule.topic,active:rule.active,scopes:[rule.scope,"repository"],ruleIds:[rule.id],canonicalPolarity:cp,resolved:true,resolution:"buildos-canonical-policy",winnerRuleId:"buildos:invariant-or-repository-evidence",overriddenRuleId:rule.id};conflicts.push(c);rule.conflicts.push(c.id);rule.resolution="overridden-by-buildos"}}return{version:7,generatedAt:new Date().toISOString(),canonicalSource:"BuildOS",changedFiles:changed.files,changedFilesKnown:changed.known,sources,canonicalPolicy:Object.fromEntries(canonical),normalizedRules:rules,conflicts,activeConflicts:conflicts.filter(c=>c.active),unresolvedConflicts:conflicts.filter(c=>c.active&&!c.resolved)}}
export function validateAgentPolicy(cwd,options={}){const policy=analyzeAgentPolicy(cwd,options),path=join(cwd,".buildos/agent-policy.json");mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(policy,null,2)+"\n");if(policy.unresolvedConflicts.length)throw new Error(`Unresolved AI-agent policy conflicts: ${policy.unresolvedConflicts.map(c=>c.topic).join(", ")}`);return policy}
