import { useCallback, useEffect, useMemo, useState } from "react";
import { addDays, addMinutes, format, isSameDay, parse, parseISO } from "date-fns";
import { Calendar as CalendarIcon, Car, DollarSign, Loader2, Plus, Search, Users } from "lucide-react";
import type { Appointment, BusinessHours, Customer, ServiceCatalogItem, Vehicle } from "@/shared/types";
import type { AppointmentFormState, CustomerFormData, VehicleFormData } from "@/shared/types/forms";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogClose, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { VehicleYMMSelector } from "@/components/vehicles/VehicleYMMSelector";
import { useRegionalSettings } from "@/contexts/RegionalSettingsContext";
import { bankersRound, formatMoney } from "@/lib/financialMath";
import { formatPhoneInput, normalizePhoneToE164 } from "@/lib/phone";
import { cn } from "@/lib/utils";
import { useFormAutoSave } from "@/hooks/useFormAutoSave";
import { fetchAvailabilityPageData } from "@/application/queries/availability-settings.query";
import { fetchWorkspaceBookedSlots, type BookedSlot } from "@/application/queries/availability.query";
import { resolveCurrentWorkspace } from "@/application/queries/settings.query";
import { nextApi } from "@/lib/nextApiClient";
import { toast } from "@/components/ui/sonner";

interface DayHours { open: string; close: string; is_open?: boolean; isOpen?: boolean }
type WeeklySchedule = Record<string, DayHours>;
type AppointmentSubmitState = AppointmentFormState & { override_availability?: boolean };

interface AppointmentFormProps {
  open:boolean; onOpenChange:(open:boolean)=>void; onSubmit:(data:AppointmentFormState)=>Promise<void>; initialData?:Partial<Appointment>|null;
  customers:Customer[]; vehicles:Vehicle[]; serviceCatalog:ServiceCatalogItem[]; businessHours:BusinessHours; saving:boolean; isEditing:boolean;
  onCreateCustomer:(data:CustomerFormData)=>Promise<Customer|null>; onCreateVehicle:(data:VehicleFormData)=>Promise<Vehicle|null>; businessUserId?:string;
}

const safe=(value:unknown)=>{if(value==null)return"";const text=String(value).trim();return text==="undefined"||text==="null"?"":text;};
const hhmm=(value:string|null|undefined)=>{const match=/^(\d{1,2}):(\d{2})/.exec(String(value||"").trim());return match?`${match[1].padStart(2,"0")}:${match[2]}`:"";};
const dayKey=(date:Date)=>format(date,"EEEE").toLowerCase();
const splitName=(name:string)=>{const parts=name.trim().split(/\s+/).filter(Boolean);return{first_name:parts.shift()||"Customer",last_name:parts.join(" ")};};

function zonedParts(timestamp:number,timezone:string){const parts=new Intl.DateTimeFormat("en-US",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(new Date(timestamp));const get=(type:Intl.DateTimeFormatPartTypes)=>Number(parts.find(p=>p.type===type)?.value||0);return{year:get("year"),month:get("month"),day:get("day"),hour:get("hour"),minute:get("minute"),second:get("second")};}
function workspaceWallClock(date:string,time:string,timezone:string){const dm=/^(\d{4})-(\d{2})-(\d{2})$/.exec(date),tm=/^(\d{2}):(\d{2})$/.exec(time);if(!dm||!tm)return new Date(NaN);const target={year:+dm[1],month:+dm[2],day:+dm[3],hour:+tm[1],minute:+tm[2],second:0};const targetUtc=Date.UTC(target.year,target.month-1,target.day,target.hour,target.minute,0);let guess=targetUtc;for(let i=0;i<3;i++){const p=zonedParts(guess,timezone);guess+=targetUtc-Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second);}return new Date(guess);}

export const AppointmentForm=({open,onOpenChange,onSubmit,initialData,customers,vehicles,serviceCatalog,businessHours,saving,isEditing}:AppointmentFormProps)=>{
  const{formatTime}=useRegionalSettings(); const[formData,setFormData]=useState<AppointmentFormState>({}); const[selectedDate,setSelectedDate]=useState(new Date()); const[bookedSlots,setBookedSlots]=useState<BookedSlot[]>([]);
  const[overrideAvailability,setOverrideAvailability]=useState(false),[sendEmailNotification,setSendEmailNotification]=useState(false),[customerSearch,setCustomerSearch]=useState("");
  const[createdCustomers,setCreatedCustomers]=useState<Customer[]>([]),[createdVehicles,setCreatedVehicles]=useState<Vehicle[]>([]),[creatingCustomer,setCreatingCustomer]=useState(false),[creatingVehicle,setCreatingVehicle]=useState(false);
  const[newCustomer,setNewCustomer]=useState({name:"",email:"",phone:""}),[newVehicle,setNewVehicle]=useState({year:"",make:"",model:"",license_plate:"",vin:""});
  const[weeklySchedule,setWeeklySchedule]=useState<WeeklySchedule>({}),[slotDuration,setSlotDuration]=useState(businessHours.slot_duration_minutes??30),[leadHours,setLeadHours]=useState(businessHours.min_lead_time_hours??0),[bufferBefore,setBufferBefore]=useState(businessHours.buffer_time_before??0),[bufferAfter,setBufferAfter]=useState(businessHours.buffer_time_after??0),[blockedDates,setBlockedDates]=useState<Set<string>>(new Set()),[workspaceTimezone,setWorkspaceTimezone]=useState("UTC");
  const draftKey=`appointment-form-draft:${isEditing?(initialData as{id?:string}|null)?.id??"editing":"new"}`; const{clear:clearDraft,label:draftLabel,lastSavedAt:draftLastSavedAt,restore:restoreDraft}=useFormAutoSave({key:draftKey,value:formData,enabled:open&&Object.keys(formData).length>0});
  const allCustomers=useMemo(()=>{const m=new Map<string,Customer>();[...customers,...createdCustomers].forEach(c=>m.set(c.id,c));return[...m.values()].sort((a,b)=>a.name.localeCompare(b.name));},[customers,createdCustomers]);
  const allVehicles=useMemo(()=>{const m=new Map<string,Vehicle>();[...vehicles,...createdVehicles].forEach(v=>m.set(v.id,v));return[...m.values()];},[vehicles,createdVehicles]);
  const selectedCustomer=useMemo(()=>allCustomers.find(c=>c.id===formData.customer_id)??null,[allCustomers,formData.customer_id]);
  const customerVehicles=useMemo(()=>formData.customer_id?allVehicles.filter(v=>v.customer_id===formData.customer_id):[],[allVehicles,formData.customer_id]);
  const filteredCustomers=useMemo(()=>{const q=customerSearch.trim().toLowerCase();return(q?allCustomers.filter(c=>`${c.name} ${c.email||""} ${c.phone||""}`.toLowerCase().includes(q)):allCustomers).slice(0,100);},[allCustomers,customerSearch]);
  const dateRange=useMemo(()=>Array.from({length:14},(_,i)=>addDays(new Date(),i)),[]);

  useEffect(()=>{if(!open)return;if(initialData){const raw=initialData as Record<string,unknown>;const date=initialData.scheduled_date?parseISO(initialData.scheduled_date):new Date();setSelectedDate(date);setFormData({...initialData,vehicle_id:safe(raw.vehicle_id)||undefined,customer_id:safe(raw.customer_id)||undefined,service_catalog_id:safe(raw.service_catalog_id)||undefined} as AppointmentFormState);return;}const restored=restoreDraft();setSelectedDate(new Date());setFormData(restored??{status:"confirmed",duration_minutes:60,scheduled_date:format(new Date(),"yyyy-MM-dd")});},[initialData,open,restoreDraft]);
  useEffect(()=>{if(!open)return;let cancelled=false;void(async()=>{try{const data=await fetchAvailabilityPageData();if(cancelled)return;const profile=data.profile as Record<string,unknown>|null;setWeeklySchedule(profile?.day_hours&&typeof profile.day_hours==="object"?profile.day_hours as WeeklySchedule:{});setSlotDuration(Number(profile?.slot_duration_minutes??businessHours.slot_duration_minutes??30));setLeadHours(Number(profile?.min_lead_time_hours??businessHours.min_lead_time_hours??0));setBufferBefore(Number(profile?.buffer_time_before??businessHours.buffer_time_before??0));setBufferAfter(Number(profile?.buffer_time_after??businessHours.buffer_time_after??0));setWorkspaceTimezone(typeof profile?.timezone==="string"?profile.timezone:"UTC");setBlockedDates(new Set((data.blocked||[]).map((row:{blocked_date:string})=>row.blocked_date));}catch(e){console.warn("[AppointmentForm] canonical availability load failed",e);}})();return()=>{cancelled=true;};},[open,businessHours]);
  useEffect(()=>{if(!open)return;const date=format(selectedDate,"yyyy-MM-dd");setFormData(p=>({...p,scheduled_date:date}));let cancelled=false;void fetchWorkspaceBookedSlots(date).then(rows=>{if(!cancelled)setBookedSlots(rows.filter(r=>r.id!==(initialData as{id?:string}|null)?.id));}).catch(()=>{if(!cancelled)setBookedSlots([]);});return()=>{cancelled=true;};},[open,selectedDate,initialData]);
  useEffect(()=>{if(!formData.customer_id||formData.vehicle_id||customerVehicles.length!==1)return;const v=customerVehicles[0];setFormData(p=>p.customer_id===v.customer_id&&!p.vehicle_id?{...p,vehicle_id:v.id,vehicle_year:v.year,vehicle_make:v.make,vehicle_model:v.model,vehicle_license:v.license_plate||""}:p);},[formData.customer_id,formData.vehicle_id,customerVehicles]);

  const dayHours=useMemo(()=>{const configured=weeklySchedule[dayKey(selectedDate)];const explicit=typeof configured?.is_open==="boolean"?configured.is_open:typeof configured?.isOpen==="boolean"?configured.isOpen:undefined;if(configured&&explicit!==undefined)return{open:configured.open,close:configured.close,is_open:explicit};const key=dayKey(selectedDate);return{open:hhmm(businessHours.opening_time)||"09:00",close:hhmm(businessHours.closing_time)||"17:00",is_open:businessHours.working_days.some(d=>d.toLowerCase()===key)};},[weeklySchedule,selectedDate,businessHours]);
  const availableSlots=useMemo(()=>{const date=format(selectedDate,"yyyy-MM-dd");if(!dayHours.is_open||blockedDates.has(date))return[];const opening=parse(hhmm(dayHours.open)||"09:00","HH:mm",new Date()),closing=parse(hhmm(dayHours.close)||"17:00","HH:mm",new Date()),interval=Math.max(5,slotDuration||30),serviceMinutes=Math.max(5,Number(formData.duration_minutes)||60),slots:string[]=[];for(let cursor=opening;addMinutes(cursor,serviceMinutes)<=closing;cursor=addMinutes(cursor,interval))slots.push(format(cursor,"HH:mm"));return slots;},[selectedDate,dayHours,blockedDates,slotDuration,formData.duration_minutes]);
  const isSlotBlocked=useCallback((slot:string)=>{const duration=Math.max(5,Number(formData.duration_minutes)||60),slotStart=parse(slot,"HH:mm",new Date()),slotEnd=addMinutes(slotStart,duration);return bookedSlots.some(b=>{const bs=parse(hhmm(b.scheduled_time),"HH:mm",new Date()),start=addMinutes(bs,-bufferBefore),end=addMinutes(addMinutes(bs,b.duration_minutes||60),bufferAfter);return slotStart<end&&slotEnd>start;});},[bookedSlots,formData.duration_minutes,bufferBefore,bufferAfter]);
  const isSlotTooSoon=useCallback((slot:string)=>{if(leadHours<=0)return false;const value=workspaceWallClock(format(selectedDate,"yyyy-MM-dd"),slot,workspaceTimezone);return Number.isNaN(value.getTime())||value.getTime()<Date.now()+leadHours*3600000;},[leadHours,selectedDate,workspaceTimezone]);
  const selectCustomer=useCallback((id:string)=>{const c=allCustomers.find(x=>x.id===id);if(!c)return;const owned=allVehicles.filter(v=>v.customer_id===c.id),only=owned.length===1?owned[0]:null;setCreatingCustomer(false);setCreatingVehicle(owned.length===0);setFormData(p=>({...p,customer_id:c.id,guest_name:c.name,guest_email:c.email||"",guest_phone:c.phone||"",vehicle_id:only?.id??"",vehicle_year:only?.year??"",vehicle_make:only?.make??"",vehicle_model:only?.model??"",vehicle_license:only?.license_plate??""}));},[allCustomers,allVehicles]);
  const selectVehicle=useCallback((id:string)=>{const v=allVehicles.find(x=>x.id===id);if(!v)return;setCreatingVehicle(false);setFormData(p=>({...p,vehicle_id:v.id,vehicle_year:v.year,vehicle_make:v.make,vehicle_model:v.model,vehicle_license:v.license_plate||""}));},[allVehicles]);
  const createCustomer=async()=>{if(!newCustomer.name.trim()){toast.error("Customer name is required");return;}const context=await resolveCurrentWorkspace();if(!context){toast.error("Select a workspace first");return;}try{const response=await nextApi.customers.create({workspace_id:context.workspaceId,...splitName(newCustomer.name),email:newCustomer.email.trim()||undefined,phone:normalizePhoneToE164(newCustomer.phone)||newCustomer.phone.trim()||undefined});const row=response.data as{id:string;first_name?:string;last_name?:string;email?:string|null;phone?:string|null};const c:Customer={id:row.id,name:[row.first_name,row.last_name].filter(Boolean).join(" ")||newCustomer.name.trim(),email:row.email||newCustomer.email.trim(),phone:row.phone||newCustomer.phone.trim()};setCreatedCustomers(p=>[...p,c]);setNewCustomer({name:"",email:"",phone:""});setCreatingCustomer(false);setCreatingVehicle(true);setFormData(p=>({...p,customer_id:c.id,guest_name:c.name,guest_email:c.email,guest_phone:c.phone,vehicle_id:""}));toast.success("Customer created");}catch(e){toast.error(e instanceof Error?e.message:"Failed to create customer");}};
  const createVehicle=async()=>{if(!formData.customer_id){toast.error("Select a customer first");return;}const year=Number(newVehicle.year);if(!year||!newVehicle.make.trim()||!newVehicle.model.trim()){toast.error("Year, make, and model are required");return;}const context=await resolveCurrentWorkspace();if(!context){toast.error("Select a workspace first");return;}try{const response=await nextApi.vehicles.create({workspace_id:context.workspaceId,customer_id:formData.customer_id,year,make:newVehicle.make.trim(),model:newVehicle.model.trim(),vin:newVehicle.vin.trim()||undefined,license_plate:newVehicle.license_plate.trim()||undefined});const row=response.data as{id:string;customer_id?:string|null;year?:number;make?:string;model?:string;vin?:string|null;license_plate?:string|null};const v:Vehicle={id:row.id,customer_id:row.customer_id||formData.customer_id,year:Number(row.year||year),make:row.make||newVehicle.make.trim(),model:row.model||newVehicle.model.trim(),vin:row.vin||undefined,license_plate:row.license_plate||undefined};setCreatedVehicles(p=>[...p,v]);setNewVehicle({year:"",make:"",model:"",license_plate:"",vin:""});setCreatingVehicle(false);setFormData(p=>({...p,vehicle_id:v.id,vehicle_year:v.year,vehicle_make:v.make,vehicle_model:v.model,vehicle_license:v.license_plate||""}));toast.success("Vehicle created");}catch(e){toast.error(e instanceof Error?e.message:"Failed to create vehicle");}};
  const chooseService=(id:string)=>{const s=serviceCatalog.find(x=>x.id===id);setFormData(p=>({...p,service_catalog_id:id,title:s?.name||p.title,estimated_cost:s?.default_price??p.estimated_cost,duration_minutes:s?.estimated_duration||p.duration_minutes||60}));};
  const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();if(!formData.customer_id){toast.error("Select or create a customer");return;}if(!formData.vehicle_id){toast.error("Select or create a vehicle");return;}if(!formData.service_catalog_id){toast.error("Select a service");return;}if(!formData.scheduled_time){toast.error("Select an available time");return;}const phone=normalizePhoneToE164(formData.guest_phone||"");const payload:AppointmentSubmitState={...formData,guest_phone:phone||formData.guest_phone,sendEmailNotification,override_availability:overrideAvailability};await onSubmit(payload);clearDraft();};

  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="flex h-full max-h-full w-full max-w-2xl flex-col bg-card p-0"><DialogHeader className="border-b p-4"><div className="flex items-center justify-between"><DialogClose asChild><Button variant="ghost">Close</Button></DialogClose><DialogTitle>{isEditing?"Edit Appointment":"New Appointment"}</DialogTitle><Button form="appointment-form" type="submit" disabled={saving} variant="ghost" className="text-primary">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:"Save"}</Button></div></DialogHeader><ScrollArea className="flex-1"><form id="appointment-form" onSubmit={handleSubmit} className="space-y-8 p-6">{!isEditing&&draftLastSavedAt&&<p className="rounded-md bg-muted px-3 py-2 text-xs text-muted-foreground">{draftLabel}</p>}
  <section className="space-y-4"><h3 className="flex items-center gap-2 text-lg font-semibold"><CalendarIcon className="h-5 w-5 text-primary"/>Date & Time</h3><ScrollArea className="w-full whitespace-nowrap pb-2"><div className="flex gap-2">{dateRange.map(date=><button type="button" key={date.toISOString()} onClick={()=>setSelectedDate(date)} className={cn("w-20 rounded-lg border-2 p-3",isSameDay(selectedDate,date)?"border-primary bg-primary/10":"border-border/50")}><p className="text-sm font-medium">{format(date,"EEE")}</p><p className="text-2xl font-bold">{format(date,"d")}</p></button>)}</div></ScrollArea>{blockedDates.has(format(selectedDate,"yyyy-MM-dd"))&&<p className="rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-800">This date is blacked out in Availability & Policies.</p>}<div className="grid grid-cols-3 gap-2 sm:grid-cols-4 md:grid-cols-5">{availableSlots.length?availableSlots.map(slot=>{const blocked=isSlotBlocked(slot)||isSlotTooSoon(slot);return <Button key={slot} type="button" variant={formData.scheduled_time===slot?"default":"outline"} disabled={blocked&&!overrideAvailability} onClick={()=>setFormData(p=>({...p,scheduled_time:slot}))} className={cn(blocked&&"line-through opacity-60")}>{formatTime(slot)}</Button>;}):<p className="col-span-full text-center text-sm text-muted-foreground">No bookable slots on this day.</p>}</div><label className="flex items-center gap-2 text-xs text-muted-foreground"><Checkbox checked={overrideAvailability} onCheckedChange={v=>setOverrideAvailability(v===true)}/>Override availability for this staff-created appointment</label></section>
  <section className="space-y-4"><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 text-lg font-semibold"><Users className="h-5 w-5 text-primary"/>Customer</h3><Button type="button" variant="outline" size="sm" onClick={()=>setCreatingCustomer(v=>!v)}><Plus className="mr-1 h-4 w-4"/>New Customer</Button></div>{creatingCustomer?<div className="space-y-3 rounded-lg border p-4"><Input placeholder="Customer name" value={newCustomer.name} onChange={e=>setNewCustomer(v=>({...v,name:e.target.value}))}/><div className="grid gap-3 sm:grid-cols-2"><Input placeholder="Email" type="email" value={newCustomer.email} onChange={e=>setNewCustomer(v=>({...v,email:e.target.value}))}/><Input placeholder="Phone" value={newCustomer.phone} onChange={e=>setNewCustomer(v=>({...v,phone:formatPhoneInput(e.target.value)}))}/></div><Button type="button" onClick={createCustomer}>Create & Select Customer</Button></div>:<><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search customer by name, email, or phone" value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)}/></div><Select value={formData.customer_id||""} onValueChange={selectCustomer}><SelectTrigger><SelectValue placeholder="Select customer"/></SelectTrigger><SelectContent>{filteredCustomers.map(c=><SelectItem key={c.id} value={c.id}>{c.name}{c.phone?` · ${c.phone}`:""}</SelectItem>)}</SelectContent></Select></>}{selectedCustomer&&<div className="grid gap-2 sm:grid-cols-2"><Input value={formData.guest_email||""} onChange={e=>setFormData(v=>({...v,guest_email:e.target.value}))} placeholder="Email"/><Input value={formData.guest_phone||""} onChange={e=>setFormData(v=>({...v,guest_phone:formatPhoneInput(e.target.value)}))} placeholder="Phone"/></div>}</section>
  <section className="space-y-4"><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 text-lg font-semibold"><Car className="h-5 w-5 text-primary"/>Vehicle</h3>{formData.customer_id&&<Button type="button" variant="outline" size="sm" onClick={()=>setCreatingVehicle(v=>!v)}><Plus className="mr-1 h-4 w-4"/>New Vehicle</Button>}</div>{!formData.customer_id?<p className="text-sm text-muted-foreground">Select a customer first.</p>:customerVehicles.length===1&&!creatingVehicle?<div className="rounded-lg border bg-muted/30 p-3 text-sm font-medium">{customerVehicles[0].year} {customerVehicles[0].make} {customerVehicles[0].model}{customerVehicles[0].license_plate?` · ${customerVehicles[0].license_plate}`:""}</div>:customerVehicles.length>1&&!creatingVehicle?<Select value={formData.vehicle_id||""} onValueChange={selectVehicle}><SelectTrigger><SelectValue placeholder="Select one of this customer's vehicles"/></SelectTrigger><SelectContent>{customerVehicles.map(v=><SelectItem key={v.id} value={v.id}>{v.year} {v.make} {v.model}{v.license_plate?` (${v.license_plate})`:""}</SelectItem>)}</SelectContent></Select>:<div className="space-y-3 rounded-lg border p-4"><VehicleYMMSelector value={{year:newVehicle.year,make:newVehicle.make,model:newVehicle.model}} onChange={x=>setNewVehicle(v=>({...v,year:x.year,make:x.make,model:x.model}))}/><div className="grid gap-3 sm:grid-cols-2"><Input placeholder="License plate" value={newVehicle.license_plate} onChange={e=>setNewVehicle(v=>({...v,license_plate:e.target.value}))}/><Input placeholder="VIN (optional)" value={newVehicle.vin} onChange={e=>setNewVehicle(v=>({...v,vin:e.target.value.toUpperCase()}))}/></div><Button type="button" onClick={createVehicle}>Create & Select Vehicle</Button></div>}</section>
  <section className="space-y-4"><h3 className="flex items-center gap-2 text-lg font-semibold"><DollarSign className="h-5 w-5 text-primary"/>Service</h3><Select value={formData.service_catalog_id||""} onValueChange={chooseService}><SelectTrigger><SelectValue placeholder="Select an active service"/></SelectTrigger><SelectContent>{serviceCatalog.map(s=><SelectItem key={s.id} value={s.id}>{s.name} · ${formatMoney(Number(s.default_price||0))}{s.estimated_duration?` · ${s.estimated_duration} min`:""}</SelectItem>)}</SelectContent></Select>{formData.service_catalog_id&&<div className="grid gap-3 sm:grid-cols-2"><div><Label>Duration (minutes)</Label><Input type="number" min={5} value={formData.duration_minutes||""} onChange={e=>setFormData(v=>({...v,duration_minutes:Number(e.target.value)}))}/></div><div><Label>Estimate ($)</Label><Input type="number" step="0.01" min={0} value={formData.estimated_cost??""} onChange={e=>setFormData(v=>({...v,estimated_cost:Number(e.target.value)}))}/></div></div>}</section>
  {!isEditing&&formData.guest_email&&<label className="flex items-center gap-3 rounded-lg border bg-muted/30 p-4"><Checkbox checked={sendEmailNotification} onCheckedChange={c=>setSendEmailNotification(c===true)}/><span><span className="block text-sm font-medium">Send confirmation email</span><span className="text-xs text-muted-foreground">Send to {formData.guest_email}</span></span></label>}<section className="space-y-2"><Label>Internal Notes</Label><Textarea value={formData.notes||""} onChange={e=>setFormData(v=>({...v,notes:e.target.value}))} placeholder="Special instructions, access notes, or internal context"/></section></form></ScrollArea><DialogFooter className="flex flex-col border-t p-4"><div className="flex w-full items-center justify-between text-lg font-bold"><span>Total Estimate</span><span>${formatMoney(bankersRound(Number(formData.estimated_cost||0),2))}</span></div><Button form="appointment-form" type="submit" size="lg" className="w-full gap-2" disabled={saving}>{saving?<Loader2 className="h-5 w-5 animate-spin"/>:<CalendarIcon className="h-5 w-5"/>}{isEditing?"Update Appointment":"Schedule Appointment"}</Button></DialogFooter></DialogContent></Dialog>;
};
