import { useEffect, useMemo, useState } from "react";
import { addDays, addMinutes, format, parse } from "date-fns";
import { Calendar, Car, Plus, Search, Users } from "lucide-react";
import type { Appointment, BusinessHours, Customer, ServiceCatalogItem, Vehicle } from "@/shared/types";
import type { AppointmentFormState, CustomerFormData, VehicleFormData } from "@/shared/types/forms";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "@/components/ui/sonner";
import { VehicleYMMSelector } from "@/components/vehicles/VehicleYMMSelector";
import { fetchAvailabilityPageData } from "@/application/queries/availability-settings.query";
import { fetchWorkspaceBookedSlots, type BookedSlot } from "@/application/queries/availability.query";
import { resolveCurrentWorkspace } from "@/application/queries/settings.query";
import { nextApi } from "@/lib/nextApiClient";
import { formatPhoneInput, normalizePhoneToE164 } from "@/lib/phone";
import { formatMoney } from "@/lib/financialMath";

interface DayHours { open?: string; close?: string; is_open?: boolean; isOpen?: boolean }
type SubmitState = AppointmentFormState & { override_availability?: boolean };
interface Props {
  open:boolean; onOpenChange:(open:boolean)=>void; onSubmit:(data:AppointmentFormState)=>Promise<void>;
  initialData?:Partial<Appointment>|null; customers:Customer[]; vehicles:Vehicle[]; serviceCatalog:ServiceCatalogItem[];
  businessHours:BusinessHours; saving:boolean; isEditing:boolean;
  onCreateCustomer:(data:CustomerFormData)=>Promise<Customer|null>; onCreateVehicle:(data:VehicleFormData)=>Promise<Vehicle|null>; businessUserId?:string;
}
const hm=(v:string|undefined)=>{const m=/^(\d{1,2}):(\d{2})/.exec(v||"");return m?`${m[1].padStart(2,"0")}:${m[2]}`:"";};
const splitName=(name:string)=>{const p=name.trim().split(/\s+/);return{first_name:p.shift()||"Customer",last_name:p.join(" ")};};
function zonedParts(ms:number,tz:string){const p=new Intl.DateTimeFormat("en-US",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(ms));const n=(t:Intl.DateTimeFormatPartTypes)=>Number(p.find(x=>x.type===t)?.value||0);return{y:n("year"),m:n("month"),d:n("day"),h:n("hour"),min:n("minute")};}
function wallClock(date:string,time:string,tz:string){const d=date.split("-").map(Number),t=time.split(":").map(Number);const target=Date.UTC(d[0],d[1]-1,d[2],t[0],t[1]);let guess=target;for(let i=0;i<3;i++){const p=zonedParts(guess,tz);guess+=target-Date.UTC(p.y,p.m-1,p.d,p.h,p.min);}return new Date(guess);}

export const AppointmentForm=({open,onOpenChange,onSubmit,initialData,customers,vehicles,serviceCatalog,businessHours,saving,isEditing}:Props)=>{
  const [form,setForm]=useState<SubmitState>({}); const [date,setDate]=useState(new Date()); const [booked,setBooked]=useState<BookedSlot[]>([]);
  const [schedule,setSchedule]=useState<Record<string,DayHours>>({}); const [blackouts,setBlackouts]=useState(new Set<string>()); const [slotMinutes,setSlotMinutes]=useState(30); const [leadHours,setLeadHours]=useState(0); const [before,setBefore]=useState(0); const [after,setAfter]=useState(0); const [tz,setTz]=useState("UTC"); const [override,setOverride]=useState(false);
  const [search,setSearch]=useState(""); const [newCustomer,setNewCustomer]=useState({name:"",email:"",phone:""}); const [newVehicle,setNewVehicle]=useState({year:"",make:"",model:"",plate:""}); const [addingCustomer,setAddingCustomer]=useState(false); const [addingVehicle,setAddingVehicle]=useState(false); const [extraCustomers,setExtraCustomers]=useState<Customer[]>([]); const [extraVehicles,setExtraVehicles]=useState<Vehicle[]>([]);
  const allCustomers=useMemo(()=>[...customers,...extraCustomers],[customers,extraCustomers]); const allVehicles=useMemo(()=>[...vehicles,...extraVehicles],[vehicles,extraVehicles]);
  const customerVehicles=useMemo(()=>form.customer_id?allVehicles.filter(v=>v.customer_id===form.customer_id):[],[allVehicles,form.customer_id]);
  const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return allCustomers.filter(c=>!q||`${c.name} ${c.email||""} ${c.phone||""}`.toLowerCase().includes(q)).slice(0,100);},[allCustomers,search]);
  useEffect(()=>{if(!open)return;const start=initialData?.scheduled_date?new Date(`${initialData.scheduled_date}T12:00:00`):new Date();setDate(start);setForm(initialData?{...initialData,customer_id:(initialData as any).customer_id||undefined,vehicle_id:(initialData as any).vehicle_id||undefined,service_catalog_id:(initialData as any).service_catalog_id||undefined}:{status:"confirmed",duration_minutes:60,scheduled_date:format(start,"yyyy-MM-dd")});},[open,initialData]);
  useEffect(()=>{if(!open)return;void fetchAvailabilityPageData().then(data=>{const p=data.profile as any;setSchedule(p?.day_hours||{});setBlackouts(new Set((data.blocked||[]).map((r:{blocked_date:string})=>r.blocked_date)));setSlotMinutes(Number(p?.slot_duration_minutes??businessHours.slot_duration_minutes??30));setLeadHours(Number(p?.min_lead_time_hours??businessHours.min_lead_time_hours??0));setBefore(Number(p?.buffer_time_before??businessHours.buffer_time_before??0));setAfter(Number(p?.buffer_time_after??businessHours.buffer_time_after??0));setTz(p?.timezone||"UTC");}).catch(()=>toast.error("Could not load scheduling availability"));},[open,businessHours]);
  useEffect(()=>{if(!open)return;const d=format(date,"yyyy-MM-dd");setForm(f=>({...f,scheduled_date:d,scheduled_time:undefined}));void fetchWorkspaceBookedSlots(d).then(rows=>setBooked(rows.filter(r=>r.id!==(initialData as any)?.id))).catch(()=>setBooked([]));},[open,date,initialData]);
  useEffect(()=>{if(form.customer_id&&!form.vehicle_id&&customerVehicles.length===1){const v=customerVehicles[0];setForm(f=>({...f,vehicle_id:v.id,vehicle_year:v.year,vehicle_make:v.make,vehicle_model:v.model,vehicle_license:v.license_plate||""}));}},[form.customer_id,form.vehicle_id,customerVehicles]);
  const dayKey=format(date,"EEEE").toLowerCase(); const raw=schedule[dayKey]; const isOpen=typeof raw?.is_open==="boolean"?raw.is_open:typeof raw?.isOpen==="boolean"?raw.isOpen:businessHours.working_days.some(d=>d.toLowerCase()===dayKey); const openTime=hm(raw?.open)||hm(businessHours.opening_time)||"09:00",closeTime=hm(raw?.close)||hm(businessHours.closing_time)||"17:00";
  const slots=useMemo(()=>{if(!isOpen||blackouts.has(format(date,"yyyy-MM-dd")))return[];const a=parse(openTime,"HH:mm",new Date()),z=parse(closeTime,"HH:mm",new Date()),duration=Math.max(5,Number(form.duration_minutes)||60),out:string[]=[];for(let x=a;addMinutes(x,duration)<=z;x=addMinutes(x,Math.max(5,slotMinutes)))out.push(format(x,"HH:mm"));return out;},[isOpen,blackouts,date,openTime,closeTime,form.duration_minutes,slotMinutes]);
  const restricted=(slot:string)=>{const s=parse(slot,"HH:mm",new Date()),e=addMinutes(s,Math.max(5,Number(form.duration_minutes)||60));const conflict=booked.some(b=>{const bs=parse(hm(b.scheduled_time),"HH:mm",new Date()),be=addMinutes(bs,b.duration_minutes||60);return s<addMinutes(be,after)&&e>addMinutes(bs,-before);});const soon=wallClock(format(date,"yyyy-MM-dd"),slot,tz).getTime()<Date.now()+leadHours*3600000;return conflict||soon;};
  const selectCustomer=(id:string)=>{const c=allCustomers.find(x=>x.id===id);if(!c)return;const owned=allVehicles.filter(v=>v.customer_id===id),v=owned.length===1?owned[0]:undefined;setForm(f=>({...f,customer_id:id,guest_name:c.name,guest_email:c.email||"",guest_phone:c.phone||"",vehicle_id:v?.id||undefined,vehicle_year:v?.year,vehicle_make:v?.make,vehicle_model:v?.model,vehicle_license:v?.license_plate||""}));setAddingVehicle(owned.length===0);};
  const createCustomer=async()=>{if(!newCustomer.name.trim())return toast.error("Customer name is required");const ctx=await resolveCurrentWorkspace();if(!ctx)return;const response=await nextApi.customers.create({workspace_id:ctx.workspaceId,...splitName(newCustomer.name),email:newCustomer.email||undefined,phone:normalizePhoneToE164(newCustomer.phone)||undefined});const r=response.data as any,c:Customer={id:r.id,name:[r.first_name,r.last_name].filter(Boolean).join(" ")||newCustomer.name,email:r.email||newCustomer.email,phone:r.phone||newCustomer.phone};setExtraCustomers(v=>[...v,c]);setAddingCustomer(false);setForm(f=>({...f,customer_id:c.id,guest_name:c.name,guest_email:c.email,guest_phone:c.phone,vehicle_id:undefined}));setAddingVehicle(true);};
  const createVehicle=async()=>{if(!form.customer_id)return toast.error("Select a customer first");const year=Number(newVehicle.year);if(!year||!newVehicle.make||!newVehicle.model)return toast.error("Year, make, and model are required");const ctx=await resolveCurrentWorkspace();if(!ctx)return;const response=await nextApi.vehicles.create({workspace_id:ctx.workspaceId,customer_id:form.customer_id,year,make:newVehicle.make,model:newVehicle.model,license_plate:newVehicle.plate||undefined});const r=response.data as any,v:Vehicle={id:r.id,customer_id:form.customer_id,year:r.year||year,make:r.make||newVehicle.make,model:r.model||newVehicle.model,license_plate:r.license_plate||newVehicle.plate};setExtraVehicles(x=>[...x,v]);setForm(f=>({...f,vehicle_id:v.id,vehicle_year:v.year,vehicle_make:v.make,vehicle_model:v.model,vehicle_license:v.license_plate||""}));setAddingVehicle(false);};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!form.customer_id||!form.vehicle_id||!form.service_catalog_id||!form.scheduled_time)return toast.error("Select a customer, vehicle, service, and time");await onSubmit({...form,override_availability:override} as SubmitState);};
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[95vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{isEditing?"Edit Appointment":"New Appointment"}</DialogTitle></DialogHeader><form onSubmit={submit} className="space-y-6">
    <section className="space-y-3"><Label className="flex gap-2"><Calendar className="h-4 w-4"/>Date & Time</Label><div className="flex gap-2 overflow-x-auto">{Array.from({length:14},(_,i)=>addDays(new Date(),i)).map(d=><Button type="button" key={d.toISOString()} variant={format(d,"yyyy-MM-dd")===format(date,"yyyy-MM-dd")?"default":"outline"} onClick={()=>setDate(d)}>{format(d,"EEE d")}</Button>)}</div><div className="grid grid-cols-4 gap-2">{slots.map(s=><Button type="button" key={s} variant={form.scheduled_time===s?"default":"outline"} disabled={restricted(s)&&!override} onClick={()=>setForm(f=>({...f,scheduled_time:s}))}>{s}</Button>)}</div><label className="flex gap-2 text-sm"><Checkbox checked={override} onCheckedChange={v=>setOverride(v===true)}/>Override restricted availability</label></section>
    <section className="space-y-3"><div className="flex justify-between"><Label className="flex gap-2"><Users className="h-4 w-4"/>Customer</Label><Button type="button" size="sm" variant="outline" onClick={()=>setAddingCustomer(v=>!v)}><Plus className="h-4 w-4"/>New</Button></div>{addingCustomer?<div className="grid gap-2"><Input placeholder="Name" value={newCustomer.name} onChange={e=>setNewCustomer(v=>({...v,name:e.target.value}))}/><Input placeholder="Email" value={newCustomer.email} onChange={e=>setNewCustomer(v=>({...v,email:e.target.value}))}/><Input placeholder="Phone" value={newCustomer.phone} onChange={e=>setNewCustomer(v=>({...v,phone:formatPhoneInput(e.target.value)}))}/><Button type="button" onClick={createCustomer}>Create customer</Button></div>:<><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customers"/></div><Select value={form.customer_id||""} onValueChange={selectCustomer}><SelectTrigger><SelectValue placeholder="Select customer"/></SelectTrigger><SelectContent>{filtered.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></>}</section>
    <section className="space-y-3"><div className="flex justify-between"><Label className="flex gap-2"><Car className="h-4 w-4"/>Vehicle</Label>{form.customer_id&&<Button type="button" size="sm" variant="outline" onClick={()=>setAddingVehicle(v=>!v)}><Plus className="h-4 w-4"/>New</Button>}</div>{customerVehicles.length>1&&!addingVehicle?<Select value={form.vehicle_id||""} onValueChange={id=>{const v=customerVehicles.find(x=>x.id===id);setForm(f=>({...f,vehicle_id:id,vehicle_year:v?.year,vehicle_make:v?.make,vehicle_model:v?.model,vehicle_license:v?.license_plate||""}));}}><SelectTrigger><SelectValue placeholder="Select vehicle"/></SelectTrigger><SelectContent>{customerVehicles.map(v=><SelectItem key={v.id} value={v.id}>{v.year} {v.make} {v.model}</SelectItem>)}</SelectContent></Select>:customerVehicles.length===1&&!addingVehicle?<p className="rounded border p-3">{customerVehicles[0].year} {customerVehicles[0].make} {customerVehicles[0].model}</p>:form.customer_id&&<div className="space-y-2"><VehicleYMMSelector value={{year:newVehicle.year,make:newVehicle.make,model:newVehicle.model}} onChange={v=>setNewVehicle(x=>({...x,year:v.year,make:v.make,model:v.model}))}/><Input placeholder="License plate" value={newVehicle.plate} onChange={e=>setNewVehicle(v=>({...v,plate:e.target.value}))}/><Button type="button" onClick={createVehicle}>Create vehicle</Button></div>}</section>
    <section className="space-y-3"><Label>Service</Label><Select value={form.service_catalog_id||""} onValueChange={id=>{const s=serviceCatalog.find(x=>x.id===id);setForm(f=>({...f,service_catalog_id:id,title:s?.name,estimated_cost:s?.default_price,duration_minutes:s?.estimated_duration||60}));}}><SelectTrigger><SelectValue placeholder="Select service"/></SelectTrigger><SelectContent>{serviceCatalog.map(s=><SelectItem key={s.id} value={s.id}>{s.name} · ${formatMoney(Number(s.default_price||0))}</SelectItem>)}</SelectContent></Select></section>
    <section><Label>Internal notes</Label><Textarea value={form.notes||""} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></section><Button type="submit" className="w-full" disabled={saving}>{saving?"Saving…":isEditing?"Update Appointment":"Schedule Appointment"}</Button>
  </form></DialogContent></Dialog>;
};
